package com.element.fleet.ordering.enums;

public enum OrderingVehiclePageEnum {

	ORDERING_VEHICLE_FLEET_SPEC_RADIO_ID("fleet-spec"), 
	ORDERING_VEHICLE_PRICE_AND_CONFIG_RADIO_ID("price-config"),
	ORDERING_VEHICLE_BUILD_FROM_SCRATCH_RADIO_ID("scratch"), 
	ORDERING_VEHICLE_VIN_RADIO_ID("vinSearch"),
	ORDERING_VEHICLE_FLEET_SPEC_FIRST_RESULT_CSS("#fleet-spec-view #order-specs-table > tbody > tr"),
	ORDERING_VEHICLE_FLEET_SPEC_FIRST_RESULT_XPATH("//table[@id='order-specs-table']//td[contains(text(),'Client Approved')]"),
	ORDERING_VEHICLE_PRICE_CONFIG_FIRST_RESULT_XPATH("//table[@id='order-specs-table']//td[contains(text(),'Price Config')]"),
	ORDERING_VEHICLE_FIRST_SEARCHED_FLEET_SPEC_SECTION_XPATH("//div[@id='fleet-spec-view']//table[@id='order-specs-table']//tbody/tr/td[position]"),
	ORDERING_VEHICLE_FLEET_SPEC_SEARCH_CSS("#fleet-spec-view  input[aria-controls=order-specs-table]"),
	ORDERING_VEHICLE_PRINCE_CONFIG_SEARCH_CSS("#price-config-view  input[aria-controls=order-specs-table]"),
	ORDERING_VEHICLE_PRINCE_CONFIG_SEARCH_XPATH("(//input[@ aria-controls='order-specs-table'])[2]"),
	ORDERING_VEHICLE_PRINCE_CONFIG_FIRST_RESULT_CSS("#price-config-view #order-specs-table > tbody > tr"),
	ORDERING_VEHICLE_FIRST_SEARCHED_PRINCE_CONFIG_SECTION_XPATH("//div[@id='price-config-view']//table[@id='order-specs-table']//tbody/tr/td[position]"),
	ORDERING_VEHICLE_FLEET_SPEC_EXTERIOR_COLOR_XPATH("(//div[contains(@class, 'sm-2 color__square')])[1]"),
	ORDERING_VEHICLE_FLEET_IMAGE_ID("vehicle__ext_carousel"),
	ORDERING_VEHICLE_FLEET_SPEC_COLOR_ACCEPT_CSS("div.modal.fade.in button#modal-accept-btn"),
	ORDERING_VEHICLE_FLEET_SPEC_INTERIOR_COLOR_ACCEPT_XPATH("(//*[@id=\"modal-accept-btn\"])"),
	ORDERING_VEHICLE_FLEET_SPEC_INTERIOR_SELCTOR_COLOR_ID("int-carousel"),
	ORDERING_VEHICLE_FLEET_SPEC_INTERIOR_COLOR_XPATH("(//div[@data-interior='true'])[1]"),
	ORDERING_VEHICLE_BUILD_FROM_SCRATCH_YEAR_DROPDOWN_ID("vcle__year"),
	ORDERING_VEHICLE_VIN_SEARCH_BOX_ID("vehicleStockSearchId"), 
	ORDERING_VEHICLE_VIN_SEARCH_BUTTON_ID("search-btn"),
	ORDERING_VEHICLE_BUILD_FROM_SCRATCH_MAKE_TEXTBOX_XPATH("(//INPUT[@class='select2-search__field'])[1]"),
	ORDERING_VEHICLE_BUILD_FROM_SCRATCH_SEARCH_RESULTS_CSS("#scratch-table > tbody"),
	ORDERING_VEHICLE_VEHICLE_INFORMATION_TAB_ID("chassisInfoTab"),
	ORDERING_VEHICLE_DIOTAB_ID("installedOptTab"),
	ORDERING_VEHICLE_DIOSECTION_ID("dataDIO"),
	ORDERING_VEHICLE_DIO_ADDNEW_ID("add-new-btn"),
	ORDERING_VEHICEL_DIO_TABLE_XPATH("//table[@id='dio-tabel']/tbody"),
	ORDERING_VEHICLE_DIOSECTION_OPTIONCODESEARCHBOX_NAME("searchOptCode"),
	ORDERING_VEHICLE_DIOSECTION_OPTIONDESCRIPTIONSEARCHBOX_NAME("searchOptCode"),
	ORDERING_VEHICLE_DIOSECTION_SEARCHDIO_SUGGESTION_SECTION_CSS("div.tt-menu.tt-open"),
	ORDERING_VEHICLE_DIOSECTION_SEARCHDIO_SUGGESTION_CSS("div.tt-suggestion.tt-selectable.empty > strong"),
	ORDERING_VEHICLE_DIOSECTION_OPTIONCODE_FIRSTSEARCHRESULT_CLASS("tt-highlight"),
	ORDERING_VEHICLE_DIOSECTION_OPTIONCODE_DATA_XPATH("//td[contains(text(),'There are currently no Fleet Specification Saved f')]"),
	ORDERING_VEHICLE_BUILD_FROM_SCRATCH_MODEL_TEXTBOX_XPATH("(//INPUT[@class='select2-search__field'])[2]"),
	ORDERING_VEHICLE_BUILD_FROM_SCRATCH_FIRST_RESULT_CSS("#scratch-table > tbody > tr:nth-child(1)"),
	ORDERING_VEHICLE_BUILD_FROM_SCRATCH_RESULT_ROWS_CSS("#scratch-table > tbody > tr"),
	ORDERING_VEHICLE_VIN_SEARCH_FIRST_RESULT_CSS("#VINListMatch > tbody > tr:nth-child(1) > td:nth-child(6) > button"),
	ORDERING_VEHICLE_VIN_SEARCH_SECTION_CSS("#VINListMatch > tbody"),
	ORDERING_VEHICLE_VIN_SEARCH_ROWS_XPATH("//table[@id='VINListMatch']/tbody/tr"),
	ORDERING_VEHICLE_VIN_SEARCH_ROWS_COLUMN_XPATH(".//td[position]"),
	ORDERING_VEHICLE_UPFIT_TAB_INFO_CSS("a[data-target='upfitInfo']"),
	ORDERING_VEHICLE_UPFIT_TAB_ADDUPFITPO_ID("add-line-items-btn"),
	ORDERING_VEHICLE_UPFIT_TAB_ADDLINEITEM_UPFIT_NAME_NAME("upfitName"),
	ORDERING_VEHICLE_UPFIT_TAB_ADDLINEITEM_UPFIT_ADDRESS_NAME("address"),
	ORDERING_VEHICLE_UPFIT_TAB_ADDLINEITEM_FILLCITY_STATE_COUNTRY_BUTTON_XPATH("//input[@class='btn-fill-driver-address fill-address']"),
	ORDERING_VEHICLE_UPFIT_TAB_ADDLINEITEM_ZIP_NAME("zip"),
	ORDERING_VEHICLE_UPFIT_TAB_ADDLINEITEM_ID("addAdhocLinePOItem"),
	ORDERING_VEHICLE_UPFIT_TAB_ADHOCITEMPIECESECTION_ID("upfit-requests-line-items"),
	ORDERING_VEHICLE_UPFIT_TAB_ADHOCITEM_CATEGORY_DROPDOWN_NAME("itemCategoryCode"),
	ORDERING_VEHICLE_UPFIT_TAB_LINEITEM_CODE_NAME("partNumber"),
	ORDERING_VEHICLE_UPFIT_TAB_LINEITEM_DESC_NAME("line-item-desc"),
	ORDERING_VEHICLE_UPFIT_TAB_LINEITEM_OPTION_PRICE_NAME("option-price"),
	ORDERING_VEHICLE_UPFIT_TAB_LINEITEM_EXT_DESC_XPATH("//div[@id='adhocItemPiece']//input[@name='extendedDescription']"),
	ORDERING_VEHICLE_UPFIT_TAB_LINEITEM_QTY_XPATH("//*[@id='adhocItemPiece']/div[5]/input"),
	ORDERING_VEHICLE_UPFIT_TAB_LINEITEM_PRICE_NAME("clientNegotiatedPrice"),
	ORDERING_VEHICLE_UPFIT_TAB_SEARCH_INFO_ID("upfit-spec-search"),
	ORDERING_VEHICLE_UPFIT_TAB_ADD_UPFIT_REQUEST_ID("add-upfit-request"),
	ORDERING_VEHICLE_UPFIT_TAB_ADD_UPFIT_REQUEST_SUPPLIER_NAME_ID("supplier-name"),
	ORDERING_VEHICLE_UPFIT_TAB_ADD_UPFIT_REQUEST_SUPPLIER_QUOTE_ID("supplier-quote"),
	ORDERING_VEHICLE_UPFIT_TAB_ADD_UPFIT_REQUEST_ADDRESS_ID("upfit-address"),
	ORDERING_VEHICLE_UPFIT_TAB_ADD_UPFIT_REQUEST_ZIP_ID("upfit-zip"),
	ORDERING_VEHICLE_UPFIT_TAB_ADD_UPFIT_REQUEST_AUTO_FILL_ID("fill-city-state"),
	ORDERING_VEHICLE_UPFIT_TAB_SEARCH_FIRST_RESULT_INFO_CSS("#upfitInfo > div:nth-child(1) > div > span > div > div > div"),
	ORDERING_VEHICLE_ALL_ADDED_UPFITS_CSS("div.upfitSpecItem.panel"),
	ORDERING_VEHICLE_ADDED_UPFIT_ITEM_TABLES_XPATH(".//div[@id='upfitItemsNgroups']//table//tbody/tr/td/input[not(@disabled)]//ancestor::table"),
	ORDERING_VEHICLE_ADDED_UPFIT_ITEM_TABLE_ROWS_XPATH(".//tbody/tr/td/input[not(@disabled)]//ancestor::tr"),
	ORDERING_VEHICLE_ADDED_UPFIT_TABLE_ROW_CHECK_RADIO_XPATH(".//td[1]/input"),
	ORDERING_VEHICLE_ADDED_UPFIT_TABLE_ROW_DATA_CODE_COLUMNS_XPATH(".//td[2]"),
	ORDERING_VEHICLE_ADDED_UPFIT_TABLE_ROW_DATA_CATEGORY_COLUMNS_XPATH(".//td[3]"),
	ORDERING_VEHICLE_ADDED_UPFIT_TABLE_ROW_DATA_DESCRIPTION_COLUMNS_XPATH(".//td[4]"),
	ORDERING_VEHICLE_ADDED_UPFIT_TABLE_ROW_DATA_EXTENDED_DESCRIPTION_COLUMNS_XPATH(".//td[5]"),
	ORDERING_VEHICLE_ADDED_UPFIT_TABLE_ROW_DATA_QUANTITY_COLUMNS_XPATH(".//td[6]"),
	ORDERING_VEHICLE_ADDED_UPFIT_TABLE_ROW_DATA_OPTION_PRICE_COLUMNS_XPATH(".//td[7]"),
	ORDERING_VEHICLE_ADDED_UPFIT_TABLE_ROW_DATA_ESTIMATED_COST_COLUMNS_XPATH(".//td[8]"),
	ORDERING_VEHICLE_NAME_FLEET_CONFIG_PAGE_XPATH("//div[contains(text(),'PriceAndConfig')]"),
	ORDERING_VEHICLE_INFORMATION_FLEET_SPEC_LEFT_ID("specs__vehicle__left"),
	ORDERING_VEHICLE_INFORMATION_FLEET_SPEC_RIGHT_CSS("#optionsListOfSpecs"),
	ORDERING_VEHICLE_INFORMATION_FLEET_SPEC_TABLE_SECTIONS_XPATH("//div[@id='optionsListOfSpecs']//div[@class='wholeParent']"),
	ORDERING_VEHICLE_INFORMATION_FLEET_SPEC_TABLE_ROWS_XPATH(".//ul[contains(@class,'col-sm-12 config_option list-unstyled list-inline') and @data-state='S']"),
	ORDERING_VEHICLE_INFORMATION_FLEET_SPEC_CHECKED_RADIO_BUTTON_XPATH(".//input[contains(@class,'selection__box')]"),
	ORDERING_VEHICLE_INFORMATION_FLEET_SPEC_CODE_LABEL_XPATH(".//li[contains(@class,'code')]"),
	ORDERING_VEHICLE_INFORMATION_FLEET_SPEC_DESCRIPTION_LABEL_XPATH(".//li[contains(@class,'description')]"),
	ORDERING_VEHICLE_INFORMATION_FLEET_SPEC_INVOICE_LABEL_XPATH(".//li[contains(@class,'invoice cost_items')]"),
	ORDERING_VEHICLE_INFORMATION_FLEET_SPEC_MSRP_LABEL_XPATH(".//li[contains(@class,'msrp cost_items')]"),
	ORDERING_VEHICLE_INFORMATION_FLEET_SPEC_TABLE_INTERIOR_COLOURS_ROW_XPATH("//div[@data-header='Interior Colors']//following-sibling::div/ul"),
	ORDERING_VEHICLE_INFORMATION_FLEET_SPEC_TABLE_EXTERIOR_COLOURS_ROW_XPATH("//div[@data-header='Primary Colors']//following-sibling::div/ul"),
	ORDERING_VEHICLE_DIO_TABLE_NOT_EMPTY_CSS("table#dio-tabel tr.data-table__row"),
	ORDERING_VEHICLE_DIO_TABLE_ROWS_XPATH("//table[@id='dealerInstalled-table']/tbody/tr"),
	ORDERING_VEHICLE_DIO_QUANTITY_TEXTBOX_XPATH(".//input[@name='quantity']"),
	ORDERING_VEHICLE_DIO_OPTION_CODE_TEXTBOX_XPATH(".//input[@name='optionCode']"),
	ORDERING_VEHICLE_DIO_DESCRIPTION_TEXTBOX_XPATH(".//input[@name='optionDesc']"),
	ORDERING_VEHICLE_DIO_PRICE_NOT_TO_EXCEED_TEXTBOX_XPATH(".//input[@name='maxPriceAmt']"),
	ORDERING_VEHICLE_DIO_POST_PRODUCTION_OPTION_CHECKBOX_XPATH(".//input[@name='postProductionInd']"),
	ORDERING_VEHICLE_AVAILABLE_ASSOCIATED_UPFIT_PANELS_DIV_XPATH("//div[@id='upfitSpecsContainer']//div[@class='upfitSpecItem panel']/div[@class='panel-heading' and @associated-item]"),
	ORDERING_VEHICLE_AVAILABLE_UPFIT_PANELS_DIV_XPATH("//div[@id='upfitSpecsContainer']//div[@class='upfitSpecItem panel']/div[@class='panel-heading' and not(@associated-item)]"),
	ORDERING_VEHICLE_AVAILABLE_UPFIT_PANELS_DIV_ID("upfit-requests-line-items"),
	ORDERING_VEHICLE_AVAILABLE_UPFIT_PANEL_HEADING_DIV_XPATH(".//div[contains(@class,'panel-title')]"),
	ORDERING_ATTACHMENT_ID_XPATH("//table[@id='comp-file-table']//td[@class='sorting_1']"),
	ORDERING_UPFIT_LINE_ITEM_RADIO_BUTTON_XPATH("//div[@class='groupItemWrapper']//h4[contains(text(),'%s')]//following::div[1]//input"),
	ORDERING_UPFIT_LIST_IN_UPFIT_INFO_TAB_XPATH("//div[@id='upfitSpecsContainer']//div[@class='upfitSpecItem panel']"),
	ORDERING_UPFIT_GROUP_LIST_IN_UPFIT_INFO_TAB_XPATH("//div[@class='groupItemWrapper']//h4"),
	ORDERING_VEHICLE_BUILDFROMSCRATCH_PICTURE_XPATH("//tr[@role='row']/th[text()=' Picture ']"),
	ORDERING_VEHICLE_BUILD_FROM_SCRATCH_MODEL_HEADING_XPATH("//table[@id='scratch-table']/thead/tr/th[text()=' Model Code ']"),
	ORDERING_VEHICLE_BUILD_FROM_SCRATCH_MODEL_VALUES_XPATH("//table[@id='scratch-table']/tbody/tr/td[6]"),
	ORDERING_VEHICLE_BUILD_FROM_SCRATCH_INVOICE_HEADING_XPATH("//table[@id='scratch-table']/thead/tr/th[text()=' Invoice ']"),
	ORDERING_VEHICLE_BUILD_FROM_SCRATCH_INVOICE_VALUES_XPATH("//table[@id='scratch-table']/tbody/tr/td[7]"),
	ORDERING_VEHICLE_CHANGE_MAKE_XPATH("//div[@id='createOrder__content']//div[@class='pull-left btn changeModel']"),
	ORDERING_VEHICLE_FLEET_SPEC_LIST_XPATH("//table[@id='order-specs-table']//tbody//tr"),
	ORDERING_VEHICLE_BUILD_FROM_SCRATCH_LIST_XPATH("//table[@id='scratch-table']//tbody//tr"),
	ORDERING_VEHICLE_DELETE_LINE_ITEM_UPFIT_XPATH("//button[@data-action='delete-second-row']//i[@class='fa fa-trash']"),
	ORDERING_VEHICLE_UNDO_DELETE_LINE_ITEM_UPFIT_XPATH("//button[@data-action='delete-second-row']//i[@class='fa fa-undo']"),
	ORDERING_VEHICLE_DELETE_UPFIT_XPATH("//button[@id='upper-delete']//i[@class='fa fa-trash']"),
	ORDERING_VEHICLE_UNDO_DELETE_UPFIT_XPATH("//button[@id='upper-delete']//i[@class='fa fa-undo']"),
	ORDERING_VEHICLE_NO_RECORD_FOUND_XPATH("//td[@class='dataTables_empty']"),
	ORDERING_VEHICLE_BUILD_FROM_SCRATCH_FIRST_VEHICLE_XPATH("//*[@id='scratch-table']/tbody/tr[1]"),
	ORDERING_VEHICLE_BUILD_FROM_SCRATCH_MAKE_TEXT_BOX_XPATH("(//*[@id='vehicle__buildNew']//input)[1]"),
	ORDERING_VEHICLE_CHANGE_LOCK_XPATH("//div[@class='lock-unlock-super-user-warning lock-warning-message']"),
	ORDERING_VEHICLE_CHANGE_LOCK_EDITMODE_CONTINUE_BUTTON_XPATH("//button[@id='edit-mode']"),
	ORDERING_VEHICLE_TOTAL_ADD_COUNT_ID("dio-tabel_info"),
	ORDERING_VEHICLE_PAGINATION_SELECT_XPATH("//select[@name='dio-tabel_length']"),
	ORDERING_VEHICLE_CHECKBOX_1_ID("data-table__checkbox-7"),
	ORDERING_VEHICLE_CHECKBOX_2_ID("data-table__checkbox-6"),
	ORDERING_VEHICLE_DELETE_XPATH("//i[@class='table-action-panel__icon fa fa-trash']"),
	ORDERING_VEHICLE_POPUP_CLASS("message"),
	ORDERING_VEHICLE_POPUP_YESOPTION_XPATH("//button[@id='modal-accept-btn']"),
	ORDERING_VEHICLE_LIST_DELETE_XPATH("//button[@class='text-button text-button--overflow js-row-menu-button']"),
	ORDERING_VEHICLE_LIST_DELETE_BUTTON_ID("row-delete-btn-0"),
	ORDERING_VEHICLE_PREVIOUS_PAGE_XPATH("//span[@id='dio-tabel_previous']"),
	ORDERING_VEHICLE_NEXT_PAGE_XPATH("//span[@id='dio-tabel_next']"),
	ORDERING_VEHICLE_DIO_ERROR_MSG1_XPATH("//tr[@class='data-table__row odd']//td[4]//div[1]//span[1]"),
	ORDERING_VEHICLE_DIO_ERROR_MSG2_XPATH("//tr[@class='data-table__row odd']//td[6]//div[1]//span[1]"),
	ORDERING_VEHICLE_DIO_SAVE_ORDER_XPATH("//button[@id='orderSaveNextId']"),
	ORDERING_VEHICLE_DIO_TABLE_XPATH("//table[@id='queue-table']//tbody//tr"),
	ORDERING_VEHICLE_DIO_OPTION_CODE_DESCRIPTION_LABEL_XPATH("//label[contains(text(),'Search for Dealer Installed Options')]"),
	ORDERING_VEHICLE_DIO_OPTION_CODE_DESCRIPTION_TEXTBOX_NAME("searchOptCode"),
	ORDERING_VEHICLE_DIO_FIRST_COLUMN_ROW_RESULT_CSS("table#dio-tabel > tbody > tr"),
	ORDERING_VEHICLE_DIO_FIRST_COLUMN_ROW_DATA_CSS("table#dio-tabel > tbody > tr >td:nth-child(number)"),
	ORDERING_VEHICLE_DIO_FIRST_SEARCH_RESULT_XPATH("//div[@class='tt-dataset tt-dataset-initBloodhound']//div[1]"),
	ORDERING_VEHICLE_DIO_ROW_OPTION_CODE_XPATH("//input[@name='optionCode']"),
	ORDERING_VEHICLE_DIO_ROW_OPTION_DESC_XPATH("//input[@name='optionDesc']"),
	ORDERING_VEHICLE_DIO_COLUMN_HEADER_CSS("#dio-tabel_wrapper.dataTables_wrapper  div.dataTables_scrollHead th"),
	ORDERING_VEHICLE_DIO_SUPPLIER_TO_SHIP_TOOL_TIP_XPATH("//div[@class='dataTables_scrollHeadInner']//i[@class='fa fa-info fa-circle-info']"),
	ORDERING_VEHICLE_DIO_VEHICLE_INFO_XPATH("//div[@class='unit-info']"),
	ORDERING_VEHICLE_DIO_QUANTITY_XPATH("//input[@name='quantity']"),
	ORDERING_VEHICLE_DIO_PRICE_NOT_TO_EXCEED_XPATH("//input[@name='maxPriceAmt']"),
	ORDERING_VEHICLE_DIO_DELETE_OPTIONS_XPATH("(//button[@class='text-button text-button--overflow js-row-menu-button'])[1]"),
	ORDERING_VEHICLE_DIO_DELETE_BUTTON_XPATH("//a[@id='row-delete-btn-0']"),
	ORDERING_VEHICLE_DIO_DELETE_POPUP_YES_BUTTON_XPATH("//button[@id='modal-accept-btn']"),
	ORDERING_VEHICLE_DIO_SUGGESION_ERROR_XPATH("//strong[contains(text(),'No results found!')]"),
	ORDERING_VEHICLE_DIO_LINE_ITEM_CHECKBOX_XPATH("//table[@id='dio-tabel']//tr[1]//td[1]//input[@type='checkbox']"),
	ORDERING_VEHICLE_DIO_LINE_ITEM_OPTIONS_XPATH("//table[@id='dio-tabel']//tr[1]//div[@class='row-actions dropdown']/button"),
	ORDERING_VEHICLE_OPTION_LIST_OF_SPEC_TABLE_HEADER_XPATH("//div[@id='optionsListOfSpecs']/ul[1]/li"),
	ORDERING_VEHICLE_OPTION_LIST_OF_SPEC_INVOICE_PRICE_XPATH("//div[@id='optionsListOfSpecs']//li[contains(@class,'col-sm-2 invoice')]"),
	ORDERING_VEHICLE_OPTION_LIST_OF_SPEC_CHECKBOXES_XPATH("//div[@id='optionsListOfSpecs']//li/input[1]"),
	ORDERING_VEHICLE_OPTION_LIST_OF_SPEC_OPTION_TYPE_XPATH("//div[@id='optionsListOfSpecs']//li/select[contains(@class,'options-type-dropdown')]"),
	ORDERING_VEHICLE_OPTION_LIST_OF_SPEC_ADJ_TYPE_XPATH("//div[@id='optionsListOfSpecs']//li/select[contains(@class,'dollar-select-dropdown')]"),
	ORDERING_VEHICLE_OPTION_LIST_OF_SPEC_ADJ_TYPE_VALUE_XPATH("//div[@id='optionsListOfSpecs']//input[contains(@class,'input-driver_price')]"),
	ORDERING_VEHICLE_OPTION_LIST_OF_SPEC_DRIVER_PRICE_XPATH("//div[@id='optionsListOfSpecs']//li[@class='col-sm-1 driver-price-value']"),
	;
	
	private String value;

	OrderingVehiclePageEnum(String value) {
		this.value = value;
	}

	public String getValue() {
		return value;
	}

	@Override
	public String toString() {
		return value;
	}
	
}
