package com.element.fleet.ordering.enums;

public enum OrderingBOOnOrderQueuePageEnum {

	ORDERING_BO_OOQ_CSS("div#queues h1#queue-page-title"), 
	ORDERING_BO_OOQ_SEARCHFIELDS_ID("standard"),
	ORDERING_BO_OOQ_RELEASE_CHECKBOX_NAME("order-check"),
	ORDERING_BO_OOQ_RELEASE_BUTTON_XPATH("//span[contains(text(),'Release')]"),
	ORDERING_BO_OOQ_RELEASE_BUTTON_DISABLED_CSS("div.btn.green.btn-shared.releaseOrder.disabled"),
	ORDERING_BO_OOQ_APPROVE_BUTTON_XPATH("//div[@class='btn custom-action green btn-shared approveOrder']//span"),
	ORDERING_BO_OOQ_APPROVE_BUTTON_DISABLED_CSS("div.btn.green.btn-shared.approveOrder.disabled"),
	ORDERING_BO_OOQ_SEARCHICON_CSS("div.btn.green.btn-shared.search"),
	ORDERING_BO_OOQ_SEARCHRESULT_XPATH("//*[@id='queue-table']/tbody/tr[1]"),
	ORDERING_BO_OOQ_SEARCHRESULT_TABLE_XPATH("//*[@id='queue-table']/tbody/tr[1]"),
	ORDERING_BO_OOQ_SEARCHRESULT_TABLE_ROWS_XPATH("//table[@id='queue-table']/tbody/tr"),
	ORDERING_BO_OOQ_SEARCHRESULT_TABLE_NO_DATA_XPATH("//div[@class='dataTables_scroll']//td[contains(text(),'No data available in table')]"),
	ORDERING_BO_OOQ_NUMBER_OF_RECORDS_VIEWTABLE_XPATH("//div[@class='dataTables_info']"),
	ORDERING_BO_OOQ_SAERCHRESULT_ROW_VIEWTABLE_XPATH("(//div[@id='queue-table']//table//tbody//tr//td[@data-name])[1]"),
	ORDERING_BO_PQ_STANDARDVIEW_CLASS("table-wrapper"),
	ORDERING_BO_OOQ_ORDER_TYPE_DROPDOWN_XPATH("//select[@class='orderType']"),
	ORDERING_BO_OOQ_ORDER_TYPE_DROPDOWN_CHANGED_OPTION_XPATH("//select[@class='orderType']//option[@selected=''][@data-code-type='OT']"),
	ORDERING_BO_OOQ_GENERALINFOBTN_XPATH("//a[@id='generalInfoTabId']"),
	ORDERING_BO_OOQ_APPROVAL_XPATH("//a[@id='approvalIndicatorsTabId']"),
	ORDERING_BO_OOQ_DRIVERBTN_XPATH("//a[@id='driverInfoTabId']"),
	ORDERING_BO_OOQ_VEHICLEBTN_XPATH("//a[@id='vehicleInfoTabId']"),
	ORDERING_BO_OOQ_DIOBTN_XPATH("//a[@id='dioInfoTabId']"),
	ORDERING_BO_OOQ_UPFITBTN_XPATH("//a[@id='upfitInfoTabId']"),
	ORDERING_BO_OOQ_BILLINGBTN_XPATH("//a[@id='billingInfoTabId']"),
	ORDERING_BO_OOQ_TITLEREGISTRATIONBTN_XPATH("//a[@id='titleInfoTabId']"),
	ORDERING_BO_OOQ_INSURANCEBTN_XPATH("//a[@id='insuranceInfoTabId']"),
	ORDERING_BO_OOQ_DEALERBTN_XPATH("//a[@id='dealerInfoTabId']"),
	ORDERING_BO_OOQ_CUSTOMFIELDSBTN_XPATH("//a[@id='customFieldsInfoTabId']"),
	ORDERING_BO_OOQ_GENERALORDER_CSS("form#generalInfo-form > div.title-line h1"),
	ORDERING_BO_OOQ_ADDSTATUS_CSS("form#generalInfo-form > div.tab-content > div.po-status > div > h2"),
	ORDERING_BO_OOQ_DELETESTATUS_CSS("form#generalInfo-form > div.tab-content > div.po-status > div.delete-status-wrapper > h2"),
	ORDERING_BO_OOQ_USEDUNITINFO_CSS("form#generalInfo-form > div.tab-content > div.used-unit > div.used-unit-section > div >h2"),
	ORDERING_BO_OOQ_APPROVALTITLE_CSS("form#approvalIndicators-form > div.title-line h1"),
	ORDERING_BO_OOQ_DRIVERTITLE_CSS("form#driverInfo-form > div.title-line h1"),
	ORDERING_BO_OOQ_GARAGINGADDRESSTITLE_CSS("form#driverInfo-form > div.tab-content > div.sub-section >h2"),
	ORDERING_BO_OOQ_DELIVERYADDRESSTITLE_CSS("form#driverInfo-form > div.tab-content div.delivery-address-section > div > h2"),
	ORDERING_BO_OOQ_VEHICLETITLE_CSS("form#vehicleInfo-form > div.title-line h1"),
	ORDERING_BO_OOQ_DIOTITLE_CSS("form#dioInfo-form > div.title-line h1"),
	ORDERING_BO_OOQ_UPFITTITLE_CSS("form#upfitInfo-form > div.title-line h1"),
	ORDERING_BO_OOQ_BILLINGTITLE_CSS("form#billingInfo-form > div.title-line h1"),
	ORDERING_BO_OOQ_DPITITLE_CSS("form#billingInfo-form > div.driver-payment-info h2"),
	ORDERING_BO_OOQ_TITLEANDREGISTRATIONTITLE_CSS("form#titleInfo-form > div.title-line h1"),
	ORDERING_BO_OOQ_TITLEADDRESSTITLE_CSS("form#titleInfo-form > div.tab-content > div.sub-section > div:nth-child(2) h2"),
	ORDERING_BO_OOQ_REGISTRATIONADDRESSTITLE_CSS("form#titleInfo-form > div.tab-content > div.sub-section > div:nth-child(3) h2"),
	ORDERING_BO_OOQ_LIENHOLDERADDRESSTITLE_CSS("form#titleInfo-form > div.tab-content > div.sub-section > div:nth-child(4) h2"),
	ORDERING_BO_OOQ_INSURANCETITLE_CSS("form#insuranceInfo-form > div.title-line h1"),
	ORDERING_BO_OOQ_DEALERTITLE_CSS("form#dealerInfo-form > div.title-line h1"),
	ORDERING_BO_OOQ_DELIVERINGDEALERTITLE_CSS("form#dealerInfo-form > div.tab-content div.delivering-dealer h2"),
	ORDERING_BO_OOQ_ORDERINGGDEALERTITLE_CSS("form#dealerInfo-form > div.tab-content div.ordering-dealer h2"),
	ORDERING_BO_OOQ_CUSTOMFIELDSTITLE_CSS("form#customFieldsInfo-form > div.title-line h1"),
	ORDERING_BO_OOQ_CUSTOMDRIVERFIELDSTITLE_CSS("form#customFieldsInfo-form > div.tab-content div.custom-driver-fields h3"),
	ORDERING_BO_OOQ_DIOADDBTN_XPATH("//label[@id='add-dio']"),
	ORDERING_BO_OOQ_DIO_OPTIONCODETEXTBOX_XPATH("//table[@id='dio-table']//following::input[@id='optionCode0-0']"),
	ORDERING_BO_OOQ_DIO_DESCRIPTIONTXTBOX_XPATH("//table[@id='dio-table']//following::input[@id='optionDescription0-0']"),
	ORDERING_BO_OOQ_DIO_QUANTITYTXTBOX_NAME("dioInfo[dioRequestList][0][quantity]:number"),
	ORDERING_BO_OOQ_DIO_OPTIONPRICETXTBOX_NAME("dioInfo[dioRequestList][0][maxPriceAmt]:number"),
	ORDERING_BO_OOQ_UPFIT_UPFITSPECSEARCHTXTBOX_XPATH("//input[@id='upfit-spec-search']"),
	ORDERING_BO_OOQ_UPFIT_UPFITSPECSEARCH_FIRSTOPTION_CSS("#upfit-spec-section> div:nth-child(1) >div>div>div>span>div>div>div"),
	ORDERING_BO_OOQ_UPFIT_SAVE_XPATH("//div[@id='save']"),
	ORDERING_BO_OOQ_UPFIT_ADD_WORKTYPEDRPDWN_XPATH("//select[@id='work-type']"),
	ORDERING_BO_OOQ_UPFIT_UPFITTERNAME_XPATH("//span[@id='upfitter-name']"),
	ORDERING_BO_OOQ_UPFIT_SUPPLIERNAME_XPATH("(//label[contains(text(),'Supplier')])[2]//following::div[15]"),
	ORDERING_BO_OOQ_UPFIT_WORKTYPE_XPATH("//select[@id='workType45850']//following-sibling::option[@selected]"),
	ORDERING_BO_OOQ_UPFIT_UPFITSPECID_XPATH("//label[contains(text(),'Upfit Spec ID')]//following::span[1]"),
	ORDERING_BO_OOQ_TITLEANDREGISTRATION_PLATETYPEDRPDWN_XPATH("//select[contains(@name,'titleInfo[plateType]')]"),
	ORDERING_BO_OOQ_TITLEANDREGISTRATION_PLATETYPESELECTED_XPATH("//select[contains(@name,'titleInfo[plateType]')]//following-sibling::option[@selected][2]"),
	ORDERING_BO_OOQ_TITLEANDREGISTRATION_WHOTOTITLESELECTED_XPATH("//select[contains(@name,'titleInfo[whoToTitle]')]//following-sibling::option[@selected][2]"),
	ORDERING_BO_OOQ_TITLEANDREGISTRATION_WHOTOTITLEDRPDWN_XPATH("//select[contains(@name,'titleInfo[whoToTitle]')]"),
	ORDERING_BO_OOQ_TITLEANDREGISTRATION_TITLEOWNERNAMETXTBOX_XPATH("//input[contains(@name,'titleInfo[titleName]')]"),
	ORDERING_BO_OOQ_TITLEANDREGISTRATION_REGISTRATIONOWNERNAMETXTBOX_XPATH("//input[contains(@name,'titleInfo[registrationName]')]"),
	ORDERING_BO_OOQ_TITLEANDREGISTRATION_LIENHOLDEROWNERNAMETXTBOX_XPATH("//input[contains(@name,'titleInfo[lienholderName]')]"),
	ORDERING_BO_OOQ_UPFIT_ADD_UPFITSPECID_XPATH("//span[@id='fancy-upfit-spec-id']"),
	ORDERING_BO_OOQ_UPFIT_ADD_UPFITSPECNAME_XPATH("//span[@id='upfit-spec-name']"),
	ORDERING_BO_OOQ_UPFIT_ADD_OPTIONCODETXT_XPATH("//input[@id='optionCode0']"),
	ORDERING_BO_OOQ_UPFIT_ADD_EXTENDEDDESCRIPTIONTXT_XPATH("//input[@id='extendedDescription0']"),
	ORDERING_BO_OOQ_UPFIT_ADD_OPTIONPRICE_XPATH("//input[@id='amount0']"),
	ORDERING_BO_OOQ_UPFIT_OPTIONCODETXT_XPATH("//input[contains(@id,'optionCode')]"),
	ORDERING_BO_OOQ_UPFIT_OPTIONDESCRIPTIONTXT_XPATH("//input[contains(@id,'optionDescription')]"),
	ORDERING_BO_OOQ_UPFIT_EXTENDEDOPTIONDESCRIPTIONTXT_XPATH("//textarea[contains(@id,'extendedDescription')]"),
	ORDERING_BO_OOQ_UPFIT_OPTIONPRICETXT_XPATH("//input[contains(@id,'amount')]"),
	ORDERING_BO_OOQ_DENY_BUTTON_XPATH("//div[@id='credit-queue']//span[contains(text(),'Deny')]"),
	ORDERING_BO_OOQ_DENY_BUTTON_DISABLED_CSS("div.btn.green.btn-shared.denyOrder.disabled"),
	ORDERING_BO_OOQ_DENY_ACCEPT_OPTION_CSS("div.btn.green.proceed"),
	ORDERING_BO_OOQ_DENY_CANCEL_OPTION_CSS("div.btn.red.cancel"),
	ORDERING_BO_OOQ_EXPORT_BUTTON_CSS("div.btn.blue.btn-shared.queue-export"),
	ORDERING_BO_OOQ_DATA_TABLE_SCROLL_BODY_CSS("div.dataTables_scrollBody"),
	ORDERING_BO_OOQ_LOG_COLUMN_TABLE_DATA_XPATH("//div[@id='queue-table_wrapper']//div[@class='dataTables_scrollBody']//td[@data-name='logNumber']"),
	ORDERING_BO_OOQ_LOG_COLUMN_TABLE_HEADING_XPATH("//div[@id='queue-table_wrapper']//div[@class='dataTables_scrollHead']//th[@data-name='logNumber']"),
	ORDERING_BO_OOQ_AUDIT_INSERT_TIME_COLUMN_TABLE_DATA_XPATH("//div[@id='queue-table_wrapper']//div[@class='dataTables_scrollBody']//td[@data-name='auditInsertTime']"),
	ORDERING_BO_OOQ_AUDIT_INSERT_TIME_COLUMN_TABLE_HEADING_XPATH("//div[@id='queue-table_wrapper']//div[@class='dataTables_scrollHead']//th[@data-name='auditInsertTime']"),
	ORDERING_BO_OOQ_NEXTPAGINATEBTN_XPATH("//span[@class='next paginate_button']"),
	ORDERING_BO_OOQ_LASTPAGINATEBTN_XPATH("//span[@class='last paginate_button']"),
	ORDERING_BO_OOQ_PAGINATEPAGETXT_XPATH("//span[@class='paginate_page']"),
	ORDERING_BO_OOQ_PAGINATEOFTXT_XPATH("//span[@class='paginate_of']"),
	ORDERING_BO_OOQ_PREVIOUSPAGINATEBTN_XPATH("//span[@class='previous paginate_button']"),
	ORDERING_BO_OOQ_FIRSTPAGINATEBTN_XPATH("//span[@class='first paginate_button']"),
	ORDERING_BO_OOQ_COMMENT_LINK_XPATH("//a[contains(text(),'Comments')]"),
	ORDERING_BO_INTERNAL_COMMENT_ADD_BUTTON_XPATH("//div[@class='btn action add']//i"),
	ORDERING_BO_INTERNAL_COMMENT_COMMENT_TYPE_DROPDOWN_XPATH("//select[@name='commentType']"),
	ORDERING_BO_INTERNAL_COMMENT_COMMENT_TEXTAREA_XPATH("//div[@class='comment-text']//textarea[@name='comment']"),
	ORDERING_BO_INTERNAL_COMMENT_SAVE_BUTTON_XPATH("//textarea[@name='comment']//following::input[@value='Save']"),
	ORDERING_BO_INTERNAL_COMMENT_COMMENT_SAVED_MESSAGE_XPATH("//div[contains(text(),'Comment(s) saved')]"),
	ORDERING_BO_INTERNAL_COMMENT_CANCEL_BUTTON_XPATH("//input[@class='btn cancel-close']"),
	ORDERING_BO_INTERNAL_COMMENT_ADD_NEW_COMMENT_LINK_XPATH("//a[contains(text(),'Add new comment')]"),
	ORDERING_BO_INTERNAL_COMMENT_COMMENT_TYPE_DROPDOWN_2_XPATH("//a[contains(text(),'Add new comment')]//following::select[2]"),
	ORDERING_BO_INTERNAL_COMMENT_COMMENT_TYPE_DROPDOWN_3_XPATH("//a[contains(text(),'Add new comment')]//following::select[3]"),
	ORDERING_BO_INTERNAL_COMMENT_COMMENT_TEXTAREA_2_XPATH("//a[contains(text(),'Add new comment')]//following::textarea[2]"),
	ORDERING_BO_INTERNAL_COMMENT_COMMENT_TEXTAREA_3_XPATH("//a[contains(text(),'Add new comment')]//following::textarea[3]"),
	ORDERING_BO_INTERNAL_COMMENT_SEARCH_INPUT_XPATH("//input[@type='search']"),
	ORDERING_BO_INTERNAL_COMMENT_COMMENT_TYPE_LIST_XPATH("//table[@id='comments-table']//th[contains(text(),'Type')]//following::tr//td[2]"),
	ORDERING_BO_INTERNAL_COMMENT_COMMENT_LIST_XPATH("//table[@id='comments-table']//th[contains(text(),'Type')]//following::tr//td[3]"),
	ORDERING_BO_INTERNAL_COMMENT_COMMENT_TYPE_HEADER_XPATH("//table[@id='comments-table']//th[contains(text(),'Type')]"),
	ORDERING_BO_INTERNAL_COMMENT_COMMENT_HEADER_XPATH("//table[@id='comments-table']//th[contains(text(),'Comment')]"),
	ORDERING_BO_INTERNAL_COMMENT_EXT_CHECKBOX_XPATH("//tr[@data-comment-type='EXT'][1]//input"),
	ORDERING_BO_INTERNAL_COMMENT_IACK_CHECKBOX_XPATH("//tr[@data-comment-type='IACK'][1]//input"),
	ORDERING_BO_INTERNAL_COMMENT_INT_CHECKBOX_XPATH("//tr[@data-comment-type='INT'][1]//input"),
	ORDERING_BO_INTERNAL_COMMENT_EDIT_BUTTON_XPATH("//div[@class='btn action edit']"),
	ORDERING_BO_INTERNAL_COMMENT_EDITED_COMMENT_EXT_XPATH("//tr[@data-comment-type='EXT'][1]//td[3]"),
	ORDERING_BO_INTERNAL_COMMENT_EDITED_COMMENT_IACK_XPATH("//tr[@data-comment-type='IACK'][1]//td[3]"),
	ORDERING_BO_INTERNAL_COMMENT_EDITED_COMMENT_INT_XPATH("//tr[@data-comment-type='INT'][1]//td[3]"),
	ORDERING_BO_INTERNAL_COMMENT_EXT_EDIT_LINK_XPATH("//tr[@data-comment-type='EXT'][1]//a[1]"),
	ORDERING_BO_INTERNAL_COMMENT_IACK_EDIT_LINK_XPATH("//tr[@data-comment-type='IACK'][1]//a[1]"),
	ORDERING_BO_INTERNAL_COMMENT_INT_EDIT_LINK_XPATH("//tr[@data-comment-type='INT'][1]//a[1]"),
	ORDERING_BO_INTERNAL_COMMENT_DELETE_BUTTON_XPATH("//div[@class='btn action delete']"),
	ORDERING_BO_INTERNAL_COMMENT_DELETE_ACCEPT_DELETE_BUTTON_XPATH("//input[@class='btn delete']"),
	ORDERING_BO_INTERNAL_COMMENT_DELETE_CLOSE_DELETE_BUTTON_XPATH("//input[@class='btn delete']//following-sibling::input"),
	ORDERING_BO_INTERNAL_COMMENT_DELETE_SUCCESS_MESSAGE_XPATH("//div[contains(text(),'Comment(s) deleted successfully')]t"),
	ORDERING_BO_INTERNAL_COMMENT_EXT_DELETE_LINK_XPATH("//tr[@data-comment-type='EXT'][1]//a[2]"),
	ORDERING_BO_INTERNAL_COMMENT_IACK_DELETE_LINK_XPATH("//tr[@data-comment-type='IACK'][1]//a[2]"),
	ORDERING_BO_INTERNAL_COMMENT_INT_DELETE_LINK_XPATH("//tr[@data-comment-type='INT'][1]//a[2]"),
	ORDERING_BO_INTERNAL_COMMENT_EXPORT_BUTTON_XPATH("//div[@class='btn action export']"),
	ORDERING_BO_ON_ORDER_ORDERCURRENTSTATUS_XPATH("//td[@data-name='currentStatus']"),
	ORDERING_BO_ON_ORDER_ROW_ACTION_STATUS_XPATH("//a[@class='row-action status']"),
	ORDERING_BO_ON_ORDER_PO_LATEST_ORDER_STATUS_XPATH("(((//table[contains(@id,'status-table')])[1]//following::tr)[2]/td)[3]"),
	ORDERING_BO_ATTACHMENT_BUTTON_XPATH("//div[@id='mainContainer']//button[@class='pull-left btn attachmentsBtn']"),
	ORDERING_BO_UPLOAD_NEW_ATTACHMENT_BUTTON_XPATH("//div[@id='editOrder']//a[text()='Upload New Attachment']"),
	ORDERING_BO_OOQ_UPFIT_UPFITTERSPECSEARCHTXTBOX_ID("upfitter-search"),
	ORDERING_BO_OOQ_UPFIT_UPFITTERSPECSEARCH_FIRSTOPTION_CSS("div.tt-dataset-upfitterSearch>div"),
	ORDERING_BO_OOQ_UPFIT_LEAD_TIME_ID("lead-time"),
	ORDERING_BO_OOQ_UPFIT_WORK_TYPE_ID("work-type"),
	ORDERING_BO_OOQ_UPFIT_ADD_PO_CSS("a.addPoAddRow"),
	ORDERING_BO_OOQ_UPFIT_OPTION_CODE_ID("optionCode0"),
	ORDERING_BO_OOQ_UPFIT_OPTION_CATEGORY_ID("optionCategory0"),
	ORDERING_BO_OOQ_UPFIT_EXTENDED_DESCRIPTION_ID("extendedDescription0"),
	ORDERING_BO_OOQ_UPFIT_OPTION_PRICE_ID("amount0"),
	ORDERING_BO_OOQ_UPFIT_OPTION_DESCRIPTION_ID("optionDescription0"),
	ORDERING_BO_OOQ_UPFIT_WORK_TYPE_XPATH("//select[contains(@id, 'workType')]"),
	ORDERING_BO_OOQ_UPFIT_SUPPLIER_QUOTE_NUMBER_CSS("input#supplier-quote"),
	ORDERING_BO_OOQ_UPFIT_SUPPLIER_QUOTE_DATE_CSS("input#supplier-quote-date"),
	ORDERING_BO_OOQ_SECOND_DIO_OPTIONCODETEXTBOX_XPATH("//table[@id='dio-table']//following::input[@id='optionCode0-1']"),
	ORDERING_BO_OOQ_SECOND_DIO_DESCRIPTIONTXTBOX_XPATH("//table[@id='dio-table']//following::input[@id='optionDescription0-1']"),
	ORDERING_BO_OOQ_SECOND_DIO_QUANTITYTXTBOX_XPATH("//table[@id='dio-table']//following::input[@id='optionQuantity0-1']"),
	ORDERING_BO_OOQ_SECOND_DIO_OPTIONPRICETXTBOX_XPATH("//table[@id='dio-table']//following::input[@id='amount0-1']"),
	ORDERING_BO_OOQ_DIO_ROW_CSS("#dio-table>tbody>tr"),
	ORDERING_BO_OOQ_TELEMATICS_INDICATOR_XPATH("//label[text()='Telematics Indicator']/..//following-sibling::div/span"),
	ORDERING_BO_OOQ_SEARCH_TABLE_ROWS_NO_DATA_PRESENT_XPATH("//table[@id='queue-table']/tbody/tr/td"),
	;
	
	private String value;

	OrderingBOOnOrderQueuePageEnum(String value) {
		this.value = value;
	}

	public String getValue() {
		return value;
	}

	@Override
	public String toString() {
		return value;
	}

}
