package com.element.fleet.ordering.enums;

public enum OrderingBOOnOrderProjectPageEnum {

	ORDERING_BO_PROJECTQ_STANDARD_VIEW_ID("btnDropdownViews"),
	ORDERING_BO_PROJECTQ_ADD_PROJECT_LINK_XPATH("//a[contains(text(),'Add Project')]"),
	ORDERING_BO_PROJECTQ_SEARCH_CLIENT_TEXBOX_NAME("search-client"),
	ORDERING_BO_PROJECTQ_SELECT_SEARCH_CLIENT_XPATH("//label[contains(text(),'Search Client')]//following::pre[@aria-hidden='true']//following::div[@class='tt-suggestion tt-selectable empty']"),
	ORDERING_BO_PROJECTQ_PROJECT_NAME_TEXBOX_ID("client-project-name"),
	ORDERING_BO_PROJECTQ_PROJECT_DESCRIPTION_TEXBOX_ID("client-project-description"),
	ORDERING_BO_PROJECTQ_DUE_DATE_TEXTBOX_XPATH("//input[@id='due-date']"),
	ORDERING_BO_PROJECTQ_ADD_PROJECT_BUTTON_ID("app-project"),
	ORDERING_BO_PROJECTQ_CREATE_DATE_COLUMN_XPATH("//th[@data-name='createdBy'][contains(text(),'Created')]"),
	ORDERING_BO_PROJECTQ_SELECT_FIRST_SEARCHED_XPATH("//table[@id='queue-table']//tbody//tr[1]//td[@data-name='projectID']"),
	ORDERING_BO_PROJECTQ_SELECT_FIRST_SEARCHED_NEW_XPATH("//table[@id='project-queue-table']//tbody//tr[1]//td[@data-name='clientNumber']"),
	ORDERING_BO_PROJECTQ_CREATE_QUOTE_BUTTON_XPATH("//div[@id='details-workflow__header-wrapper']//button[1]"),
	ORDERING_BO_PROJECTQ_CREATE_QUOTE_SAVE_BUTTON_XPATH("//div[@class='footer-action-panel js-footer-action-panel']//div[@class='button-group--right']//button[@id='footer-save-button']"),
	ORDERING_BO_PROJECTQ_PROJECT_NAME_LIST_XPATH("//td[@data-name='projectName']"),
	ORDERING_BO_PROJECTQ_PROJECT_PAGE_TITLE_XPATH("//div[contains(text(),'Project Details')]"),
	ORDERING_BO_PROJECTQ_SELECT_QUOTE_QUEUE_XPATH("//div[@id='rfq-queue']//span[contains(text(),'Quote Queue')]"),
	ORDERING_BO_PROJECTQ_CLICK_ADD_QUOTE_BUTTON_XPATH("//a[contains(text(),'Add Quote')]"),
	ORDERING_BO_PROJECTQ_ENTER_QUOTE_NUMBER_TEXTBOX_ID("quote-number"),
	ORDERING_BO_PROJECTQ_QUOTE_DATE_TEXTBOX_XPATH("//input[@name='quote-date']"),
	ORDERING_BO_PROJECTQ_QUOTE_TYPE_DROPDOWN_ID("quote-type"),
	ORDERING_BO_PROJECTQ_UPFITTER_SEARCH_XPATH("//input[@name='supplier-search']"),
	ORDERING_BO_PROJECTQ_SELECT_FIRST_SEARCH_UPFITTER_XPATH("//div[@class='tt-dataset tt-dataset-supplierSearch']//div[1]"),
	ORDERING_BO_PROJECTQ_INSTALLER_SEARCH_XPATH("//input[@name='installer-search']"),
	ORDERING_BO_PROJECTQ_SELECT_FIRST_SEARCH_INSTALLER_XPATH("//div[@class='tt-dataset tt-dataset-installerSearch']//div[1]"),
	ORDERING_BO_PROJECTQ_DROP_SHIP_SEARCH_XPATH("//input[@name='drop-ship-search']"),
	ORDERING_BO_PROJECTQ_SELECT_FIRST_SEARCH_DROP_SHIP_XPATH("//div[@class='tt-dataset tt-dataset-drop-shipSearch']//div[1]"),
	ORDERING_BO_PROJECTQ_SHIP_TO_DROPDOWN_ID("ship-to-search-by"),
	ORDERING_BO_PROJECTQ_WORK_TYPE_DROPDOWN_ID("work-type"),
	ORDERING_BO_PROJECTQ_CHASSIS_SEARCH_BY_DROPDOWN_ID("chassis-search-by"),
	ORDERING_BO_PROJECTQ_CHASSIS_SEARCH_TEXTBOX_XPATH("//input[@id='chassis-search']"),
	ORDERING_BO_PROJECTQ_SELECT_FIRST_SEARCH_CHASSIS_XPATH("//div[@class='tt-dataset tt-dataset-chassisSearch']//div[1]"),
	ORDERING_BO_PROJECTQ_ADD_LINE_ITEMS_XPATH("//div[@id='add-item']"),
	ORDERING_BO_PROJECTQ_ADD_CODE_LINE_ITEMS_ID("part-number"),
	ORDERING_BO_PROJECTQ_CATEGORY_LINE_ITEMS_XPATH("//select[@id='category']"),
	ORDERING_BO_PROJECTQ_DESCRIPTION_LINE_ITEMS_XPATH("//input[@placeholder='Description']"),
	ORDERING_BO_PROJECTQ_EXTENDED_DESCRIPTION_LINE_ITEMS_ID("extended-description"),
	ORDERING_BO_PROJECTQ_PRICE_LINE_ITEMS_XPATH("//input[@id='price']"),
	ORDERING_BO_PROJECTQ_SAVE_QUOTE_XPATH("//div[@id='saveQuote']"),
	ORDERING_BO_PROJECTQ_FIRT_SAVED_QUOTE_PROJECT_DETAILS_XPATH("//table[@id='queue-table']//tbody//td[@data-name='quoteId'][1]"),
	ORDERING_BO_PROJECTQ_CONVERT_TO_UPFIT_FLEET_SPEC_LINK_XPATH("//div[@id='convert']//i"),
	ORDERING_BO_PROJECTQ_UPFIT_FLEET_SPEC_NAME_TEXT_BOX_ID("spec-name"),
	ORDERING_BO_PROJECTQ_UPFIT_FLEET_SPEC_LEADTIME_TEXT_BOX_ID("lead-time"),
	ORDERING_BO_PROJECTQ_UPFIT_FLEET_SPEC_DESCRIPTION_TEXTAREA_ID("spec-description"),
	ORDERING_BO_PROJECTQ_UPFIT_FLEET_SPEC_CLIENT_DROPDOWN_ID("spec-client"),
	ORDERING_BO_PROJECTQ_CONVERT_TO_UPFIT_SPEC_OK_BUTTON_ID("convert-to-upfit-spec"),
	ORDERING_BO_PROJECTQ_ELEMENT_APPROVE_LINK_XPATH("//div[@id='elementApprove']"),
	ORDERING_BO_PROJECTQ_CLIENT_APPROVE_LINK_XPATH("//div[@id='clientApprove']"),
	ORDERING_BO_PROJECTQ_ATTACH_TO_FLEET_SPEC_LINK_XPATH("//div[@id='attachFleet']"),
	ORDERING_BO_PROJECTQ_WAIT_FOR_FLEET_SEPC_ASSOCIATION_PAGE_XPATH("//div[contains(text(),'Upfit Spec / Fleet Spec Association')]"),
	ORDERING_BO_PROJECTQ_SEARCH_FLEET_SPECIFICATION_TEXTBOX_XPATH("//input[@name='search-fleet-spec-search']"),
	ORDERING_BO_PROJECTQ_FIRST_SEARCH_FLEET_SPECIFICATION_XPATH("//div[@class='tt-dataset tt-dataset-upfitSpecSearch']//div[1]"),
	ORDERING_BO_PROJECTQ_FLEET_SPECIFICATION_SAVE_BUTTON_XPATH("//div[@id='saveFleetSpecAttach']"),
	ORDERING_BO_PROJECT_DETAILS_CLOSE_BUTTON_CSS("i.fa.fa-close"),
	ORDERING_BO_PROJECTQ_PROJECTDETAILS_LABEL_VALUE("Project Details"),
	ORDERING_BO_PROJECTQ_PROJECTDETAILS_LABEL_XPATH("//div[@class= 'subscreen-title']"),
	ORDERING_BO_PROJECTQ_PROJECTDETAILS_CLOSE_UPFIT_SPEC_MAINTENANCE_XPATH("//div[@id='upfitAttachments']//preceding::div[1]//i"),
	ORDERING_BO_PROJECTQ_PROJECTDETAILS_CLOSE_EDIT_UPFIT_QUOTE_XPATH("//div[@id='quoteAttachments']//preceding::div[1]//i"),
	ORDERING_BO_PROJECTQ_PROJECTDETAILS_CLOSE_EDIT_UPFIT_QUOTE_OK_BUTTON_XPATH("//button[@id='yes-cancel']//i"),
	ORDERING_BO_PROJECTQ_PROJECTDETAILS_CLOSE_PAGE_XPATH("//div[@id='saveProject']//following::div[1]//i"),
	ORDERING_BO_UPFIT_SPEC_QUEUES_CREATE_DATE_COLUMN_XPATH("//div[@class='dataTables_scrollHead']//th[@data-name='createDate']"),
	ORDERING_BO_UPFIT_SPEC_QUEUES_UPFIT_NAME_COLUMN_LIST_XPATH("//td[@data-name='upfitSpecName']"),
	ORDERING_BO_UPFIT_SPEC_MAINTENANCE_PAGE_TITLE_NAME_XPATH("//div[contains(text(),'Upfit Spec Maintenance')]"),
	ORDERING_BO_UPFIT_SPEC_MAINTENANCE_PAGE_UPFIT_NAME_XPATH("//label[contains(text(),'Upfit Spec Name:')]//following::span[1]//span"),
	ORDERING_BO_QUOTE_CORE_SECTION_VALUES_XPATH("//div[@class='section coreSection']//label[text()='%s']/..//span"),
	ORDERING_BO_PROJECT_FILTER_BUTTON_CLASS("filterControls"),
	ORDERING_BO_PROJECT_FILTER_BUTTON_PROJECT_NAME_XPATH("//a[contains(text(),'Project Name')]"),
	ORDERING_BO_PROJECT_FILTER_BUTTON_PROJECT_NAME_SEARCH_ID("projectName-txtselectAllColumn"),
	ORDERING_BO_PROJECT_FILTER_BUTTON_PROJECT_NAME_APPLY_XPATH("//button[contains(text(),'Apply')]"),
	ORDERING_BO_PROJECT_FILTER_BUTTON_PROJECT_EXPORT_XPATH("//a[@class='exportExcelBtn pull-right']"),
	ORDERING_BO_PROJECT_FILTER_PROJECT_ADD_REMOVE_XPATH("//a[@class='addRemoveBtn pull-right']"),
	ORDERING_BO_PROJECT_FILTER_PROJECT_ADD_REMOVE_CLEAR_ALL_XPATH("//label[@for='selectAllColumn']"),
	ORDERING_BO_PROJECT_FILTER_PROJECT_ADD_REMOVE_CLEAR_ALL_CLOSE_BUTTON_CLASS("closeBtn"),
	ORDERING_BO_PROJECT_FILTER_PROJECT_ADD_REMOVE_COLUMN_LIST_XPATH("//label[@class='spnOptions']"),
	ORDERING_BO_PROJECT_FILTER_PROJECT_ADD_REMOVE_COLUMN_LAST_COLUMN_XPATH("//th[@data-name='rfqStatusEvent'][contains(text(),'RFQ')]"),
	ORDERING_BO_PROJECT_FILTER_PROJECT_HEADER_COLUMN_LIST_XPATH("//div[@class='dataTables_scrollHeadInner']//th"),
	ORDERING_BO_PROJECT_FILTER_PROJECT_SAVE_BUTTON_XPATH("//a[@class='saveBtn pull-right']"),
	ORDERING_BO_PROJECT_FILTER_PROJECT_SAVE_SAVEAS_OPTION_ID("popSaveAs"),
	ORDERING_BO_PROJECT_FILTER_PROJECT_SAVE_SAVEAS_NAME_ID("popInput"),
	ORDERING_BO_PROJECT_FILTER_PROJECT_SAVE_SAVEAS_SAVE_BUTTON_CLASS("btnSaveAsOk"),
	ORDERING_BO_PROJECT_FILTER_PROJECT_SAVE_SAVE_OPTION_ID("popSave"),
	ORDERING_BO_PROJECT_FILTER_PROJECT_SAVE_SAVE_OPTION_OK_CLASS("btnSaveOk"),
	ORDERING_BO_PROJECT_FILTER_PROJECT_SAVE_SAVE_OPTION_CANCEL_XPATH("//button[@class='btnSaveOk']//following::button[1]"),
	ORDERING_BO_PROJECT_FILTER_PROJECT_SELECT_VIEWS_ID("btnDropdownViews"),
	ORDERING_BO_PROJECT_FILTER_PROJECT_SAVE_PROJECT_POP_UP_XPATH("//div[contains(text(),'Standard View can not be saved')]"),
	ORDERING_BO_PROJECT_QUOTEID_XPATH("(//table[@id='queue-table'])[2]/tbody/tr/td[@data-name='quoteId']"),
	ORDERING_BO_PROJECT_QUOTE_SHIPTOSEARCH_XPATH("//input[@name='ship-to-search']"),
	ORDERING_BO_PROJECT_QUOTE_SELECT_FIRST_SHIPTOSEARCH_XPATH("//div[@class='tt-dataset tt-dataset-ship-toSearch']//div[1]"),
	ORDERING_BO_PROJECT_TABLE_COLUMN_NAMES_XPATH("//div[@id='queue-table_wrapper']//div[@class='dataTables_scrollHeadInner']//th"),
	ORDERING_BO_PROJECT_QUEUE_PAGE_PAGINATION_NAME("queue-table_length"),
	ORDERING_BO_PROJECTQ_FLEETSPEC_SEARCHBY_XPATH("//select[@id='fleet-spec-search-by']"),
	ORDERING_BO_PROJECTQ_FLEETSPEC_MANAGEGROUPS_XPATH("//div[@id='manageGroup']"),
	ORDERING_BO_PROJECTQ_FLEETSPEC_MANAGEGROUPSYES_XPATH("//button[@id='confirm-submit']"),
	ORDERING_BO_PROJECTQ_FLEETSPEC_STATUS_XPATH("//span[@id='upfitStatuslbl']"),
	ORDERING_BO_PROJECTQ_FLEETSPEC_ID_XPATH("//h4[contains(text(),'Upfit Spec is attached to the following Fleet Specs')]//following-sibling::div/child::div[2]/span"),
	ORDERING_BO_PROJECTQ_FLEETSPEC_DETACH_XPATH("//div[@id='detachFleet']"),
	ORDERING_BO_PROJECTQ_FLEETSPEC_DETACH_SELECTRDIO_XPATH("//input[@name='fleetSpec']"),
	ORDERING_BO_PROJECTQ_FLEETSPEC_DETACH_SAVE_XPATH("//div[@id='saveFleetSpecDetach']"),
	ORDERING_BO_PROJECTQ_FLEETSPEC_SAVE_XPATH("//div[@id='saveUpfit']"),
	ORDERING_BO_PROJECTQ_FLEETSPEC_MANAGEGRP_ACTIONADD_XPATH("//a[@class='addGroup']/i"),
	ORDERING_BO_PROJECTQ_FLEETSPEC_MANAGEGRP_GRPNAME_XPATH("//input[contains(@value,'Category')]"),
	ORDERING_BO_PROJECTQ_FLEETSPEC_MANAGEGRP_SELECTRULE_XPATH("//select[contains(@id,'upfitSpecItemGroupType0')]"),
	ORDERING_BO_PROJECTQ_FLEETSPEC_MANAGEGRP_SELECTGROUP_XPATH("//select[contains(@id,'group')]"),
	ORDERING_BO_PROJECTQ_FLEETSPEC_GROUPLABEL_XPATH("//span[contains(@id,'groupLabel')]"),
	ORDERING_BO_PROJECTQ_FLEETSPEC_ADDLINEITEM_XPATH("//div[@id='standard-line-item-section']//div[@id='add-item']"),
	ORDERING_BO_PROJECTQ_FLEETSPEC_ADDLINEITEM_PARTNUMBER_XPATH("(//div[@id='standard-line-item-section']//div//input[@id='part-number'])[2]"),
	ORDERING_BO_PROJECTQ_FLEETSPEC_ADDLINEITEM_CATEGORY_XPATH("(//div[@id='standard-line-item-section']//div//select)[2]"),
	ORDERING_BO_PROJECTQ_FLEETSPEC_ADDLINEITEM_PARTNAME_XPATH("(//div[@id='standard-line-item-section']//div//input[@id='part-name'])[2]"),
	ORDERING_BO_PROJECTQ_FLEETSPEC_ADDLINEITEM_EXTDESC_XPATH("(//div[@id='standard-line-item-section']//div//textarea[@id='extended-description'])[2]"),
	ORDERING_BO_PROJECTQ_FLEETSPEC_ADDLINEITEM_PRICE_XPATH("(//div[@id='standard-line-item-section']//div//input[@id='price'])[2]"),
	ORDERING_BO_PROJECTQ_FLEETSPEC_SAVEUPFITSPEC_XPATH("//div[@id='saveUpfit']"),
	ORDERING_BO_PROJECTQ_UPFITSPEC_STATUS_XPATH("//span[@id='upfitStatuslbl']"),	
    ;
	
	private String value;

	OrderingBOOnOrderProjectPageEnum(String value) {
		this.value = value;
	}

	public String getValue() {
		return value;
	}

	@Override
	public String toString() {
		return value;
	}

}
