package com.element.fleet.ordering.enums;

public enum OrderingBOBusinessMaintainedTablesEnum {

	ORDERING_BO_BMT_UPLOAD_FILES_TABLE_CLASS("full-menu"),
	ORDERING_BO_BMT_HEADING_XPATH("//div[@id='queues']//h1[@id='queue-page-title']"),
	ORDERING_BO_BMT_HEADING_Expected("Business Maintained Tables"),
	ORDERING_BO_BMT_ADDITIONAL_OPTIONS_OPTION_XPATH("//div[@class='full-menu']//div[@data-target='AOAQ']"),
	ORDERING_BO_BMT_ASSET_CODE_OPTION_XPATH("//div[@class='full-menu']//div[@data-target='ACAQ']"),
	ORDERING_BO_BMT_DEALER_INSTALLED_OPTIONS_OPTION_XPATH("//div[@class='full-menu']//div[@data-target='DIAQ']"),
	ORDERING_BO_BMT_ELEMENT_FINFAN_CODES_OPTION_XPATH("//div[@class='full-menu']//div[@data-target='EFAQ']"),
	ORDERING_BO_BMT_EMISSIONS_OPTION_XPATH("//div[@class='full-menu']//div[@data-target='EIMQ']"),
	ORDERING_BO_BMT_FACTORY_ORDER_RANGE_OPTION_XPATH("//div[@class='full-menu']//div[@data-target='FOAQ']"),
	ORDERING_BO_BMT_FINFAN_OPTION_XPATH("//div[@class='full-menu']//div[@data-target='FFAQ']"),
	ORDERING_BO_BMT_FLEET_ASSIGNMNET_OPTION_XPATH("//div[@class='full-menu']//div[@data-target='FAAQ']"),
	ORDERING_BO_BMT_HARD_CODED_INSTRUCTION_OPTION_XPATH("//div[@class='full-menu']//div[@data-target='HCIQ']"),
	ORDERING_BO_BMT_INCENTIVES_OPTION_XPATH("//div[@class='full-menu']//div[@data-target='INAQ']"),
	ORDERING_BO_BMT_MASTER_PURCHASE_ORDER_STATUS_OPTION_XPATH("//div[@class='full-menu']//div[@data-target='PSAQ']"),
	ORDERING_BO_BMT_PRICE_PROTECTION_OPTION_XPATH("//div[@class='full-menu']//div[@data-target='PPAQ']"),
	ORDERING_BO_BMT_SCHEDULER_OPTION_XPATH("//div[@class='full-menu']//div[@data-target='SCEQ']"),
	ORDERING_BO_BMT_SWEEPER_RESULTS_OPTION_XPATH("//div[@class='full-menu']//div[@data-target='SRAQ']"),
	ORDERING_BO_BMT_STATUS_TRACKER_SETTING_OPTION_XPATH("//div[@data-target='statusTrackerSettings']//div[@class='title']"),
	ORDERING_BO_BMT_TRANSPORTERS_OPTION_XPATH("//div[@class='full-menu']//div[@data-target='OSAQ']"),
	ORDERING_BO_BMT_UPFITTER_PREFERENCES_OPTION_XPATH("//div[@class='full-menu']//div[@data-target='UPFPQ']"),
	ORDERING_BO_BMT_YEAR_MAKE_MODEL_OPTION_XPATH("//div[@class='full-menu']//div[@data-target='YMMACQ']"),
	ORDERING_BO_BMT_CAPPING_RULES_XPATH("//div[@data-target='cappingRules']//div"),
	ORDERING_BO_BMT_YEAR_MAKE_MODEL_OPTION_EXPECTED(" Year Make Model "),
	ORDERING_BO_BMT_FEATURE_TOGGLE_OPTION_XPATH("//div[@class='full-menu']//div[@data-target='FTAQ']"),
	ORDERING_BO_BMT_ORDER_HOLD_OPTION_XPATH("//div[@class='full-menu']//div[@data-target='ODHQ']"),
	ORDERING_BO_BMT_AO_HEADING_XPATH("//div[@id='queues']//h1[@id='queue-page-title']"),
	ORDERING_BO_BMT_AO_SEARCH_FIELD_ID("standard"),
	ORDERING_BO_BMT_FILTER_SEARCH_FIELD_XPATH("//div[@id='search-filters']"),
	ORDERING_BO_BMT_EDIT_BMT_PAGE_SECTION_ID("main-section"),
	ORDERING_BO_BMT_EDIT_BMT_PAGE_HEADING_CSS("div.subscreen-title"),
	ORDERING_BO_BMT_EDIT_BMT_PRICE_PROTECTION_HEADING_XPATH("//div[@id='price-protection']//h1[contains(text(),'Price Protection')]"),
	ORDERING_BO_BMT_EDIT_BMT_PAGE_ENTITY_ID("entity-ui"),
	ORDERING_BO_BMT_EDIT_BMT_PAGE_SAVE_BUTTON_ID("save-entity"),
	ORDERING_BO_BMT_EDIT_BMT_PRICE_PROTECTION_PAGE_SAVE_BUTTON_ID("save-relationship"),
	ORDERING_BO_BMT_EDIT_BMT_PAGE_ADD_BUTTON_ID("add-entity"),
	ORDERING_BO_BMT_EDIT_BMT_PAGE_DELETE_BUTTON_ID("delete-entity"),
	ORDERING_BO_BMT_EDIT_BMT_PRICE_PROTECTION_PAGE_DELETE_BUTTON_ID("delete-relationship"),
	ORDERING_BO_BMT_EDIT_BMT_PRICE_PROTECTION_PAGE_CANCEL_BUTTON_ID("cancel-relationship"),
	ORDERING_BO_BMT_EDIT_BMT_PAGE_BACK_TO_QUEUE_VIEW_LINK_ID("browser-back"),
	ORDERING_BO_BMT_EDIT_BMT_PAGE_BACK_TO_PRICE_PROTECTION_QUEUE_VIEW_LINK_XPATH("//div[@id='breadcrumbs']//a[@class='breadcrumbs__link js-breadcrumb-link']"),
	ORDERING_BO_BMT_ADDOPTIONS_SUBTITLEEXPECTED("Additional Options"),
	ORDERING_BO_BMT_ADDOPTIONS_SUBSCREENSUBTITLEEXPECTED("Additional Option Maintenance"),
	ORDERING_BO_BMT_COMMON_SEARCHBTN_XPATH("//div[@data-target='search']"),
	ORDERING_BO_BMT_COMMON_CLEARFILTERBTN_XPATH("//div[@data-target='clear']"),
	ORDERING_BO_BMT_COMMON_ADDNEWENTRYBTN_XPATH("//span[contains(text(),'Add New')]"),
	ORDERING_BO_BMT_COMMON_EXPORTBTN_XPATH("//span[contains(text(),'Export')]"),
	ORDERING_BO_BMT_COMMON_TOGGLECOLUMNDROPDOWN_XPATH("//span[contains(text(),'Toggle Columns')]"),
	ORDERING_BO_BMT_COMMON_SIGNOUTBTN_XPATH("//input[@value='Sign Out']"),
	ORDERING_BO_BMT_COMMON_SUBSCREENSUBTITLE_XPATH("//div[@class='subscreen-title']"),
	ORDERING_BO_BMT_COMMON_PROCESS_NAME_XPATH("//input[@name='codeTypeValue']"),
	ORDERING_BO_BMT_COMMON_STATUS_XPATH("//td[@data-name='activeIndicator']"),
	ORDERING_BO_BMT_COMMON_CHECKBOX_NAME("order-check"),
	ORDERING_BO_BMT_COMMON_RELEASE_XPATH("//span[contains(text(),'Release')]"),
	ORDERING_BO_BMT_RELEASE_BUTTON_DISABLED_CSS("div.btn.green.btn-shared.releaseOrder.disabled"),
	ORDERING_BO_BMT_COMMON_HOLD_XPATH("//span[contains(text(),'Hold')]"),
	ORDERING_BO_BMT_HOLD_BUTTON_DISABLED_CSS("div.btn.green.btn-shared.holdOrder.disabled"),
	ORDERING_BO_BMT_UPFITTER_PREF_UPFITTERCODE_XPATH("//input[@name='upfitterCode']"),
	ORDERING_BO_BMT_UPFITTER_PREF_COMMUNICATION_XPATH("//input[@name='codeDescription']"),
	ORDERING_BO_BMT_UPFITTER_PREF_COMMUNICATION_PREF_CSS("select#communicationPreference0"),
	ORDERING_BO_BMT_NOTIFICATION_POPUP_CSS("div.noty-msg"),
	ORDERING_BO_BMT_EDIT_BMT_PAGE_CANCEL_BUTTON_ID("cancel-entity"),
	ORDERING_BO_BMT_COMMON_RERUN_BTN_XPATH("//span[contains(text(),'Re-Run')]"),
	ORDERING_BO_BMT_SCHEDULER_PROCESS_STATUS_XPATH("//td//span[contains(text(),'$processName#')]//following::td[@data-name='activeIndicator'][1]//span"),
	ORDERING_BO_BMT_SCHEDULER_PROCESS_NAME_CHECKBOX_XPATH("//td//span[contains(text(),'$processName#')]//preceding::input[1]"),
	ORDERING_BO_BMT_SCHEDULER_HOLD_BUTTON_XPATH("//div[@class='btn custom-action green btn-shared holdOrder']//span"),
	ORDERING_BO_BMT_SCHEDULER_RELEASE_BUTTON_XPATH("//div[@class='btn custom-action green btn-shared releaseOrder']//span"),
	ORDERING_BO_BMT_SCHEDULER_SEARCH_WITH_XPATH("//label[contains(text(),'$searchBy#')]//preceding::input[1]"),
	ORDERING_BO_BMT_SCHEDULER_SEARCH_BUTTON_XPATH("//span[@class='fa fa-search']//following::span[1]"),
	ORDERING_BO_BMT_SCHEDULER_PROCESS_NAME_LINK_XPATH("//td[@data-val='$processName#']//span"),
	ORDERING_BO_BMT_SCHEDULER_CRON_EXPRESSION_ID("cronScheduleExpression"),
	ORDERING_BO_BMT_SCHEDULER_ENDPONT_ID("endpoint"),
	ORDERING_BO_BMT_SCHEDULER_SAVE_ID("save-entity"),
	ORDERING_BO_BMT_SCHEDULER_CANCEL_ID("cancel-entity"),
	ORDERING_BO_BMT_SCHEDULER_TITLE_XPATH("//div[@id='queues']//h1[2]"),
	ORDERING_BO_BMT_ADTNL_OPTN_CORP_CODE_DRP_DWN_XPATH("//select[@id='corpCode']"),
	ORDERING_BO_BMT_ADTNL_OPTN_FLEET_INPUT_XPATH("//input[@id='clientNumber']"),
	ORDERING_BO_BMT_ADTNL_OPTN_FLEET_SPAN_XPATH("//span[@id='clientNumber']"),
	ORDERING_BO_BMT_ADTNL_OPTN_OPTN_CODE_INPUT_XPATH("//input[@id='code']"),
	ORDERING_BO_BMT_ADTNL_OPTN_OPTN_DESC_INPUT_XPATH("//input[@id='shortDesc']"),
	ORDERING_BO_BMT_ADTNL_OPTN_OPTN_PRICE_INPUT_XPATH("//input[@id='invoicePriceAmount']"),
	ORDERING_BO_BMT_ADTNL_OPTN_EST_ACT_PRICE_SELECT_XPATH("//select[@id='invoicePriceIndicator']"),
	ORDERING_BO_BMT_ADTNL_OPTN_EC_CODE_SELECT_XPATH("//select[@id='equipCategoryCode']"),
	ORDERING_BO_BMT_ADTNL_OPTN_CORP_CODE_SEARCH_INPUT_XPATH("//input[@name='corpCode']"),
	ORDERING_BO_BMT_ADTNL_OPTN_FLEET_SEARCH_INPUT_XPATH("//input[@name='clientNumber']"),
	ORDERING_BO_BMT_ADTNL_OPTN_OPTION_CODE_SEARCH_INPUT_XPATH("//input[@name='code']"),
	ORDERING_BO_BMT_ADTNL_OPTN__PRICE_IND_TABLE_VALUE_XPATH("//td[@data-name='optionInvoicePriceIndicator']"),
	ORDERING_BO_BMT_ADTNL_OPTN_OPTN_CODE_SPAN_XPATH("//span[@id='code']"),
	ORDERING_BO_BMT_ADTNL_OPTN_OPTN_DESC_SPAN_XPATH("//span[@id='shortDesc']"),
	ORDERING_BO_BMT_DELETE_OK_MODAL_XPATH("//button[contains(@class,'button--primary')]"),
	ORDERING_BO_BMT_PRICE_PROTECTION_DELETE_OK_MODAL_XPATH("//button[@class='modal-ok-btn']"),
	ORDERING_BO_BMT_NO_MODAL_XPATH("//button[contains(@class,'button--secondary')]"),
	ORDERING_BO_BMT_ASSET_CODE_ASSET_CODE_INPUT_XPATH("//input[@id='assetCode']"),
	ORDERING_BO_BMT_ASSET_CODE_DESC_INPUT_XPATH("//input[@id='assetCodeDesc']"),
	ORDERING_BO_BMT_ASSET_CODE_PRODUCT_CLASS_DROPDOWN_XPATH("//select[@id='productClassValueId']"),
	ORDERING_BO_BMT_ASSET_CODE_ASSET_CODE_SPAN_XPATH("//span[@id='assetCode']"),
	ORDERING_BO_BMT_ASSET_CODE_SEARCH_INPUT_XPATH("//input[@name='assetCode']"),
	ORDERING_BO_BMT_ASSET_CODE_DESCRIPTION_SEARCH_INPUT_XPATH("//input[@name='assetCodeDescription']"),
	ORDERING_BO_BMT_ASSET_CODE_PRODUCT_CLASS_SEARCH_INPUT_XPATH("//input[@name='productClassCode']"),
	ORDERING_BO_BMT_ASSET_CODE_PRODUCT_CLASS_TABLE_VALUE_XPATH("//td[@data-name='productClassCode']/span"),
	ORDERING_BO_BMT_DIO_OPTION_CODE_INPUT_XPATH("//input[@id='optionCode']"),
	ORDERING_BO_BMT_DIO_OPTION_DESC_INPUT_XPATH("//input[@id='optionShortDesc']"),
	ORDERING_BO_BMT_DIO_BRAND_PROVIDER_INPUT_XPATH("//input[@id='supplierName']"),
	ORDERING_BO_BMT_DIO_EC_CODE_INPUT_XPATH("//select[@id='equipCtgyId']"),
	ORDERING_BO_BMT_DIO_MAX_PRICE_INPUT_XPATH("//input[@id='maxPriceAmount']"),
	ORDERING_BO_BMT_DIO_OPTION_CODE_SEARCH_XPATH("//input[@name='optionCode']"),
	ORDERING_BO_BMT_DIO_OPTION_CODE_DESC_SEARCH_XPATH("//input[@name='optionDescription']"),
	ORDERING_BO_BMT_DIO_BRAND_PROVIDER_SEARCH_XPATH("//input[@name='providerName']"),
	ORDERING_BO_BMT_DIO_BRAND_PROVIDER_TABLE_VALUE_XPATH("//td[@data-name='providerName']/span"),
	ORDERING_BO_BMT_ELEMENT_FINFAN_CORP_CODE_DROPDOWN_XPATH("//select[@id='corpCode']"),
	ORDERING_BO_BMT_ELEMENT_FINFAN_FLEET_INPUT_XPATH("//input[@id='clientNumber']"),
	ORDERING_BO_BMT_ELEMENT_FINFAN_MANUFACTURER_DROPDOWN_XPATH("//select[@id='manufacturer']"),
	ORDERING_BO_BMT_ELEMENT_FINFAN_MAKE_DROPDOWN_XPATH("//select[@id='make']"),
	ORDERING_BO_BMT_ELEMENT_BMT_FINFAN_INPUT_XPATH("//input[@id='finFanVal']"),
	ORDERING_BO_BMT_ELEMENT_FINFAN_INPUT_XPATH("//input[@id='finFanCode']"),
	ORDERING_BO_BMT_ELEMENT_FINFAN_RENTAL_INDICATOR_TOGGLE_XPATH("//input[@id='rentalIndicator']//ancestor::div[@class='toggle-switch']"),
	ORDERING_BO_BMT_ELEMENT_FINFAN_CORP_CODE_SEARCH_XPATH("//input[@name='corpCode']"),
	ORDERING_BO_BMT_ELEMENT_FINFAN_MANUFACTURER_SEARCH_XPATH("//input[@name='manufacturer']"),
	ORDERING_BO_BMT_ELEMENT_FINFAN_SEARCH_XPATH("//input[@name='finFan']"),
	ORDERING_BO_BMT_ELEMENT_FINFAN_RENTAL_INDICATOR_TABLE_VAL_XPATH("//td[@data-name='rentalIndicator']/span"),
	ORDERING_BO_BMT_EMISION_CORP_CODE_DROPDOWN_XPATH("//select[@id='corp']"),
	ORDERING_BO_BMT_EMISION_YEAR_DROPDOWN_XPATH("//select[@id='year']"),
	ORDERING_BO_BMT_EMISION_MANUFACTURER_DROPDOWN_XPATH("//select[@id='manufacturer']"),
	ORDERING_BO_BMT_EMISION_MAKE_DROPDOWN_XPATH("//select[@id='make']"),
	ORDERING_BO_BMT_EMISION_MODEL_DROPDOWN_XPATH("//select[@id='model']"),
	ORDERING_BO_BMT_EMISION_TRIM_DROPDOWN_XPATH("//select[@id='trim']"),
	ORDERING_BO_BMT_EMISION_CODE_INPUT_XPATH("//input[@id='emissionCode']"),
	ORDERING_BO_BMT_EMISION_REIGON_DROPDOWN_XPATH("//select[@id='emissionRegionId']"),
	ORDERING_BO_BMT_EMISION_CORP_SEARCH_XPATH("//input[@name='corpCd']"),
	ORDERING_BO_BMT_EMISION_YEAR_SEARCH_XPATH("//input[@name='ymmYear']"),
	ORDERING_BO_BMT_EMISION_MANUFACTURER_SEARCH_XPATH("//input[@name='manufacturer']"),
	ORDERING_BO_BMT_EMISION_MODEL_SEARCH_XPATH("//input[@name='model']"),
	ORDERING_BO_BMT_EMISION_MAKE_SEARCH_XPATH("//input[@name='make']"),
	ORDERING_BO_BMT_EMISION_CODE_TABLE_VAL_XPATH("//td[@data-name='emCode']/span"),
	ORDERING_BO_BMT_FACTORY_ORDER_RANGE_CORP_DROPDOWN_XPATH("//select[@id='corpCode']"),
	ORDERING_BO_BMT_FACTORY_ORDER_RANGE_MODEL_CODE_DROPDOWN_XPATH("//select[@id='mfgCode']"),
	ORDERING_BO_BMT_FACTORY_ORDER_RANGE_START_NUMBER_INPUT_XPATH("//input[@id='rangeStartNumber']"),
	ORDERING_BO_BMT_FACTORY_ORDER_RANGE_MODEL_CODE_INPUT_XPATH("//input[@name='modelCode']"),
	ORDERING_BO_BMT_FACTORY_ORDER_RANGE_START_NUMBER_TABLE_VALUE_XPATH("//td[@data-name='startNumber']/span"),
	ORDERING_BO_BMT_FEATURE_TOGGLE_FEATURE_NAME_INPUT_XPATH("//input[@id='featureName']"),
	ORDERING_BO_BMT_FEATURE_TOGGLE_FEATURE_DESCRIPTION_INPUT_XPATH("//input[@id='featureDescription']"),
	ORDERING_BO_BMT_FEATURE_TOGGLE_FEATURE_TYPE_SELECT_XPATH("//select[@id='featureTypeCode']"),
	ORDERING_BO_BMT_FEATURE_TOGGLE_FEATURE_VALUE_INPUT_XPATH("//input[@id='featureValue']"),
	ORDERING_BO_BMT_FEATURE_TOGGLE_PARENT_GROUP_XPATH("//select[@id='parentFeatureId']"),
	ORDERING_BO_BMT_FEATURE_TOGGLE_FEATURE_NAME_LIST_XPATH("//td[@data-name='featureName']/span"),
	ORDERING_BO_BMT_FLEET_ASSIGNMENT_CORP_CODE_DROPDOWN_XPATH("//select[@id='corpCode']"),
	ORDERING_BO_BMT_FLEET_ASSIGNMENT_FLEET_INPUT_XPATH("//input[@id='clientNumber']"),
	ORDERING_BO_BMT_FLEET_ASSIGNMENT_ROLE_ID_XPATH("//select[@id='roleId']"),
	ORDERING_BO_BMT_FLEET_ASSIGNMENT_PRIMARYID_INPUT_XPATH("//input[@id='pseudo-primaryId']"),
	ORDERING_BO_BMT_FLEET_ASSIGNMENT_PRIMARYID_OPTION_LIST_XPATH("//div[@class='field-wrapper']//input[@id='pseudo-primaryId']//following-sibling::datalist//option"),
	ORDERING_BO_BMT_FLEET_ASSIGNMENT_CORP_CODE_SEARCH_XPATH("//input[@name='corpCode']"),
	ORDERING_BO_BMT_FLEET_ASSIGNMENT_CLIENT_NUMBER_SEARCH_XPATH("//input[@name='clientNumber']"),
	ORDERING_BO_BMT_FLEET_ASSIGNMENT_ROLE_NAME_SEARCH_XPATH("//input[@name='roleName']"),
	ORDERING_BO_BMT_FLEET_ASSIGNMENT_PRIMARY_USER_SEARCH_XPATH("//input[@name='primaryUser']"),
	ORDERING_BO_BMT_FLEET_ASSIGNMENT_FLEET_SPAN_XPATH("//span[@id='clientNumber']"),
	ORDERING_BO_BMT_FLEET_ASSIGNMENT_PRIMARY_USER_TABLE_VAL_XPATH("//td[@data-name='primaryUserId']/span"),
	ORDERING_BO_BMT_INCENTIVE_ID_INPUT_XPATH("//input[@id='code']"),
	ORDERING_BO_BMT_INCENTIVE_ID_SPAN_XPATH("//span[@id='code']"),
	ORDERING_BO_BMT_INCENTIVE_DESCRIPTION_INPUT_XPATH("//input[@id='description']"),
	ORDERING_BO_BMT_INCENTIVE_DESCRIPTION_TABLE_VAL_XPATH("//td[@data-name='description']/span"),
	ORDERING_BO_BMT_INCENTIVE_CORP_CODE_SEARCH_XPATH("//input[@name='corpCode']"),
	ORDERING_BO_BMT_INCENTIVE_FLEET_SEARCH_XPATH("//input[@name='clientNumber']"),
	ORDERING_BO_BMT_INCENTIVE_YEAR_SEARCH_XPATH("//input[@name='year']"),
	ORDERING_BO_BMT_INCENTIVE_MANUFACTURER_SEARCH_XPATH("//input[@name='make']"),
	ORDERING_BO_BMT_INCENTIVE_CODE_SEARCH_XPATH("//input[@name='code']"),
	ORDERING_BO_BMT_MPO_MANUFACTURER_DROPDOWN_XPATH("//select[@id='manufacturer']"),
	ORDERING_BO_BMT_MPO_MAKE_DROPDOWN_XPATH("//select[@id='make']"),
	ORDERING_BO_BMT_MPO_MAJOR_CODE_DROPDOWN_XPATH("//select[@id='majorCode']"),
	ORDERING_BO_BMT_MPO_DESC_INPUT_XPATH("//input[@id='description']"),
	ORDERING_BO_BMT_MPO_MANUFACTURER_SEARCH_XPATH("//input[@name='manufacturer']"),
	ORDERING_BO_BMT_MPO_MAJOR_CODE_SEARCH_XPATH("//input[@name='majorCode']"),
	ORDERING_BO_BMT_MPO_DESCRIPTION_SEARCH_XPATH("//input[@name='description']"),
	ORDERING_BO_BMT_MPO_MAKE_SEARCH_XPATH("//input[@name='make']"),
	ORDERING_BO_BMT_MPO_DESCRIPTION_TABLE_VAL_XPATH("//td[@data-name='description']/span"),
	ORDERING_BO_BMT_ORDER_HOLD_YEAR_DROPDOWN_XPATH("//select[@id='year']"),
	ORDERING_BO_BMT_ORDER_HOLD_MANUFACTURER_DROPDOWN_XPATH("//select[@id='manufacturer']"),
	ORDERING_BO_BMT_ORDER_HOLD_MAKE_DROPDOWN_XPATH("//select[@id='make']"),
	ORDERING_BO_BMT_ORDER_HOLD_MODEL_DROPDOWN_XPATH("//select[@id='model']"),
	ORDERING_BO_BMT_ORDER_HOLD_CORP_SEARCH_XPATH("//input[@name='corpCode']"),
	ORDERING_BO_BMT_ORDER_HOLD_YEAR_SEARCH_XPATH("//input[@name='year']"),
	ORDERING_BO_BMT_ORDER_HOLD_MANUFACTURER_SEARCH_XPATH("//input[@name='manufacturer']"),
	ORDERING_BO_BMT_ORDER_HOLD_MAKE_SEARCH_XPATH("//input[@name='make']"),
	ORDERING_BO_BMT_ORDER_HOLD_MODEL_SEARCH_XPATH("//input[@name='model']"),
	ORDERING_BO_BMT_ORDER_HOLD_MODEL_TABLE_VAL_XPATH("//td[@data-name='model']/span"),
	ORDERING_BO_BMT_PRICE_PROTECTION_CORP_CODE_DROPDOWN_XPATH("//select[@id='corp-code']"),
	ORDERING_BO_BMT_PRICE_PROTECTION_CLIENT_NUMBER_INPUT_XPATH("//input[@id='search-client']"),
	ORDERING_BO_BMT_PRICE_PROTECTION_CLIENT_NUMBER_SUGGESTION_XPATH("(//div[@class='tt-suggestion tt-selectable empty client-color'])[1]"),
	ORDERING_BO_BMT_PRICE_PROTECTION_YEAR_DROPDOWN_XPATH("//select[@id='year']"),
	ORDERING_BO_BMT_PRICE_PROTECTION_MANUFACTURER_DROPDOWN_XPATH("//select[@id='manufacturer']"),
	ORDERING_BO_BMT_PRICE_PROTECTION_MAKE_DROPDOWN_XPATH("//select[@id='make']"),
	ORDERING_BO_BMT_PRICE_PROTECTION_MODEL_DROPDOWN_XPATH("//select[@id='model']"),
	ORDERING_BO_BMT_PRICE_PROTECTION_TRIM_DROPDOWN_XPATH("//select[@id='trim']"),
	ORDERING_BO_BMT_PRICE_PROTECTION_PRICING_MSRP_CHECKBOX_XPATH("//input[@id='msrp']"),
	ORDERING_BO_BMT_PRICE_PROTECTION_PRICING_INVOICE_CHECKBOX_XPATH("//input[@id='invoice']"),
	ORDERING_BO_BMT_PRICE_PROTECTION_CORP_SEARCH_XPATH("//input[@name='corpCode']"),
	ORDERING_BO_BMT_PRICE_PROTECTION_FLEET_SEARCH_XPATH("//input[@name='clientNumber']"),
	ORDERING_BO_BMT_PRICE_PROTECTION_YEAR_SEARCH_XPATH("//input[@name='year']"),
	ORDERING_BO_BMT_PRICE_PROTECTION_MAKE_SEARCH_XPATH("//input[@name='make']"),
	ORDERING_BO_BMT_PRICE_PROTECTION_MODEL_SEARCH_XPATH("//input[@name='model']"),
	ORDERING_BO_BMT_PRICE_PROTECTION_PRICING_SCHEME_TABLE_VAL_XPATH("//td[@data-name='pricingScheme']/span"),
	ORDERING_BO_BMT_PRICE_PROTECTION_DELETE_BTN_XPATH("//div[@id='delete-relationship']"),
	ORDERING_BO_BMT_PRICE_PROTECTION_SAVE_BTN_XPATH("//div[@id='save-relationship']"),
	ORDERING_BO_BMT_PRICE_PROTECTION_BACK_XPATH("//a[@class='breadcrumbs__link js-breadcrumb-link']"),
	ORDERING_BO_BMT_SCHEDULER_RUN_TYPE_DROPDOWN_XPATH("//select[@id='scheduleTypeCode']"),
	ORDERING_BO_BMT_SCHEDULER_PROCESS_NAME_DROPDOWN_XPATH("//select[@id='scheduleCode']"),
	ORDERING_BO_BMT_SCHEDULER_PROCESS_CRON_INPUT_XPATH("//input[@id='cronScheduleExpression']"),
	ORDERING_BO_BMT_SCHEDULER_PROCESS_CRON_INPUT_ID("cronScheduleExpression"),
	ORDERING_BO_BMT_SCHEDULER_PROCESS_REQUEST_TYPE_DROPDOWN_XPATH("//select[@id='requestMethodCode']"),
	ORDERING_BO_BMT_SCHEDULER_PROCESS_NAME_INPUT_XPATH("//input[@name='codeTypeValue']"),
	ORDERING_BO_BMT_SCHEDULER_TYPE_INPUT_XPATH("//input[@name='codeTypeName']"),
	ORDERING_BO_BMT_SCHEDULER_FREQUENCY_TABLE_VAL_XPATH("//td[@data-name='cronScheduleDescription']/span"),
	ORDERING_BO_BMT_DIO_ADD_XPATH("//span[contains(text(),'Add New')]"),
	ORDERING_BO_BMT_DIO_OPTION_CODE_ID("optionCode"),
	ORDERING_BO_BMT_DIO_OPTION_DESC_ID("optionShortDesc"),
	ORDERING_BO_BMT_DIO_OPTION_MAX_PRICE_ID("maxPriceAmount"),
	ORDERING_BO_BMT_DIO_SAVE_BUTTON_ID("save-entity"),
	ORDERING_BO_BMT_DIO_SAVE_NOTIFICATION_XPATH("//div[@id='ui-datepicker-div']"),
	ORDERING_BO_BMT_DIO_OPTIONCODE_XPATH("//input[@id='optionCode']"),
	ORDERING_BO_BMT_DIO_OPTION_DESCRIPTION_XPATH("//input[@id='optionShortDesc']"),
	ORDERING_BO_BMT_DIO_BRAND_PROVIDER_XPATH("//input[@id='supplierName']"),
	ORDERING_BO_BMT_DIO_EXTENDED_DESCRIPTION_XPATH("//input[@id='extendedDescription']"),
	ORDERING_BO_BMT_DIO_MAX_PRICE_XPATH("//input[@id='maxPriceAmount']"),
	ORDERING_BO_BMT_DIO_POST_PROD_IND_XPATH("//div[@id='div-postProductionInd']//div[@class='field-wrapper']//label"),
	ORDERING_BO_BMT_DIO_SUPPLIER_SHIP_XPATH("//div[@id='div-supplierToShipIndicator']//div[@class='field-wrapper']//label"),
	ORDERING_BO_BMT_DIO_SAVE_BUTTON_XPATH("//div[@id='save-entity']"),
	ORDERING_BO_BMT_DIO_BACK_TO_QUEUES_XPATH("//div[@id='browser-back']"),
	ORDERING_BO_BMT_DIO_TABLE_MAXPRICE_XPATH("//td[8]"),
	ORDERING_BO_BMT_DIO_SEARCH_OPTIONCODE_XPATH("//input[@name='optionCode']"),
	ORDERING_BO_BMT_DIO_SEARCH_BUTTON_CLASS("btn green btn-Shape search loading"),
	ORDERING_BO_BMT_DIO_SECTION_FIRST_ROW_XPATH("//tr[@class='odd']"),
	ORDERING_BO_BMT_DIO_SECTION_DELETE_BUTTON_XPATH("//div[@id='delete-entity']"),
	ORDERING_BO_BMT_DIO_SECTION_DELETE_POPUP_YES_BUTTON_XPATH("//button[@class='modal-ok-btn']"),
	ORDERING_BO_BMT_CAPPING_RULE_TITLE_XPATH("//h1[contains(text(),'Capping Rules')]"),
	ORDERING_BO_BMT_CAPPING_SMART_RULE_SUBTITLE_XPATH("//h1[contains(text(),'Capping Rules')]//following::h2[1]"),
	ORDERING_BO_BMT_CAPPING_RULE_SUBTITLE_XPATH("//h1[contains(text(),'Capping Rules')]//following::h2[2]"),
	ORDERING_BO_BMT_CAPPING_RULES_TITLE_XPATH("//h1[@id='queue-page-title']"),
	ORDERING_BO_BMT_CAPPING_RULES_ACTIVE_RULES_XPATH("//a[contains(text(),'Active Rules')]"),
	ORDERING_BO_BMT_CAPPING_RULES_ARCHIVED_RULES_XPATH("//a[contains(text(),'Archived Rules')]"),
	ORDERING_BO_BMT_CAPPING_SMART_RULES_RULE_ID_XPATH("//div[@id='capping-smart-rules-queue']//label[contains(text(),'Rule ID')]"),
	ORDERING_BO_BMT_CAPPING_SMART_RULES_RULE_ID_TEXTFIELD_XPATH("//div[@id='capping-smart-rules-queue']//input[@id='ruleGroupId-input']"),
	ORDERING_BO_BMT_CAPPING_SMART_RULES_RULE_NAME_XPATH("//div[@id='capping-smart-rules-queue']//label[contains(text(),'Rule Name')]"),
	ORDERING_BO_BMT_CAPPING_SMART_RULES_RULE_NAME_TEXTFIELD_XPATH("//div[@id='capping-smart-rules-queue']//input[@id='rule-input']"),
	ORDERING_BO_BMT_CAPPING_SMART_RULES_CORP_CODE_XPATH("//div[@id='capping-smart-rules-queue']//label[contains(text(),'Corp Code')]"),
	ORDERING_BO_BMT_CAPPING_SMART_RULES_CORP_CODE_TEXTFIELD_XPATH("//div[@id='capping-smart-rules-queue']//input[@id='rule-input']"),
	ORDERING_BO_BMT_CAPPING_SMART_RULES_CLIENT_XPATH("//div[@id='capping-smart-rules-queue']//label[contains(text(),'Client')]"),
	ORDERING_BO_BMT_CAPPING_SMART_RULES_CLIENT_TEXTFIELD_XPATH("//div[@id='capping-smart-rules-queue']//input[@id='clientNumber-input']"),	
	ORDERING_BO_BMT_CAPPING_SMART_RULES_BREAKDOWN_XPATH("//div[@id='capping-smart-rules-queue']//label[contains(text(),'Breakdown')]"),
	ORDERING_BO_BMT_CAPPING_SMART_RULES_BREAKDOWN_TEXTFIELD_XPATH("//div[@id='capping-smart-rules-queue']//input[@id='breakdown-input']"),	
	ORDERING_BO_BMT_CAPPING_SMART_RULES_EFFECTIVE_DATE_XPATH("//div[@id='capping-smart-rules-queue']//label[contains(text(),'Effective Date')]"),
	ORDERING_BO_BMT_CAPPING_SMART_RULES_EFFECTIVE_DATE_TEXTFIELD_XPATH("//div[@id='capping-smart-rules-queue']//input[@id='effDateSTARTCSRQ5-input']"),	
	ORDERING_BO_BMT_CAPPING_SMART_RULES_EFFECTIVE_UNTIL_XPATH("//div[@id='capping-smart-rules-queue']//label[contains(text(),'Effective Until')]"),
	ORDERING_BO_BMT_CAPPING_SMART_RULES_EFFECTIVE_UNTIL_TEXTFIELD_XPATH("//div[@id='capping-smart-rules-queue']//input[@id='endDateENDCSRQ6-input']"),	
	ORDERING_BO_BMT_CAPPING_SMART_RULES_CONTRACT_TYPE_XPATH("//div[@id='capping-smart-rules-queue']//label[contains(text(),'Contract Type')]"),
	ORDERING_BO_BMT_CAPPING_SMART_RULES_CONTRACT_TYPE_TEXTFIELD_XPATH("//div[@id='capping-smart-rules-queue']//input[@id='contractType-input']"),
	ORDERING_BO_BMT_CAPPING_SMART_RULES_ORDER_TYPE_XPATH("//div[@id='capping-smart-rules-queue']//label[contains(text(),'Order Type')]"),
	ORDERING_BO_BMT_CAPPING_SMART_RULES_ORDER_TYPE_TEXTFIELD_XPATH("//div[@id='capping-smart-rules-queue']//input[@id='orderType-input']"),
	ORDERING_BO_BMT_CAPPING_SMART_RULES_PRODUCT_CLASS_XPATH("//div[@id='capping-smart-rules-queue']//label[contains(text(),'Product Class')]"),
	ORDERING_BO_BMT_CAPPING_SMART_RULES_PRODUCT_CLASS_TEXTFIELD_XPATH("//div[@id='capping-smart-rules-queue']//input[@id='productClass-input']"),
	ORDERING_BO_BMT_CAPPING_SMART_RULES_YEAR_XPATH("//div[@id='capping-smart-rules-queue']//label[contains(text(),'Year')]"),
	ORDERING_BO_BMT_CAPPING_SMART_RULES_YEAR_TEXTFIELD_XPATH("//div[@id='capping-smart-rules-queue']//input[@id='year-input']"),
	ORDERING_BO_BMT_CAPPING_SMART_RULES_MAKE_XPATH("//div[@id='capping-smart-rules-queue']//label[contains(text(),'Make')]"),
	ORDERING_BO_BMT_CAPPING_SMART_RULES_MAKE_TEXTFIELD_XPATH("//div[@id='capping-smart-rules-queue']//input[@id='make-input']"),
	ORDERING_BO_BMT_CAPPING_SMART_RULES_MODEL_XPATH("//div[@id='capping-smart-rules-queue']//label[contains(text(),'Model')]"),
	ORDERING_BO_BMT_CAPPING_SMART_RULES_MODEL_TEXTFIELD_XPATH("//div[@id='capping-smart-rules-queue']//input[@id='model-input']"),
	ORDERING_BO_BMT_CAPPING_SMART_RULES_STATE_PROVINSE_XPATH("//div[@id='capping-smart-rules-queue']//label[contains(text(),'State/Province')]"),
	ORDERING_BO_BMT_CAPPING_SMART_RULES_STATE_TEXTFIELD_XPATH("//div[@id='capping-smart-rules-queue']//input[@id='stateProvience-input']"),
	ORDERING_BO_BMT_CAPPING_SMART_RULES_VISIBLE_TO_CLIENT_XPATH("//div[@id='capping-smart-rules-queue']//label[contains(text(),'Visible to Client')]"),
	ORDERING_BO_BMT_CAPPING_SMART_RULES_APPLIED_TO_INFLIGHT_ORDERS_XPATH("//div[@id='capping-smart-rules-queue']//label[contains(text(),'Applied to In-Flight Orders')]"),
	ORDERING_BO_BMT_CAPPING_SMART_RULES_CLEAR_FILTER_BUTTON_XPATH("//div[@id='capping-smart-rules-queue']//button[@id='clear-all-filters-btn']"),
	ORDERING_BO_BMT_CAPPING_SMART_RULES_SEARCH_BUTTON_XPATH("//div[@id='capping-smart-rules-queue']//button[@id='search-by-filters-btn']"),
	ORDERING_BO_BMT_CAPPING_SMART_RULES_BULK_ACTIONS_BUTTON_XPATH("//div[@id='capping-smart-rules-queue']//label[contains(text(),'Bulk Actions')]"),
	ORDERING_BO_BMT_CAPPING_SMART_RULES_ADD_NEW_BUTTON_XPATH("//button[@id='csr-add-new-button']"),
	ORDERING_BO_BMT_CAPPING_SMART_RULES_EXPORT_BUTTON_XPATH("//div[@id='capping-smart-rules-queue']//button[@id='export-CSV-button']"),
	ORDERING_BO_BMT_CAPPING_SMART_RULES_TABLE_COLUMN_DATA_XPATH("//td[@class='data-table__cell dt-left']"),
	ORDERING_BO_BMT_CAPPING_SMART_RULES_ROWS_CSS("data-table__row"),
	ORDERING_BO_BMT_CAPPING_RULES_RULE_ID_XPATH("//div[@id='capping-rules-queue']//label[contains(text(),'Rule ID')]"),
	ORDERING_BO_BMT_CAPPING_RULES_RULE_NAME_XPATH("//div[@id='capping-rules-queue']//label[contains(text(),'Rule Name')]"),
	ORDERING_BO_BMT_CAPPING_RULES_CORP_CODE_XPATH("//div[@id='capping-rules-queue']//label[contains(text(),'Corp Code')]"),
	ORDERING_BO_BMT_CAPPING_RULES_CLIENT_XPATH("//div[@id='capping-rules-queue']//label[contains(text(),'Client')]"),
	ORDERING_BO_BMT_CAPPING_RULES_BREAKDOWN_XPATH("//div[@id='capping-rules-queue']//label[contains(text(),'Breakdown')]"),
	ORDERING_BO_BMT_CAPPING_RULES_EFFECTIVE_DATE_XPATH("//div[@id='capping-rules-queue']//label[contains(text(),'Effective Date')]"),
	ORDERING_BO_BMT_CAPPING_RULES_EFFECTIVE_UNTIL_XPATH("//div[@id='capping-rules-queue']//label[contains(text(),'Effective Until')]"),
	ORDERING_BO_BMT_CAPPING_RULES_CONTRACT_TYPE_XPATH("//div[@id='capping-rules-queue']//label[contains(text(),'Contract Type')]"),
	ORDERING_BO_BMT_CAPPING_RULES_ORDER_TYPE_XPATH("//div[@id='capping-rules-queue']//label[contains(text(),'Order Type')]"),
	ORDERING_BO_BMT_CAPPING_RULES_PRODUCT_CLASS_XPATH("//div[@id='capping-rules-queue']//label[contains(text(),'Product Class')]"),
	ORDERING_BO_BMT_CAPPING_RULES_YEAR_XPATH("//div[@id='capping-rules-queue']//label[contains(text(),'Year')]"),
	ORDERING_BO_BMT_CAPPING_RULES_MAKE_XPATH("//div[@id='capping-rules-queue']//label[contains(text(),'Make')]"),
	ORDERING_BO_BMT_CAPPING_RULES_MODEL_XPATH("//div[@id='capping-rules-queue']//label[contains(text(),'Model')]"),
	ORDERING_BO_BMT_CAPPING_RULES_STATE_PROVINSE_XPATH("//div[@id='capping-rules-queue']//label[contains(text(),'State/Province')]"),
	ORDERING_BO_BMT_CAPPING_RULES_VISIBLE_TO_CLIENT_XPATH("//div[@id='capping-rules-queue']//label[contains(text(),'Visible to Client')]"),
	ORDERING_BO_BMT_CAPPING_RULES_APPLIED_TO_INFLIGHT_ORDERS_XPATH("//div[@id='capping-rules-queue']//label[contains(text(),'Applied to In-Flight Orders')]"),
	ORDERING_BO_BMT_CAPPING_RULES_CLEAR_FILTER_BUTTON_XPATH("//div[@id='capping-rules-queue']//button[@id='clear-all-filters-btn']"),
	ORDERING_BO_BMT_CAPPING_RULES_SEARCH_BUTTON_XPATH("//div[@id='capping-rules-queue']//button[@id='search-by-filters-btn']"),
	ORDERING_BO_BMT_CAPPING_RULES_BULK_ACTIONS_BUTTON_XPATH("//div[@id='capping-rules-queue']//label[contains(text(),'Bulk Actions')]"),
	ORDERING_BO_BMT_CAPPING_RULES_ADD_NEW_BUTTON_XPATH("//button[@id='add-new-button']"),
	ORDERING_BO_BMT_CAPPING_RULES_EXPORT_BUTTON_XPATH("//div[@id='capping-rules-queue']//button[@id='export-CSV-button']"),
	ORDERING_BO_BMT_CAPPING_RULES_SEARCH_FIELDS_INPUT_XPATH("//div[@id='%s']//label[text()='%s']/following-sibling::input"),
	ORDERING_BO_BMT_CAPPING_RULES_SEARCH_SELECT_XPATH("//div[@id='%s']//label[text()='%s']/following-sibling::select"),
	ORDERING_BO_BMT_CAPPING_RULES_SROLL_XPATH("//div[@id='capping-rules-queue']//div[@id='queue-filters']"),
	ORDERING_BO_BMT_CAPPING_RULES_COLUMN_LIST_XPATH("//div[@id='%s']//td[@data-name='%s']"),
	ORDERING_BO_BMT_CAPPING_RULES_CLEAR_FILTER_XPATH("//div[@id='%s']//button[@id='clear-all-filters-btn']"),
	ORDERING_BO_BMT_CAPPING_RULES_INPUT_FIELDS_LIST_XPATH("//div[@id='%s']//label/following-sibling::input"),
	ORDERING_BO_BMT_CAPPING_RULES_SELECT_LIST_XPATH("//div[@id='%s']//label/following-sibling::select"),
	ORDERING_BO_BMT_CAPPING_RULES_SEARCH_BTN_XPATH("//div[@id='%s']//button[@id='search-by-filters-btn']"),
	ORDERING_BO_BMT_CAPPING_RULES_DEFAULT_VIEW_XPATH("//div[@id='%s']//span[@class='default-view-preference js-default-view-preference']"),
	ORDERING_BO_BMT_CAPPING_RULES_MANAGE_VIEW_XPATH("//div[@id='%s']//li[@data-view-action='Manage View']"),
	ORDERING_BO_BMT_CAPPING_RULES_CREATE_VIEW_RADIO_BTN_XPATH("//input[@id='create-new-view-radio']"),
	ORDERING_BO_BMT_CAPPING_RULES_CREATE_VIEW_SAVE_DEFAULT_BTN_XPATH("//button[@data-action='save-default']"),
	ORDERING_BO_BMT_CAPPING_RULES_CREATE_VIEW_OK_BTN_XPATH("//button[contains(@class,'modal-ok-btn')]"),
	ORDERING_BO_BMT_CAPPING_RULES_MANAGE_VIEW_SELECT_XPATH("//select[@class='current-view-dropdown js-current-view-select-option']"),	
	ORDERING_BO_BMT_CAPPING_RULES_MANAGE_VIEW_DELETE_XPATH("//button[contains(@class,'modal-delete')]"),
	ORDERING_BO_BMT_CAPPING_RULES_CREATE_VIEW_INPUT_XPATH("//input[@id='create-new-view-text-input']"),
	ORDERING_BO_BMT_CAPPING_RULES_ARCHIVE_TAB_XPATH("//a[@data-toggle='tab' and text()='Archived Rules']"),
	ORDERING_BO_BMT_ARCHIVED_CAPPING_RULES_SROLL_XPATH("//div[@id='archive-capping-rules-summary']//div[@id='queue-filters']"),
	ORDERING_BO_BMT_CAPPING_RULES_CHECKBOX_XPATH("//div[@class='checkbox-groups']//label[contains(text(),'%s')]/preceding-sibling::input"),
	ORDERING_BO_BMT_CAPPING_RULES_CHECKBOX_LIST_XPATH("//div[@class='checkbox-groups']//label/preceding-sibling::input"),
	ORDERING_BO_BMT_CAPPING_RULES_CHECKBOX_PARENT_LIST_XPATH("//div[@class='checkbox-groups']"),
	ORDERING_BO_BMT_CAPPING_RULES_VEHICLE_BREAKDOWN_XPATH("//input[@name='vb']"),
	ORDERING_BO_BMT_CAPPING_RULES_DRIVER_BREAKDOWN_XPATH("//input[@name='db']"),
	ORDERING_BO_BMT_CAPPING_RULES_VEHICLE_BREAKDOWN_TITLE_XPATH("//div[@id='bkdSelectorBMTVBD']//h3[contains(text(),'Client & Breakdown Selector')]"),
	ORDERING_BO_BMT_CAPPING_RULES_VEHICLE_BREAKDOWN_COMPANY_INFORMATION_XPATH("//div[@id='bkdSelectorBMTVBD']//a[@title='Company Information']"),
	ORDERING_BO_BMT_CAPPING_RULES_VEHICLE_BREAKDOWN_INFORMATION_XPATH("//div[@id='bkdSelectorBMTVBD']//div[@id='brkdwnAccordion']"),
	ORDERING_BO_BMT_CAPPING_RULES_BREAKDOWN_CLOSE_XPATH("//div[@id='bkdSelectorBMTVBD']//i[@class='fa fa-times close close-selector']"),
	ORDERING_BO_BMT_CAPPING_RULES_DRIVER_BREAKDOWN_TITLE_XPATH("//div[@id='bkdSelectorBMTDBD']//h3[contains(text(),'Client & Breakdown Selector')]"),
	ORDERING_BO_BMT_CAPPING_RULES_DRIVER_BREAKDOWN_COMPANY_INFORMATION_XPATH("//div[@id='bkdSelectorBMTDBD']//a[@title='Company Information']"),
	ORDERING_BO_BMT_CAPPING_RULES_DRIVER_BREAKDOWN_INFORMATION_XPATH("//div[@id='bkdSelectorBMTDBD']//div[@id='brkdwnAccordion']"),
	ORDERING_BO_BMT_CAPPING_RULES_DRIVER_BREAKDOWN_CLOSE_XPATH("//div[@id='bkdSelectorBMTDBD']//i[@class='fa fa-times close close-selector']"),
	ORDERING_BO_BMT_CAPPING_RULE_ADD_RULE_CLOSE_XPATH("//div[@id='cancel-entity']"),
	ORDERING_BO_BMT_CAPPING_RULE_ADD_RULE_SAVE_XPATH("//div[@id='save-entity']"),
	ORDERING_BO_BMT_CAPPING_RULE_FIRST_ROW_CLIENT_XPATH("//div[@id='%s']//td[contains(text(),'%s')]/preceding::i[1]//following::td[@data-name='clientNumber'][1]"),
	ORDERING_BO_BMT_CAPPING_RULE_SECOND_ROW_CLIENT_XPATH("//div[@id='%s']//td[contains(text(),'%s')]/preceding::i[1]//following::td[@data-name='clientNumber'][2]"),
	ORDERING_BO_BMT_CAPPING_RULE_HEADER_LIST_XPATH("//div[@id='%s']//div[@class='dataTables_scrollHead']//th[contains(@class,'data-table__header-cell dt-left sorting')]"),
	ORDERING_BO_BMT_SMART_ADD_NEW_RULE_BUTTON_ID("csr-add-new-button"),
	ORDERING_BO_BMT_ADD_NEW_RULE_BUTTON_ID("add-new-button"),
	ORDERING_BO_BMT_ADD_NEW_RULE_PAGE_TITLE_ID("rule-type-title"),
	ORDERING_BO_BMT_ADD_NEW_RULE_SMART_RULE_CONTAINER_XPATH("//div[@class='container-fluid smartrule-container']//div"),
	ORDERING_BO_BMT_ADD_NEW_RULE_SMART_RULE_XPATH("//label[contains(text(),'$Rule#')]//preceding::input[1]"),
	ORDERING_BO_BMT_ADD_NEW_RULE_TEXT_ID("capping-rule-txt"),
	ORDERING_BO_BMT_ADD_NEW_RULE_START_DATE_ID("start-date"),
	ORDERING_BO_BMT_ADD_NEW_RULE_START_DATE_SYMBOL_XPATH("//button[@data-target-name='start-date']"),
	ORDERING_BO_BMT_ADD_NEW_RULE_START_DATE_CSS("div#ui-datepicker-div[style*='display: block;'] td.ui-datepicker-today > a"),
	ORDERING_BO_BMT_ADD_NEW_RULE_START_DATE_MONTH_YEAR_CSS("div#ui-datepicker-div[style*='display: block;'] td.ui-datepicker-today"),
	ORDERING_BO_BMT_ADD_NEW_RULE_EFFECTIVE_DATE_ID("end-date"),
	ORDERING_BO_BMT_ADD_NEW_RULE_EFFECTIVE_DATE_SYMBOL_XPATH("//button[@data-target-name='end-date']"),
	ORDERING_BO_BMT_ADD_NEW_RULE_EFFECTIVE_DATE_CSS("div#ui-datepicker-div[style*='display: block;'] td.ui-datepicker-today+td > a"),
	ORDERING_BO_BMT_ADD_NEW_RULE_EFFECTIVE_DATE_MONTH_YEAR_CSS("div#ui-datepicker-div[style*='display: block;'] td.ui-datepicker-today+td"),
	ORDERING_BO_BMT_ADD_NEW_RULE_CORP_ID("corp"),
	ORDERING_BO_BMT_ADD_NEW_RULE_CONTRACT_TYPE_NAME("OCT"),
	ORDERING_BO_BMT_ADD_NEW_RULE_ORDER_TYPE_NAME("OT"),
	ORDERING_BO_BMT_ADD_NEW_RULE_PRODUCT_CLASS_NAME("PC"),
	ORDERING_BO_BMT_ADD_NEW_RULE_YEAR_ID("year"),
	ORDERING_BO_BMT_ADD_NEW_RULE_MAKE_ID("make"),
	ORDERING_BO_BMT_ADD_NEW_RULE_MODEL_ID("model"),
	ORDERING_BO_BMT_ADD_NEW_RULE_STATE_ID("state"),
	ORDERING_BO_BMT_ADD_NEW_RULE_CLIENT_SEARCH_ID("client-search"),
	ORDERING_BO_BMT_ADD_NEW_RULE_VEHICLE_BREAKDOWN_NAME("vb"),
	ORDERING_BO_BMT_ADD_NEW_RULE_DRIVER_BREAKDOWN_NAME("db"),
	ORDERING_BO_BMT_ADD_NEW_RULE_APPROVE_FOR_CLIENT_ID("client-view-approved"),
	ORDERING_BO_BMT_ADD_NEW_RULE_APPLY_INFLIGHT_ORDERS_ID("apply-in-flight"),
	ORDERING_BO_BMT_ADD_NEW_RULE_CAPPING_NOTES_TEXT_ID("capping-notes-txt"),
	ORDERING_BO_BMT_ADD_NEW_RULE_CAPPING_NOTES_CLEAR_ID("clear-capping-notes"),
	ORDERING_BO_BMT_ADD_NEW_RULE_SAVE_BUTTON_ID("save-entity"),
	ORDERING_BO_BMT_ADD_NEW_RULE_CANCEL_BUTTON_ID("cancel-entity"),
	ORDERING_BO_BMT_ADD_NEW_RULE_NAVIGATION_ID("breadcrumbs"),
	ORDERING_BO_BMT_ADD_NEW_RULE_SIGNOUT_XPATH("//input[@value='Sign Out']"),
	ORDERING_BO_BMT_ADD_NEW_RULE_CLEAR_CAPPING_RULE_ID("clear-capping-rule"),
	ORDERING_BO_BMT_ADD_NEW_RULE_SMART_RULE_SELECTION_XPATH("//label[contains(text(),'$SmartRule#')]//preceding::input[1]"),
	ORDERING_BO_BMT_ADD_NEW_RULE_CLIENT_SEARCH_FIELD_ID("client-search"),
	ORDERING_BO_BMT_ADD_NEW_RULE_CLIENT_SEARCH_OPTION_XPATH("//div[@class='tt-suggestion tt-selectable empty']"),
	ORDERING_BO_BMT_RULE_ID_COLUMN_DATA1_XPATH("//td[contains(text(),'$Rule#')]//preceding::i[1]//following::td[@data-name='ruleGroupId'][1]"),
	ORDERING_BO_BMT_RULE_COLUMN_DATA_XPATH("//td[contains(text(),'$RuleID#')]//preceding::i[1]//following::td[@data-name='rule'][1]"),
	ORDERING_BO_BMT_RULE_ID_COLUMN_DATA_XPATH("//td[contains(text(),'$RuleID#')]//preceding::i[1]//following::td[@data-name='ruleGroupId'][1]"),
	ORDERING_BO_BMT_RULE_ID_COLUMN_DATA_ARCHIVED_XPATH("//td[@data-val='$RuleID#']"),
	ORDERING_BO_BMT_ARCHIVED_DATE_COLUMN_DATA_ARCHIVED_XPATH("//td[@data-val='$RuleID#']//following::td[@data-name='archivedDate'][1]"),
	ORDERING_BO_BMT_CORP_CODE_COLUMN_DATA_XPATH("//td[contains(text(),'$RuleID#')]//preceding::i[1]//following::td[@data-name='corpCode'][1]"),
	ORDERING_BO_BMT_CLIENT_COLUMN_XPATH("//td[contains(text(),'$RuleID#')]//preceding::i[1]//following::td[@data-name='clientNumber'][1]"),
	ORDERING_BO_BMT_CLIENT_VIEW_XPATH("//td[contains(text(),'$RuleID#')]//preceding::i[1]//following::td[@data-name='clientView'][1]"),
	ORDERING_BO_BMT_IN_FLIGHT_ORDER_COLUMN_XPATH("//td[contains(text(),'$RuleID#')]//preceding::i[1]//following::td[@data-name='inFlightOrders'][1]"),
	ORDERING_BO_BMT_BREAKDOWN_COLUMN_XPATH("//td[contains(text(),'$RuleID#')]//preceding::i[1]//following::td[@data-name='breakdown'][1]"),
	ORDERING_BO_BMT_CONTRACT_TYPE_COLUMN_XPATH("//td[contains(text(),'$RuleID#')]//preceding::i[1]//following::td[@data-name='contractType'][1]"),
	ORDERING_BO_BMT_ORDER_TYPE_XPATH("//td[contains(text(),'$RuleID#')]//preceding::i[1]//following::td[@data-name='orderType'][1]"),
	ORDERING_BO_EFFECTIVE_DATE_COLUMN_XPATH("//td[contains(text(),'$RuleID#')]//preceding::i[1]//following::td[@data-name='effDate'][1]"),
	ORDERING_BO_BMT_EFFECTIVE_UNTIL_DATE_XPATH("//td[contains(text(),'$RuleID#')]//following::td[@data-name='endDate'][1]"),
	ORDERING_BO_BMT_PRODUCT_CLASS_COLUMN_XPATH("//td[contains(text(),'$RuleID#')]//preceding::i[1]//following::td[@data-name='productClass'][1]"),
	ORDERING_BO_BMT_STATE_COLUMN_XPATH("//td[contains(text(),'$RuleID#')]//preceding::i[1]//following::td[@data-name='stateProvience'][1]"),
	ORDERING_BO_BMT_YEAR_CULUMN_XPATH("//td[contains(text(),'$RuleID#')]//preceding::i[1]//following::td[@data-name='year'][1]"),
	ORDERING_BO_BMT_MAKE_COLUMN_XPATH("//td[contains(text(),'$RuleID#')]//preceding::i[1]//following::td[@data-name='make'][1]"),
	ORDERING_BO_BMT_MODEL_COLUMN_XPATH("//td[contains(text(),'$RuleID#')]//preceding::i[1]//following::td[@data-name='model'][1]"),
	ORDERING_BO_BMT_ROW_ACTIONS_XPATH("//td[contains(text(),'$RuleId#')]//preceding::td[2]//button"),
	ORDERING_BO_BMT_ROW_ACTION_EDIT_XPATH("//td[contains(text(),'$RuleId#')]//preceding::td[2]//following::ul[1]//li//a[contains(text(),'Edit')]"),
	ORDERING_BO_BMT_ROW_ACTION_VIEW_XPATH("//td[contains(text(),'$RuleId#')]//preceding::td[2]//following::ul[1]//li//a[contains(text(),'View')]"),
	ORDERING_BO_BMT_ROW_ACTION_COPY_XPATH("//td[contains(text(),'$RuleId#')]//preceding::td[2]//following::ul[1]//li//a[contains(text(),'Copy')]"),
	ORDERING_BO_BMT_ROW_ACTION_ARCHIVE_XPATH("//td[contains(text(),'$RuleId#')]//preceding::td[2]//following::ul[1]//li//a[contains(text(),'Archive')]"),
	ORDERING_BO_BMT_ROW_ACTION_UNARCHIVE_XPATH("//td[contains(text(),'$RuleId#')]//preceding::td[2]//ul[1]//a[contains(text(),'Unarchive')]"),
	ORDERING_BO_BMT_CLIENT_SELECTED_XPATH("//ul[@id='select-client']//li"),
	ORDERING_BO_BMT_GO_BACK_TO_CAPPING_RULE_XPATH("//a[contains(text(),'Capping Rules')]"),
	ORDERING_BO_BMT_EDIT_OR_COPY_ARCHIVE_POP_UP_YES_NO_XPATH("//button[contains(text(),'$EditOrCopyYesNo#')]"),
	ORDERING_BO_BMT_EDIT_POP_UP_CONFIRMATION_TEXT_XPATH("//div[@id='new-modal']//div[contains(@class,'modal-body')]//h5"),
	ORDERING_BO_BMT_EDIT_COPY_ARCHIVE_POP_UP_TITLE_XPATH("//div[@id='new-modal']//div[@class='modal-dialog']//span[@class='message']"),
	ORDERING_BO_BMT_UNABLE_TO_COPY_RULE_TITLE_XPATH("//div[@id='new-modal']//div[@class='modal-dialog']//span[@class='message']"),
	ORDERING_BO_BMT_COPY_ARCHIVE_POP_UP_CONFIRMATION_TEXT1_XPATH("//h5[1]"),
	ORDERING_BO_BMT_UNABLE_TO_COPY_POP_UP_CONFIRMATION_XPATH("//div[@id='new-modal']//div[contains(@class,'modal-body')]//span"),
	ORDERING_BO_BMT_UNABLE_TO_COPY_POP_UP_OK_XPATH("//button[contains(text(),'OK')]"),
	ORDERING_BO_BMT_COPY_ARCHIVE_POP_UP_CONFIRMATION_TEXT2_XPATH("//h5[3]"),
	ORDERING_BO_BMT_ARCHIVE_POP_UP_CONFIRMATION_TEXT2_XPATH("//h5[2]"),
	ORDERING_BO_BMT_COPY_PAGE_TITLE_XPATH("//div[@class='subscreen-title']"),
	ORDERING_BO_BMT_COPY_IN_FLIGHT_ORDERS_ID("copy-to-in-flight"),
	ORDERING_BO_BMT_COPY_RULE_COUNT_CSS("#rule-count"),
	ORDERING_BO_BMT_ARCHIVE_POP_UP_NOTE_TEXT_ID("archive-note-txt"),
	ORDERING_BO_BMT_ARCHIVE_POP_UP_CANCEL_XPATH("//button[contains(text(),'Archive')]//preceding::button[1]"),
	ORDERING_BO_BMT_ARCHIVE_OR_ACTIVE_RULE_TAB_XPATH("//a[contains(text(),'$RuleTab#')]"),
	ORDERING_BO_BMT_CAPPING_SMART_RULE_BULK_COPY_DISABLED_XPATH("//button[@id='csr-bulk-copy-btn'][@disabled='']"),
	ORDERING_BO_BMT_CAPPING_SMART_RULE_BULK_COPY_ENABLED_XPATH("//button[@id='csr-bulk-copy-btn']"),
	ORDERING_BO_BMT_CAPPING_RULE_BULK_COPY_DISABLED_XPATH("//button[@id='bulk-copy-btn'][@disabled='']"),
	ORDERING_BO_BMT_CAPPING_RULE_BULK_COPY_ENABLED_XPATH("//button[@id='bulk-copy-btn']"),
	ORDERING_BO_BMT_CAPPING_SMART_RULE_BULK_ARCHIVE_DISABLED_XPATH("//button[@id='csr-bulk-archive-btn'][@disabled='']"),
	ORDERING_BO_BMT_CAPPING_SMART_RULE_BULK_ARCHIVE_ENABLED_XPATH("//button[@id='csr-bulk-archive-btn']"),
	ORDERING_BO_BMT_CAPPING_RULE_BULK_ARCHIVE_DISABLED_XPATH("//button[@id='bulk-archive-btn'][@disabled='']"),
	ORDERING_BO_BMT_CAPPING_RULE_BULK_ARCHIVE_ENABLED_XPATH("//button[@id='bulk-archive-btn']"),
	ORDERING_BO_BMT_CAPPING_SMART_RULE_BULK_UNARCHIVE_DISABLED_XPATH("//div[@id='archive-capping-smart-rules']//button[@id='bulk-unarchive-btn'][@disabled='']"),
	ORDERING_BO_BMT_CAPPING_SMART_RULE_BULK_UNARCHIVE_ENABLED_XPATH("//div[@id='archive-capping-smart-rules']//button[@id='bulk-unarchive-btn']"),
	ORDERING_BO_BMT_CAPPING_RULE_BULK_UNARCHIVE_DISABLED_XPATH("//div[@id='archive-capping-rules']//button[@id='bulk-unarchive-btn'][@disabled='']"),
	ORDERING_BO_BMT_CAPPING_RULE_BULK_UNARCHIVE_ENABLED_XPATH("//div[@id='archive-capping-rules']//button[@id='bulk-unarchive-btn']"),
	ORDERING_BO_BMT_CAPPING_RULE_SMART_BULK_SELECTION_CHECKBOX_XPATH("//div[@id='capping-smart-rules-summary']//td[contains(text(),'$RuleId#')]//preceding::td[3]//label"),
	ORDERING_BO_BMT_CAPPING_RULE_BULK_SELECTION_CHECKBOX_XPATH("//div[@id='capping-rules-summary']//td[contains(text(),'$RuleId#')]//preceding::td[3]//label"),
	ORDERING_BO_BMT_CAPPING_RULE_SMART_BULK_SELECTION_ARCHIVE_XPATH("//div[@id='archive-capping-smart-rules-summary']//td[contains(text(),'$RuleId#')]//preceding::td[3]//label"),
	ORDERING_BO_BMT_CAPPING_RULE_BULK_SELECTION_ARCHIVE_XPATH("//div[@id='archive-capping-rules-summary']//td[contains(text(),'$RuleId#')]//preceding::td[3]//label"),
	ORDERING_BO_BMT_CAPPING_RULE_BULK_SELECTION_COPY_XPATH("//td[contains(text(),'$RuleId#')]//preceding::td[3]//label"),
	ORDERING_BO_BMT_BULK_COPY_RULE_ID_LIST_XPATH("//td[@data-name='ruleGroupId']"),
	ORDERING_BO_BMT_COPY_RULE_BULK_SELECTION_CHECKBOX_XPATH("//td[@data-val='$RuleId#']//preceding::td[2]//label"),
	ORDERING_BO_BMT_RULE_IDS_BULK_ACTION_XPATH("//td[contains(text(),'$Rule#')]//preceding::i[1]//following::td[@data-name='ruleGroupId'][$count#]"),
	ORDERING_BO_BMT_CLIENT_COLUMN_BULK_ACTION_XPATH("//td[contains(text(),'$RuleID#')]//following::td[2]"),
	ORDERING_BO_BMT_CAPPING_SMART_RULE_RULE_NAME_XPATH("//div[@id='capping-smart-rules-summary']//input[@id='rule-input']"),
	ORDERING_BO_BMT_CAPPING_RULE_RULE_NAME_XPATH("//div[@id='capping-rules-summary']//input[@id='rule-input']"),
	ORDERING_BO_BMT_CAPPING_SMART_RULE_SEARCH_XPATH("//div[@id='capping-smart-rules-summary']//button[@id='search-by-filters-btn']"),
	ORDERING_BO_BMT_CAPPING_RULE_SEARCH_XPATH("//div[@id='capping-rules-summary']//button[@id='search-by-filters-btn']"),
	ORDERING_BO_BMT_CAPPING_SMART_RULE_TOGGLE_FILTER_XPATH("//div[@id='capping-smart-rules-summary']//button[@id='toggle-filter']"),
	ORDERING_BO_BMT_CAPPING_RULE_TOGGLE_FILTER_XPATH("//div[@id='capping-rules-summary']//button[@id='toggle-filter']"),
	ORDERING_BO_BMT_CAPPING_SMART_RULE_RULE_NAME_ARCHIVED_XPATH("//div[@id='archive-capping-smart-rules-summary']//input[@id='rule-input']"),
	ORDERING_BO_BMT_CAPPING_RULE_RULE_NAME_ARCHIVED_XPATH("//div[@id='archive-capping-rules-summary']//input[@id='rule-input']"),
	ORDERING_BO_BMT_CAPPING_SMART_RULE_SEARCH_ARCHIVED_XPATH("//div[@id='archive-capping-smart-rules-summary']//button[@id='search-by-filters-btn']"),
	ORDERING_BO_BMT_CAPPING_RULE_SEARCH_ARCHIVED_XPATH("//div[@id='archive-capping-rules-summary']//button[@id='search-by-filters-btn']"),
	ORDERING_BO_BMT_CAPPING_SMART_RULE_TOGGLE_FILTER_ARCHIVED_XPATH("//div[@id='archive-capping-smart-rules-summary']//button[@id='toggle-filter']"),
	ORDERING_BO_BMT_CAPPING_RULE_TOGGLE_FILTER_ARCHIVED_XPATH("//div[@id='archive-capping-rules-summary']//button[@id='toggle-filter']"),
	ORDERING_BO_BMT_CAPPING_RULE_CLIENT_XPATH("//li[@data-client='$ClientNumber#']"),
	ORDERING_BO_BMT_EDIT_BMT_PAGE_INSURANCE_SECTION_XPATH("//div[@class='price-protection__container']"),
	ORDERING_BO_BMT_CDD_ASSIGNMENT_RULE_XPATH("//div[contains(text(),'Customer Delivering Dealer Assignment Rules')]"),
	ORDERING_BO_BMT_CDDA_Add_NEW_XPATH("//div[@class='btn green btn-shared addNew']//span"),
	ORDERING_BO_BMT_CDDA_CUST_SUBTITLE_XPATH("//div[@id='customersubtitle']"),
	ORDERING_BO_BMT_CDDA_CORP_XPATH("//div[@class='row-flex']//div[@class='display-lbl']//label[1]"),
	ORDERING_BO_BMT_CDDA_CROPS_XPATH("//select[@id='corps']"),
	ORDERING_BO_BMT_CDDA_SEARCH_CLIENT_XPATH("//input[@id='search-client']"),
	ORDERING_BO_BMT_CDDA_GROUP_NAME_XPATH("//input[@id='group-name']"),
	ORDERING_BO_BMT_CDDA_START_DATE2_XPATH("//input[@id='start-date']"),
	ORDERING_BO_BMT_CDDA_END_DATE2_XPATH("//input[@id='end-date']"),
	ORDERING_BO_BMT_CDDA_SEARCH_CLIENT_FIRST_SUGGESTION_XPATH("//body/div[@id='mainContainer']/section[1]/div[3]/div[1]/div[1]/div[1]/div[1]/form[1]/section[1]/section[1]/div[1]/div[2]/div[2]/span[1]/div[1]/div[1]/div[1]"),
	ORDERING_BO_CDDAR_ADD_RULE_MAKE_XPATH("//div[@id='MAKE']//button[@class='btn multiselect dropdown-toggle btn-default']"),
	ORDERING_BO_CDDAR_ADD_RULE_MAKE2_XPATH("//div[@id='multiSelecMakes']//ul[@class='multiselect-container dropdown-menu']//li[3]"),
	ORDERING_BO_CDDAR_ADD_RULE_MAKE3_XPATH("//div[@id='MAKE']"),
	ORDERING_BO_BMT_CDDA_DEALER_SEARCH_XPATH("//input[@name='search-dealer']"),
	ORDERING_BO_BMT_CDDA_SEARCH_DEALER_XPATH("//input[@id='search-dealer']"),
	ORDERING_BO_BMT_CDDA_SEARCH_CLIENT_FIRST_SUGG_XPATH("//div[@class='tt-suggestion tt-selectable sugg-item'])[1]"),
	ORDERING_BO_BMT_CDDA_SEARCH_BUTTON_XPATH("//div[@class='btn green btn-shared search']"),
	ORDERING_BO_BMT_CDDA_RULE_LABEL_XPATH("//input[@name ='ruleName']"),
	ORDERING_BO_BMT_LDU_XPATH("//div[@class='full-menu']//div[@data-target='LDMQ']"),
	ORDERING_BO_BMT_LDU_SIGNOUT_BUTTON_XPATH("//input[@value='Sign Out']"),
	ORDERING_BO_BMT_LDU_CLEAR_FILTER_BUTTON_XPATH("//button[@id='clear-all-filters-btn']"),
	ORDERING_BO_BMT_LDU_SEARCH_BUTTON_XPATH("//button[@id='search-by-filters-btn']"),
	ORDERING_BO_BMT_LDU_TABLE_VIEW_BUTTON_XPATH("//button[@id='default-view-button']"),
	ORDERING_BO_BMT_LDU_EXPORT_BUTTON_XPATH("//button[@id='export-CSV-button']"),
	ORDERING_BO_BMT_LDU_TABLE_ROW_XPATH("//div[@id='queue-table']//tbody//tr"),
	ORDERING_BO_BMT_LDU_PAGE_LAST_XPATH("//span[contains(@id,'last')]"),
	ORDERING_BO_BMT_LDU_PAGE_NEXT_XPATH("//span[contains(@id,'next')]"),
	ORDERING_BO_BMT_LDU_PAGE_FIRST_XPATH("//span[contains(@id,'first')]"),
	ORDERING_BO_BMT_LDU_PAGE_PREV_XPATH("//span[contains(@id,'prev')]"),
	ORDERING_BO_BMT_LDU_COLUMN_NAME_XPATH("//div[@id='queue-table']//div[@class='dataTables_scrollHeadInner']//th[not(contains(@style,'none'))]"),
	ORDERING_BO_BMT_LDU_LAST_UPDATED_DATE_XPATH("//td[@data-name='lastUpdateDate']"),
	ORDERING_BO_BMT_LDU_SEARCH_XPATH("//label[text()='%s']//following-sibling::input"),
	ORDERING_BO_BMT_LDU_TABLE_XPATH("//div[@id='queue-table']//td[contains(@data-name,'%s')]"),
	ORDERING_BO_BMT_LDU_SAVE_BTN_XPATH("//div[@id='save-entity']"),
	ORDERING_BO_BMT_LDU_CORP_CODE_SELECT_XPATH("//select[@id='corpCode']"),
	ORDERING_BO_BMT_LDU_CLIENT_NUMBER_INPUT_XPATH("//input[@id='clientNumber']"),
	ORDERING_BO_BMT_LDU_DOCUMENT_CATEGORY_SELECT_XPATH("//select[@id='documentCategoryCode']"),
	ORDERING_BO_BMT_LDU_DOCUMENT_TYPE_SELECT_XPATH("//select[@id='documentTypeCode']"),
	ORDERING_BO_BMT_LDU_DOCUMENT_CATEGORY_ERROR_XPATH("//select[@id='documentCategoryCode']/following-sibling::div//span"),
	ORDERING_BO_BMT_LDU_DOCUMENT_TYPE_ERROR_XPATH("//select[@id='documentTypeCode']/following-sibling::div//span"),
	ORDERING_BO_BMT_LDU_DOCUMENT_DATE_ERROR_XPATH("//div[@id='div-archiveTimestamp']//div[@class='field-error bottom']"),
	ORDERING_BO_BMT_LDU_BROWSE_BTN_XPATH("//label[@class='custom-file-upload button button--primary']"),
	ORDERING_BO_BMT_LDU_ADD_BTN_XPATH("//button[@id='add-new-button']"),
	ORDERING_BO_BMT_LDU_ARCHIVE_DATE_INPUT_XPATH("//input[@id='archiveTimestamp']"),
	ORDERING_BO_BMT_LDU_ARCHIVE_DATE_PICKER_XPATH("//input[@id='archiveTimestamp']/following-sibling::button"),
	ORDERING_BO_BMT_LDU_ARCHIVE_DATE_PICKER_TODAY_XPATH("//td[contains(@class,'ui-datepicker-today')]"),
	ORDERING_BO_BMT_COD_ASSIGNMENT_RULE_XPATH("//div[@data-target='COARQ']"),
	ORDERING_BO_BMT_COD_TABLE_HEADER_XPATH("//th[@data-name]"),
	ORDERING_BO_BMT_COD_GLOBAL_SPINNER_CSS("div.global-spinner-wrapper"),
	ORDERING_BO_BMT_COD_FIRSTRECORD_VALUES_XPATH("//tbody//tr[@class='odd'][1]//td[@data-name]"),
	ORDERING_BO_BMT_COD_INPUT_FIELDS_XPATH("//section[@id='standard']//input[@type='text']"),
	ORDERING_BO_BMT_COD_TABLE_BODY_ROW_XPATH("//tbody//tr"),
	ORDERING_BO_BMT_COD_DIV_RULE_ID("div-ruleGroupId"),
	ORDERING_BO_BMT_COD_TOGGLE_COLUMNS_BUTTON_XPATH("//button[@data-toggle='dropdown']"),
	ORDERING_BO_BMT_COD_TOGGLE_COLUMNS_CHECKBOXES_XPATH("//ul//input[@type='checkbox']"),
	ORDERING_BO_BMT_COD_ADD_NEW_RULE_BUTTON_XPATH("//div[@class='btn green btn-shared addNew']"),
	ORDERING_BO_BMT_COD_CORP_CODE_SELECT_ID("corpCode"),
	ORDERING_BO_BMT_COD_CLIENT_NUMBER_SELECT_ID("clientNumber"),
	ORDERING_BO_BMT_COD_ALWAYS_USE_SELECT_ID("alwaysUseIndicator"),
	ORDERING_BO_BMT_COD_DIVERSE_SWITCH_XPATH("//div[@class='toggle-switch']//label"),
	ORDERING_BO_BMT_COD_MAKE_SELECT_ID("makeIndicator"),
	ORDERING_BO_BMT_COD_FLEET_INPUT_XPATH("//input[@name='clientNumber']"),
	ORDERING_BO_BMT_COD_MAKE_INPUT_XPATH("//input[@name='make']"),
	ORDERING_BO_BMT_COD_DELETE_BUTTON_XPATH("//div[contains(@class, 'Delete')]"),
	ORDERING_BO_BMT_COD_ORDER_CHECKBOX_XPATH("//input[@name='order-check']"),
	ORDERING_BO_BMT_COD_CANCEL_WARNING_MODAL_XPATH("//div[@class='modal-body']"),
	ORDERING_BO_BMT_COD_DELETE_WARNING_MODAL_XPATH("//div[@class='modal-body new-modal__body']"),
	ORDERING_BO_BMT_COD_CONFIRM_DELETE_MODAL_BUTTON_XPATH("//button[@class='button button--primary btn-spacing js-button-primary']"),
	ORDERING_BO_BMT_COD_CANCEL_DELETE_MODAL_BUTTON_XPATH("//button[@class='button button--secondary btn-spacing']"),
	ORDERING_BO_BMT_COD_RULEID_INPUT_XPATH("//input[@name='ruleGroupId']"),
	ORDERING_BO_BMT_COD_NODATA_RESULT_LABEL_XPATH("//td[@class='dataTables_empty']"),
	ORDERING_BO_BMT_COD_NOTIFICATION_MESSAGE_LABEL_CSS("div.noty_bar"),
	ORDERING_BO_BMT_COD_ENDDATE_INPUT_ID("effectiveEndDate"),
	ORDERING_BO_BMT_COD_ENDDATE_LABEL_XPATH("//div[@id='div-effectiveEndDate']//label"),
	ORDERING_BO_BMT_COD_ENDDATE_INVALID_MESSAGE_XPATH("//div[@class='field-error bottom']"),
	ORDERING_BO_BMT_COD_EXPORT_BUTTON_XPATH("//div[@class='btn blue btn-shared queue-export']"),
	ORDERING_BO_BMT_EOD_EODAR_LINK_XPATH("//div[@data-target='EOARQ']"),
	ORDERING_BO_BMT_EOD_CORPCODE_ROW_LABEL_XPATH("//td[@data-name='corpCode']"),
	ORDERING_BO_BMT_EOD_RULENAME_INPUT_ID("ruleGroupName"),
	ORDERING_BO_BMT_EOD_DIVERSE_SWITCH_ID("diverse"),
	ORDERING_BO_BMT_EOD_STARTDATE_INPUT_XPATH("//input[@name='effDate']"),
	ORDERING_BO_BMT_NEWRULE_TODAY_CALENDAR_XPATH("//a[contains(@class, 'ui-state-default ui-state')]"),
	ORDERING_BO_BMT_CDDAR_ALERT_TEXT1_XPATH("//body/div[@id='new-modal']/div[1]/div[1]/div[3]/button[2]"),
	ORDERING_BO_BMT_CDDAR_ALERT_TEXT2_XPATH("//body/div[@id='new-modal']/div[1]/div[1]/div[2]/div[1]"),
	ORDERING_BO_BMT_CDDAR_ADD_RULE_XPATH("//div[@id='add-group']"),	
	ORDERING_BO_BMT_CDDAR_CORP_SEARCH_XPATH("//input[@name='corp']"),
	ORDERING_BO_BMT_CDDAR_FLEET_ID_SEARCH_XPATH("//input[@name='fleet']"),
	ORDERING_BO_BMT_CDDAR_RULE_NAME_SEARCH_XPATH("//input[@name='ruleName']"),
	ORDERING_BO_BMT_CDDAR_RULE_NAME_TABLE_XPATH("//td[@data-name='ruleName']"),
	ORDERING_BO_BMT_ADD_NEW_BTN_XPATH("//div[@class='btn green btn-shared addNew']"),
	ORDERING_BO_BMT_SEARCH_XPATH("//div[contains(@class,'btn green btn-shared search')]"),
	ORDERING_BO_BMT_SAVE_BTN_XPATH("//div[@id='save-group']"),
	ORDERING_BO_BMT_DELETE_BTN_XPATH("//div[@id='delete-group']"),
	ORDERING_BO_BMT_BACK_TO_QUEUE_BTN_XPATH("//div[@id='browser-back-cdar']"),
	ORDERING_BO_BMT_CDDAR_CORP_SELECT_XPATH("//select[@id='corps']"),
	ORDERING_BO_BMT_CDDAR_FLEETID_INPUT_XPATH("//input[@id='search-client']"),
	ORDERING_BO_BMT_CDDAR_RULE_NAME_INPUT_XPATH("//input[@id='group-name']"),
	ORDERING_BO_BMT_CDDAR_COURSTESY_DELIVERY_INPUT_XPATH("//input[@name='INPUT-CD']"),
	ORDERING_BO_BMT_CDDAR_SUGGESTION_XPATH("//div[@class='tt-suggestion tt-selectable empty']/strong"),
	ORDERING_BO_BMT_CDDAR_SUGGESTION_FLEET_XPATH("//div[@class='tt-menu tt-open']/div[@class='tt-dataset tt-dataset-contactSearch']"),
	ORDERING_BO_BMT_CDDAR_OK_BTN_XPATH("//button[@class='button button--primary btn-spacing js-button-primary']"),
	ORDERING_BO_BMT_CDDAR_CANCEL_BTN_XPATH("//button[@class='button button--secondary btn-spacing']"),
	ORDERING_BO_EDDAR_SIDE_MENU_XPATH("//div[@data-target='EDARQ']//div[@class='title']"),
	ORDERING_BO_CAPPING_SMART_RULE_ID_COLUMN_XPATH("//div[@id='capping-smart-rules']//th[contains(@aria-label,'Rule ID')]"),
	ORDERING_BO_CAPPING_RULE_ID_COLUMN_XPATH("//div[@id='capping-rules']//th[contains(@aria-label,'Rule ID')]"),
	ORDERING_BO_CAPPING_ARCHIVE_SMART_RULE_ID_COLUMN_XPATH("//div[@id='archive-capping-smart-rules']//th[contains(@aria-label,'Rule ID')]"),
	ORDERING_BO_CAPPING_ARCHIVE_RULE_ID_COLUMN_XPATH("//div[@id='archive-capping-rules']//th[contains(@aria-label,'Rule ID')]"),
	
	;

	private String value;

	OrderingBOBusinessMaintainedTablesEnum(String value) {
		this.value = value;
	}

	public String getValue() {
		return value;
	}

	@Override
	public String toString() {
		return value;
	}

}