package com.element.fleet.ordering.enums;

public enum OrderingFOFleetPreferencesPageEnum {
	
	ORDERING_FO_FLEETPREFERENCES_ORDERINGFLLETPREFERENCES_XPATH("//div[contains(text(),'Ordering Fleet Preferences')]"),
	ORDEING_HOME_FLEET_PREFRENCES_GENERAL_XPATH("//div[contains(text(),'General')]"),
	ORDEING_HOME_FLEET_PREFRENCES_GENERAL_CLIENT_NAME_XPATH("//*[@id='fleet-preferences']/div[2]/div[2]/div[2]/p[2]"),
	ORDEING_HOME_FLEET_PREFRENCES_COMMUNICATIONS_XPATH("//div[contains(text(),'Communications')]"),
	ORDERING_FO_FLEETPREFERENCES_CLIENT_COMMUNICATIONS_YES_ID("RCMY"),
	ORDERING_FO_FLEETPREFERENCES_CLIENT_COMMUNICATIONS_NO_ID("RCMN"),
	ORDERING_FO_FLEETPREFERENCES_CLIENT_COMMUNICATIONS_ADD_NEW_RECIPIENT_LINK_XPATH("//div[@id='client-communication']//a[@class='add-contact']"),	
	ORDEING_HOME_FLEET_PREFRENCES_COMMUNICATIONS_RECEIVE_CLIENT_COMMUNITCATIONS_XPATH("//div[contains(text(),'client-communication')]"),	
	ORDEING_HOME_FLEET_PREFRENCES_PROACTIVE_XPATH("//div[contains(text(),'Proactive Spec Maintenance')]"),
	ORDEING_HOME_FLEET_PREFRENCES_PROACTIVE_SPEC_MAINTENANCE_RECEIVE_CLIENT_COMMUNITCATIONS_XPATH("//div[@data-preference-cd='RCN']/label"),
	ORDEING_HOME_FLEET_PREFRENCES_PROACTIVE_SPEC_MAINTENANCE_RECEIVE_CLIENT_COMMUNITCATIONS_YES_ID("RCNY"),
	ORDEING_HOME_FLEET_PREFRENCES_PROACTIVE_SPEC_MAINTENANCE_RECEIVE_CLIENT_COMMUNITCATIONS_NO_ID("RCNN"),
	ORDEING_HOME_FLEET_PREFRENCES_DEALER_XPATH("//div[contains(text(),'Dealer')]"),
	ORDEING_HOME_FLEET_PREFRENCES_TITLE_AND_REGISTRATION_XPATH("//div[contains(text(),'Title & Registration')]"),
	ORDEING_HOME_FLEET_PREFRENCES_BILLING_XPATH("//div[contains(text(),'Billing')]"),
	ORDEING_HOME_FLEET_PREFRENCES_DRIVER_XPATH("//section[@id='driver']//div[@class='title']"),
	ORDERING_FO_FLEETPREFERENCES_AUTO_UNIT_YES_ID("AUNY"),
	ORDERING_FO_FLEETPREFERENCES_AUTO_UNIT_NO_ID("AUNN"),
	ORDERING_FO_FLEETPREFERENCES_START_UNIT_NUMBER_ID("SUN"),
	ORDERING_FO_FLEETPREFERENCES_END_UNIT_NUMBER_ID("EUN"),
	ORDERING_FO_FLEETPREFERENCES_LAST_UNIT_NUMBER_ID("LUN"),
	ORDERING_FO_FLEETPREFERENCES_WHO_TO_SELL_USED_UNIT_ID("WSU"),
	ORDERING_FO_FLEETPREFERENCES_COMPETITOR_TO_NOTIFY_ID("NTC"),
	ORDERING_FO_FLEETPREFERENCES_IS_RENTAL_FLEET_YES_ID("RFIY"),
	ORDERING_FO_FLEETPREFERENCES_IS_RENTAL_FLEET_NO_ID("RFIN"),
	ORDERING_FO_FLEETPREFERENCES_REQUESTED_DELIVERING_DEALER_YES_ID("ARDY"),
	ORDERING_FO_FLEETPREFERENCES_REQUESTED_DELIVERING_DEALER_NO_ID("ARDN"),
	ORDERING_FO_FLEETPREFERENCES_PROCEED_OK_XPATH("//button[@class='modal-ok-btn proceed-update-SUN']"),
	ORDERING_FO_FLEETPREFERENCES_SAVE_XPATH("//div[@data-target='save'][@class='btn pull-left save']"),
	ORDERING_FO_FLEETPREFERENCES_CLOSE_XPATH("//i[@class='fa fa-times close']"),
	ORDERING_FO_FLEETPREFERENCES_CLOSE_OK_XPATH("//button[@class='modal-ok-btn']"),
	ORDERING_FO_FLEETPREFERENCES_DRIVER_TAB_LABEL_ID("DRT"),
	ORDERING_FO_FLEETPREFERENCES_DRIVER_FIRST_NAME_ID("DRFN"),
	ORDERING_FO_FLEETPREFERENCES_DRIVER_LAST_NAME_ID("DRLN"),
	ORDERING_FO_FLEETPREFERENCES_FINAL_ORDDER_SUMMARY_YES_ID("AEDY"),
	ORDERING_FO_FLEETPREFERENCES_FINAL_ORDDER_SUMMARY_NO_ID("AEDN"),
	ORDERING_FO_FLEETPREFERENCES_DRIVER_PAID_OPTION_YES_ID("POAY"),
	ORDERING_FO_FLEETPREFERENCES_DRIVER_PAID_OPTION_NO_ID("POAN"),
	ORDERING_FO_FLEETPREFERENCES_PAYMENT_OPTION_LABEL_XPATH("//label[contains(text(),'Select DPO Payment Options')]"),
	ORDERING_FO_FLEETPREFERENCES_DPO_PAYMENT_OPTIONS_XPATH("//div[@data-preference-name='$PaymentOption#']//input"),
	ORDERING_FO_FLEETPREFERENCES_DPO_PAYMENT_CREDIT_CARD_XPATH("//div[@data-preference-name='Credit Card']"),
	ORDERING_FO_FLEETPREFERENCES_DPO_PAYMENT_CREDIT_UNION_XPATH("//div[@data-preference-name='Credit Union']"),
	ORDERING_FO_FLEETPREFERENCES_DPO_PAYMENT_DEBIT_CARD_XPATH("//div[@data-preference-name='Debit Card']"),
	ORDERING_FO_FLEETPREFERENCES_DPO_PAYMENT_ECHECK_XPATH("//div[@data-preference-name='eCheck']"),
	ORDERING_FO_FLEETPREFERENCES_DPO_PAYMENT_PAYROLL_DEDUCTION_XPATH("//div[@data-preference-name='Payroll Deduction']"),
	ORDERING_FO_FLEETPREFERENCES_DEFAULT_FOR_DRIVER_AWARD_YES_ID("DDAY"),
	ORDERING_FO_FLEETPREFERENCES_DEFAULT_FOR_DRIVER_AWARD_NO_ID("DDAN"),
	ORDERING_FO_FLEETPREFERENCES_DRIVER_AWARD_DOLLER_ID("AMTL"),
	ORDERING_FO_FLEETPREFERENCES_DRIVER_AWARD_PER_ID("PCTL"),
	ORDERING_FO_FLEETPREFERENCES_DRIVER_AWARD_VALUE_ID("VALD"),
	ORDERING_FO_FLEETPREFERENCES_AUTO_UNIT_NUMBER_ASSIGNMENT_LABEL_XPATH("//div[@data-preference-cd='AUNL']/label"),
	ORDERING_FO_FLEETPREFERENCES_START_UNIT_NUMBER_LABEL_XPATH("//div[@data-preference-cd='SUNL']/label"),
	ORDERING_FO_FLEETPREFERENCES_END_UNIT_NUMBER_LABEL_XPATH("//div[@data-preference-cd='EUNL']/label"),
	ORDERING_FO_FLEETPREFERENCES_LAST_UNIT_NUMBER_LABEL_XPATH("//div[@data-preference-cd='LUNL']/label"),
	ORDERING_FO_FLEETPREFERENCES_WHO_TO_SELL_USED_UNIT_LABEL_XPATH("//div[@data-preference-cd='WSUL']/label"),
	ORDERING_FO_FLEETPREFERENCES_IS_THIS_RENTAL_FLEET_LABEL_XPATH("//div[@data-preference-cd='RFIL']/label"),
	ORDERING_FO_FLEETPREFERENCES_DRIVER_TAB_LABEL_LABEL_XPATH("//div[@data-preference-cd='DRTL']/label"),
	ORDERING_FO_FLEETPREFERENCES_DRIVER_FIRST_NAME_LABEL_XPATH("//div[@data-preference-cd='DFNL']/label"),
	ORDERING_FO_FLEETPREFERENCES_DRIVER_LAST_NAME_LABEL_XPATH("//div[@data-preference-cd='DLNL']/label"),
	ORDERING_FO_FLEETPREFERENCES_FINAL_ORDER_SUMMARY_LABEL_XPATH("//div[@data-preference-cd='AEDL']/label"),
	ORDERING_FO_FLEETPREFERENCES_DRIVER_PAID_OPTION_LABEL_XPATH("//div[@data-preference-cd='POAL']/label"),
	ORDERING_FO_FLEETPREFERENCES_PAYMENT_OPTIONS_LABEL_XPATH("//div[@data-preference-cd='SDOL']/label"),
	ORDERING_FO_FLEETPREFERENCES_DEFAULT_DRIVER_AWARD_LABEL_XPATH("//div[@data-preference-cd='DDAL']/label"),
	ORDERING_FO_FLEETPREFERENCES_EXTRA_COST_EXTERIOR_RADIO_XPATH("//input[starts-with(@id,'EC')]"),
	ORDERING_FO_FLEETPREFERENCES_EXTRA_COST_INTERIOR_RADIO_XPATH("//input[starts-with(@id,'IC')]"),
	ORDERING_FO_FLEETPREFERENCES_EXTRA_COST_INTERIOR_EXTERIOR_DRIVER_PAY_RADIO_OPTIONS_XPATH("//input[starts-with(@id,'WP')]"),
	ORDERING_FO_FLEETPREFERENCES_SAVE_BUTTON_XPATH("//div[@id='fleet-preferences']/div[1]/div[1]"),
	ORDERING_FO_FLEETPREFERENCES_CLOSE_ICON_XPATH("//div[@id='fleet-preferences']/div[1]/i"),
	ORDERING_FO_FLEETPREFERENCES_SAVE_MESSAGE_XPATH("//div[text()='Fleet Preferences have been saved successfully']"),
	ORDERING_FO_FLEETPREFERENCES_BILLING_ADD_NEW_BUTTON_XPATH("//span[text()='Add New']//ancestor::a[@class='add-billing-row']"),
	ORDERING_FO_FLEETPREFERENCES_BILLING_PRODUCT_CLASS_DROPDOWN_XPATH("//table[@id='billing-table']//tbody//tr[%s]//select[@data-preference-name='Product Class']"),
	ORDERING_FO_FLEETPREFERENCES_BILLING_CONTRACT_TYPE_DROPDOWN_XPATH("//table[@id='billing-table']//tbody//tr[%s]//select[@data-preference-name='Contract Type']"),
	ORDERING_FO_FLEETPREFERENCES_BILLING_LEASE_TERM_DROPDOWN_XPATH("//table[@id='billing-table']//tbody//tr[%s]//select[@data-preference-name='Lease Term']"),
	ORDERING_FO_FLEETPREFERENCES_BILLING_LEASE_TERM_LABEL_XPATH("//table[@id='billing-table']//tbody//tr[%s]//p[@class='lease-term-label']"),
	ORDERING_FO_FLEETPREFERENCES_BILLING_FUNDING_TYPE_LABEL_XPATH("//table[@id='billing-table']//tbody//tr[%s]//p[@class='funding-type-label']"),
	ORDERING_FO_FLEETPREFERENCES_BILLING_FUNDING_INDEX_LABEL_XPATH("//table[@id='billing-table']//tbody//tr[%s]//p[@class='funding-index-label']"),
	ORDERING_FO_FLEETPREFERENCES_BILLING_INTEREST_ADDER_LABEL_XPATH("//table[@id='billing-table']//tbody//tr[%s]//p[@class='interest-adder-label']"),
	ORDERING_FO_FLEETPREFERENCES_BILLING_ACTIONS_DELETE_LINK_XPATH("//table[@id='billing-table']//tbody//tr[%s]//a[@data-action='delete']"),
	ORDERING_FO_FLEETPREFERENCES_BILLING_ACTIONS_UNDO_LINK_XPATH("//table[@id='billing-table']//tbody//tr[%s]//a[@data-action='undo']"),
	ORDERING_FO_FLEETPREFERENCES_BILLING_TABLE_ROWS_XPATH("//table[@id='billing-table']//tbody/tr"),
	ORDERING_FO_FLEETPREFERENCES_DEALER_DELIVERING_DELEAR_YES_ID("ARDY"),
	ORDERING_FO_FLEETPREFERENCES_DEALER_DELIVERING_DELEAR_NO_ID("ARDN"),
	ORDERING_FO_FLEETPREFERENCES_REQUEST_A_DEALER_LINK_XPATH("//a[@id='requestNewDealer']"),
	ORDERING_FO_FLEETPREFERENCES_CLIENT_COMMUNICATIONS_LABEL_XPATH("//div[@data-preference-cd='RCML']/label"),
	;

	private String value;

	OrderingFOFleetPreferencesPageEnum(String value) {
		this.value = value;
	}

	public String getValue() {
		return value;
	}

	@Override
	public String toString() {
		return value;
	}

}
