package com.element.fleet.ordering.enums;

public enum OrderingBOQueuePageEnum {

	ORDERING_BO_QUEUES_MENU_CLASS("queues"),
	ORDERING_BO_SIDE_MENU_ID("side-menu"),
	ORDERING_BO_QUEUES_CLASS("full-menu"),
	ORDERING_BO_QUEUES_ELEMENTS_CLASS("title"),
	ORDERING_BO_QUEUES_HEADING_ID("queue-page-title"),
	ORDERING_BO_QUEUES_ON_ORDER_OPTION_XPATH("//div[@id='queues']//div[@data-target='OOQ']"),
	ORDERING_BO_QUEUES_ACKNOWLEDGMENT_OPTION_XPATH("//div[@id='queues']//div[@data-target='ACKQ']"),
	ORDERING_BO_QUEUES_BILLING_OPTION_XPATH("//div[@id='queues']//div[@data-target='BILQ']"),
	ORDERING_BO_QUEUES_CREDIT_OPTION_XPATH("//div[@id='queues']//div[@data-target='CREQ']"),
	ORDERING_BO_QUEUES_DEALER_OPTION_XPATH("//div[@id='queues']//div[@data-target='DEAQ']"),
	ORDERING_BO_QUEUES_DIO_OPTION_XPATH("//div[@id='queues']//div[@data-target='DIHQ']"),
	ORDERING_BO_QUEUES_DRIVER_CHANGE_OPTION_XPATH("//div[@id='queues']//div[@data-target='DRVQ']"),
	ORDERING_BO_QUEUES_INSURANCE_OPTION_XPATH("//div[@id='queues']//div[@data-target='INSQ']"),
	ORDERING_BO_QUEUES_MAINFRAME_BRIDGING_OPTION_XPATH("//div[@id='queues']//div[@data-target='MFBQ']"),
	ORDERING_BO_QUEUES_ORDER_TRANSMISSION_OPTION_XPATH("//div[@id='queues']//div[@data-target='ODTQ']"),
	ORDERING_BO_QUEUES_PROJECT_OPTION_XPATH("//div[@id='queues']//div[@data-target='PROQ']"),
	//ORDERING_BO_QUEUES_UPFIT_PROJECT_OPTION_XPATH("//div[@id='queues']//div[@data-target='UFPQ']"),
	ORDERING_BO_QUEUES_QUOTE_OPTION_XPATH("//div[@id='queues']//div[@data-target='QUOQ']"),
	ORDERING_BO_QUEUES_RFQ_OPTION_XPATH("//div[@id='queues']//div[@data-target='RFQQ']"),
	ORDERING_BO_QUEUES_STOCK_OPTION_XPATH("//div[@id='queues']//div[@data-target='STOQ']"),
	ORDERING_BO_QUEUES_SWEEPER_ADMIN_OPTION_XPATH("//div[@id='queues']//div[@data-target='SWAQ']"),
	ORDERING_BO_QUEUES_TITLE_AND_REGISTRATION_OPTION_XPATH("//div[@id='queues']//div[@data-target='TTLQ']"),
	ORDERING_BO_QUEUES_UPFIT_OPTION_XPATH("//div[@id='queues']//div[@data-target='UPFQ']"),
	ORDERING_BO_QUEUES_UPFIT_SPEC_OPTION_XPATH("//div[@data-target='UFPQ']"),
	ORDERING_BO_REJECT_BUTTON_ID("reject"),
	ORDERING_BO_RESEND_BUTTON_ID("resend"),
	ORDERING_BO_ACKNOWLEDGE_BUTTON_ID("acknowledge"),
	ORDERING_BO_ORDER_ACKNOWLEDGE_STATUS_GEN_INFO_XPATH("//label[contains(text(),'Order Status')]//ancestor::div[1]//following-sibling::span[1][contains(text(),'Acknowledged')]"),
	ORDERING_BO_ORDER_REJECTED_STATUS_GEN_INFO_XPATH("//label[contains(text(),'Order Status')]//ancestor::div[1]//following-sibling::span[1][contains(text(),'Rejected')]"),
	ORDERING_BO_ORDER_RESEND_STATUS_GEN_INFO_XPATH("//label[contains(text(),'Order Status')]//ancestor::div[1]//following-sibling::span[1][contains(text(),'Resend')]"),
	ORDERING_BO_GENERAL_INFOMATION_TAB_ID("generalInfoTabId"),	
	ORDERING_BO_QUEUES_QUEUELABEL_XPATH("//h1[@class='title']"),
	ORDERING_BO_QUEUES_QUEUELABEL_VALUE("Queues"),
	ORDERING_BO_QUEUES_INSURANCE_LABEL_XPATH("//h1[@class='subtitle']"),
	ORDERING_BO_QUEUES_INSURANCE_LABEL_VALUE("- Insurance"),
	ORDERING_BO_QUEUES_PROJECT_LABEL_VALUE("- Project"),
	ORDERING_BO_QUEUES_PROJECT_LABEL_XPATH("//h1[@class='subtitle']"),
	ORDERING_BO_QUEUES_PROJECT_ADDPROJECT_LABEL_VALUE("Add Project"),
	ORDERING_BO_QUEUES_PROJECT_ADDPROJECT_LABEL_XPATH("//a[@class='addProjectBtn pull-right']"),
	ORDERING_BO_QUEUES_BILLING_QUEUES_OPTION_XPATH("//div[@id='queues']/h1[contains(text(),'Queues')]"),
	ORDERING_BO_QUEUES_BILLING_QUEUES_BILLING_OPTION_XPATH("//div[@id='queues']/h1[contains(text(),'Billing')]"),
	ORDERING_BO_QUEUES_QUEUES_CREDIT_OPTION_XPATH("//div[@id='queues']/h1[contains(text(),'Queues')]"),
	ORDERING_BO_QUEUES_QUEUES_CREDIT_QUEUES_OPTION_XPATH("//div[@id='queues']/h1[contains(text(),'Credit')]"),
	ORDERING_BO_QUEUES_QUEUES_DEALER_OPTION_XPATH("//div[@id='queues']/h1[contains(text(),'Queues')]"),
	ORDERING_BO_QUEUES_QUEUES_DEALER_QUEUES_OPTION_XPATH("//div[@id='queues']/h1[contains(text(),'Dealer')]"),
	ORDERING_LABEL_BACKOFFICE_QUEUES_XPATH("//span[contains(text(),'Queues')]"),
	ORDERING_LABEL_BACKOFFICE_EDITORDER_XPATH("//span[contains(text(),'Edit Order')]"),
	ORDERING_LABEL_BACKOFFICE_MANAGER_ORDER_PREFERENCES_XPATH("//span[contains(text(),'Manager Order Preferences')]"),
	ORDERING_LABEL_BACKOFFICE_CODESTABLES_XPATH("//span[normalize-space()='Codes Tables']"),
	ORDERING_LABEL_BACKOFFICE_BATCHPROCESSING_XPATH("//span[contains(text(),'Batch Processing')]"),
	ORDERING_LABEL_BACKOFFICE_BUSINESSMAINTAINEDTABLES_XPATH("//span[normalize-space()='Business Maintained Tables']"),
	ORDERING_LABEL_BACKOFFICE_QUEUES_VALUE("Queues"), 
	ORDERING_LABEL_BACKOFFICE_EDITORDER_VALUE("Edit Order"),
	ORDERING_LABEL_BACKOFFICE_MANAGERORDERPREFERENCES_VALUE("Manager Order Preferences"),
	ORDERING_LABEL_BACKOFFICE_CODESTABLES_VALUE("Codes Tables"),
	ORDERING_LABEL_BACKOFFICE_BATCHPROCESSING_VALUE("Batch Processing"),
	ORDERING_LABEL_BACKOFFICE_BUSINESSMAINTAINEDTABLES_VALUE("Business Maintained Tables"),
	ORDERING_BO_QUEUES_SAVEBUTTON_XPATH("//a[@class='saveBtn pull-right']"),
	ORDERING_BO_QUEUES_EXPORTBUTTON_XPATH("//a[@class='exportExcelBtn pull-right']"),
	ORDERING_BO_QUEUES_ADDREMOVEBUTTON_XPATH("//a[@class='addRemoveBtn pull-right']"),
	ORDERING_BO_QUEUES_SAVEBUTTON_VALUE("Save"),
	ORDERING_BO_QUEUES_EXPORTBUTTON_VALUE("Export"),
	ORDERING_BO_QUEUES_ADDREMOVEBUTTON_VALUE("Add/Remove"),
	ORDERING_BO_QUEUES_BILLING_QUEUES_OPTION_VALUE("Queues- Billing"),
	ORDERING_BO_QUEUES_QUEUES_CREDIT_OPTION_VALUE("Queues- Credit"),
	ORDERING_BO_QUEUES_QUEUES_DEALER_OPTION_VALUE("Queues- Dealer"),
	ORDERING_BO_ORDER_SEARCH_FIELDS_LABEL_XPATH("//section[@id='%s']//label"),
	ORDERING_BO_ORDER_SEARCH_FIELDS_VALUE_XPATH("//section[@id='%s']//label[text()='%s']/..//input"),
	ORDERING_BO_SEARCHED_RECORDS_RESULT_XPATH("//table[@id='queue-table']//td[@data-name='%s']"),
	ORDERING_BO_SEARCHED_ROCORDS_ROW_XPATH("//table[@id='queue-table']//tbody//tr"),
	ORDERING_BO_OOQ_SEARCHICON_CSS("div.btn.green.btn-shared.search"),
	ORDERING_BO_QUEUES_RELEASE_BUTTON_DISABLED_XPATH("//span[text()='Release']//parent::div[contains(@class, 'disabled')]"),
	ORDERING_BO_QUEUES_SEARCH_FIELD_XPATH("//section[@id='standard']//label[text()='%s']//parent::div//input[@type='text']"),
	ORDERING_BO_QUEUES_CLEAR_FILTER_BUTTON_CSS("div.btn.green.btn-shared.clear-filters"),
	ORDERING_BO_QUEUES_TOGGLE_COLUMN_BUTTON_XPATH("//span[text()='Toggle Columns']//parent::button"),
	ORDERING_BO_QUEUES_EXPORT_BUTTON_CSS("div.btn.blue.btn-shared.queue-export"),
	ORDERING_BO_UPFIT_SPEC_EXPORT_BUTTON_CSS("button.btn.exportExcel.dropdown-toggle"),
	ORDERING_BO_QUEUES_TOGGLE_ACTIVE_COLUMN_LABEL_XPATH("//button//span[text()='Toggle Columns']/../..//li[@class='active']//label"),
	ORDERING_BO_QUEUES_TABLE_COLUMN_NAMES_XPATH("//div[@id='queue-table_wrapper']//div[@class='dataTables_scrollHeadInner']//th[not(contains(@style,'none'))]"),
	ORDERING_BO_QUESE_ADD_REMOVE_COMLUMN_XPATH("//label[contains(text(),'%s')]/..//parent::li"),
	ORDERING_BO_QUEUES_TABLE_SORTING_COLUMN_NAME_XPATH("//div[@id='queue-table_wrapper']//th[text()='%s']"),
	ORDERING_BO_OOQ_NEXTPAGINATEBTN_XPATH("//span[@id='queue-table_next']"),
	ORDERING_BO_OOQ_LASTPAGINATEBTN_XPATH("//span[@id='queue-table_last']"),
	ORDERING_BO_OOQ_PAGINATEPAGETXT_XPATH("//span[@class='paginate_page']"),
	ORDERING_BO_OOQ_PAGINATEOFTXT_XPATH("//span[@class='paginate_of']"),
	ORDERING_BO_OOQ_PREVIOUSPAGINATEBTN_XPATH("//span[@id='queue-table_previous']"),
	ORDERING_BO_OOQ_FIRSTPAGINATEBTN_XPATH("//span[@id='queue-table_first']"),
	ORDERING_BO_OOQ_RECORDSIZE_DRPDWN_XPATH("//select[@name='queue-table_length']//child::option"),
	ORDERING_BO_QUEUES_ADDREMOVEBTN_XPATH("//a[@class='addRemoveBtn pull-right']"),
	ORDERING_BO_QUEUES_TABLECOLUMNLISTNAME_XPATH("(//table[@class='table datatable queue-table dataTable no-footer'])[1]//following-sibling::tr//th[not(contains(@style,'display: none'))]"),
	ORDERING_BO_QUEUES_ADDREMOVELIST_XPATH("//div[@class='listContainer dropdown-menu drpdwnCol']//label"),
	ORDERING_BO_QUEUES_CONTROLSLINK_XPATH("//div[@id='filterControlsBlock']//span[contains(text(),'Filters')]"),
	ORDERING_BO_QUEUES_OPTIONS_XPATH("//a[@data-f-name='%s']"),
	ORDERING_BO_QUEUES_OPTIONSEARCH_XPATH("//a[@data-f-name='%s']//following::input[1]"),
	ORDERING_BO_QUEUES_ARIAMULTISELECTABLE_XPATH("//div[@id='filter-content-accordion']"),
	ORDERING_BO_QUEUES_CONTROLS_APPLY_XPATH("//div[@class='buttonSet']//following::button[contains(text(),'Apply')]"),
	ORDERING_BO_QUEUES_CLOSECROSS_XPATH("//a[@title='Close']"),
	ORDERING_BO_QUEUES_SAVEAS_XPATH("//a[@title='Save As']"),
	ORDERING_BO_QUEUES_SAVEVIEW_XPATH("//a[@class='saveBtn pull-right']"),
	ORDERING_BO_QUEUES_INPUTNAME_XPATH("//input[@placeholder='Type in Name']"),
	ORDERING_BO_QUEUES_SAVEASOK_XPATH("//button[@class='btnSaveAsOk']"),
	ORDERING_BO_QUEUES_VIEWDRPDWN_XPATH("//button[@id='btnDropdownViews']"),
	ORDERING_BO_QUEUES_VIEWLIST_XPATH("//ul[@id='ulordertableCols']//child::label"),
	ORDERING_BO_OOQ_PAGESIZE_DRPDWN_XPATH("//select[@name='queue-table_length']"),
	ORDERING_BO_EDIT_ORDER_XPATH("//span[contains(text(),'Edit Order')]"),
	ORDERING_BO_EDIT_ORDER_MAINTENANCE_XPATH("//span[contains(text(),'Order Maintenance')]"),
	ORDERING_BO_EDIT_ORDER_SMART_SEARCH_XPATH("//div[@id='smart-search']//input[1]"),
	ORDERING_BO_EDIT_ORDER_SMART_SEARCH_SELECT_XPATH("//strong[contains(text(),'#LogNumber$')]"),
	ORDERING_BO_QUEUES_SEARCH_FIELDS_ELEMENT_LIST_XPATH("//div[contains(@class,'filter-field')]"),
	ORDERING_BO_QUEUES_COLUMNNAME_XPATH("//th[contains(text(),'%s')]"),
	ORDERING_BO_QUEUES_BUTTON_TOGGLE_XPATH("//span[@class='multiselect-selected-text']"),
	ORDERING_BO_QUEUES_BUTTON_SEARCH_XPATH("//div[@class='btn green btn-shared search loading']"),
	ORDERING_BO_QUEUES_BUTTON_CLEAR_XPATH("//div[@class='btn green btn-shared clear-filters']"),
	ORDERING_BO_QUEUES_BUTTON_EXPORT_XPATH("//div[@class='btn blue btn-shared queue-export']']"),
	ORDERING_BO_QUEUES_BUTTON_RELEASEGRAY_XPATH("//div[@class='btn custom-action green btn-shared releaseOrder disabled']"),
	ORDERING_BO_QUEUES_TITLE1_XPATH("//h1[@class='title']"),
	ORDERING_BO_QUEUES_SUBTITLE_XPATH("//h1[@id='queue-page-title']"),
	ORDERING_BO_QUEUES_STANDARD_SEARCH_FIELDS_XPATH("//section[@id='standard']//div[contains(@class,'filter-field')]"),
	ORDERING_BO_QUEUES_ADVANCED_SEARCH_FIELDS_XPATH("//section[@id='advanced']//div[contains(@class,'filter-field')]"),
	ORDERING_BO_QUEUES_LOG_COLUMN_TABLE_DATA_XPATH("//div[@id='queue-table_wrapper']//div[@class='dataTables_scrollBody']//td[@data-name='logNumber']"),
	ORDERING_BO_QUEUES_UNIT_COLUMN_TABLE_DATA_XPATH("//div[@id='queue-table_wrapper']//div[@class='dataTables_scrollBody']//td[@data-name='unitNumber']"),
	ORDERING_BO_QUEUES_FACTORY_ORDER_DATE_COLUMN_TABLE_DATA_XPATH("//div[@id='queue-table_wrapper']//div[@class='dataTables_scrollBody']//td[@data-name='foDate']"),
	ORDERING_BO_QUEUES_CLIENT_COLUMN_TABLE_DATA_XPATH("//div[@id='queue-table_wrapper']//div[@class='dataTables_scrollBody']//td[@data-name='clientNumber']"),
	ORDERING_BO_QUEUES_UPFITSPEC_ID_COLUMN_HEADER_XPATH("//div[@class='dataTables_scrollHead']//th[@data-name='upfitSpecID']"),
	ORDERING_BO_QUEUES_UPFITSPEC_ID_COLUMN_TABLE_DATA_XPATH("//div[@id='queue-table_wrapper']//div[@class='dataTables_scrollBody']//td[@data-name='upfitSpecID']"),
	ORDERING_BO_QUEUES_QUOTE_ID_COLUMN_HEADER_XPATH("//div[@class='dataTables_scrollHead']//th[@data-name='quoteId']"),
	ORDERING_BO_QUEUES_CREATED_BY_COLUMN_HEADER_XPATH("//div[@class='dataTables_scrollHead']//th[@data-name='createdBy']"),
	ORDERING_BO_QUEUES_QUOTE_ID_COLUMN_TABLE_DATA_XPATH("//div[@id='queue-table_wrapper']//div[@class='dataTables_scrollBody']//td[@data-name='quoteId']"),
	ORDERING_BO_QUEUES_CREATED_BY_COLUMN_TABLE_DATA_XPATH("//div[@id='queue-table_wrapper']//div[@class='dataTables_scrollBody']//td[@data-name='createdBy']"),
	ORDERING_BO_QUEUES_CORP_COLUMN_HEADER_XPATH("//div[@class='dataTables_scrollHead']//th[@data-name='corpCode']"),
	ORDERING_BO_QUEUES_CORP_COLUMN_TABLE_DATA_XPATH("//div[@id='queue-table_wrapper']//div[@class='dataTables_scrollBody']//td[@data-name='corpCode']"),
	ORDERING_BO_BUSINESS_MAINTAINED_TABLE_XPATH("//a[@href='#businessTables']//span"),
	ORDERING_BO_QUEUES_APPROVAL_STATUS_COLUMN_VALUES_XPATH("//table[@id='queue-table']//tr//td[@data-name='status']"),
	ORDERING_BO_QUEUES_TELEMATICS_XPATH("//div[@id='queues']//div[@data-target='TLQ']"),
	ORDERING_BO_QUEUES_UPFIT_PROJECT_XPATH("//div[@id='queues']//div[@data-target='UFPQ']"),
	ORDERING_BO_QUEUES_CORP_CDDR_COLUMN_HEADER_XPATH("//div[@class='dataTables_scrollHead']//th[@data-name='corp']"),
	ORDERING_BO_QUEUES_FLEET_ID_CDDR_COLUMN_HEADER_XPATH("//div[@class='dataTables_scrollHead']//th[@data-name='fleet']"),	
	ORDERING_BO_QUEUES_CORP_CDDRTABLE_DATA_COLUMN_HEADER_XPATH("//div[@id='queue-table_wrapper']//div[@class='dataTables_scrollBody']//td[@data-name='corp']"),
	ORDERING_BO_QUEUES_FLEET_ID_CDDRTABLE_DATA_COLUMN_HEADER_XPATH("//div[@id='queue-table_wrapper']//div[@class='dataTables_scrollBody']//td[@data-name='fleet']"),
	ORDERING_BO_QUEUES_CLOSE_XPATH("//h2[contains(text(), 'Show/Hide Columns')]/a[@title='Close']"),
    ORDERING_BO_QUEUES_SELECTSTATUS_XPATH("(//button[@class='multiselect dropdown-toggle btn btn-default']//span[@class=\"multiselect-selected-text\"])[2]"),
	ORDERING_BO_QUEUES_SELECTALL_XPATH("(//input[@value='multiselect-all'])[2]"),
	ORDERING_BO_QUEUES_SELECT_UPFITPENDING_XPATH("(//input[@value='UPPN'])[1]"),
	ORDERING_BO_QUEUES_SEARCH_UPFITPENDING_XPATH("//button[@id='search-by-filters-btn']"),
	ORDERING_BO_QUEUES_SELECTED_ROW_UPFITPENDING_XPATH("(//tr[@class='data-table__row odd'])[1]"),
	ORDERING_BO_QUEUES_CLIENTNUMBER_XPATH("//input[@id='clientNumber-input']"),
	ORDERING_BO_QUEUES_UPFITTING_XPATH("//a[text()='Upfitting']"),
	ORDERING_BO_VEHICLECONFIG_ASSOCIATEUPFIT_XPATH("//a[text()='Associated Upfits']"),
	ORDERING_BO_VEHICLECONFIG_ADDASSOCIATION_XPATH("//button[@id='add-association']"),
	ORDERING_BO_VEHICLECONFIG_SELECTASSOCIATION_XPATH("//select[@id='select-association']"),
	ORDERING_BO_VEHICLECONFIG_ACCORDIONMESSAGE_XPATH("//div[@class='empty-alert-message']"),
	ORDERING_BO_VEHICLECONFIG_SAVE_QUOTE_XPATH("//button[text()='Save']"),
	ORDERING_BO_VEHICLECONFIG_CHKBOX_QUOTE_XPATH("//div[@class='left-controls-group']/input"),
	ORDERING_BO_VEHICLECONFIG_NOTIFICATION_MESSAGE_XPATH("//div[@class='noty-msg x-style']"),
	ORDERING_BO_VEHICLECONFIG_REQUIREDSLIDER_XPATH("(//span[@class='slider round'])[1]"),
	ORDERING_BO_UPFIT_PROJECT_CREATE_RFQ_NOTIFICATION_XPATH("//div[@class='noty-msg x-style']"),
	ORDERING_BO_VEHICLECONFIG_QUOTENAME_SELECTED_XPATH("//div[@class='label-p-group quote-name']/p"),
	ORDERING_BO_VEHICLECONFIG_SCROLL_BULKACTION_XPATH("//label[text()='Bulk Actions']"),
	ORDERING_BO_QUEUES_UPFIT_PROJECT_OPTION_XPATH("//div[@id='queues']//div[@data-target='UFPQ']"),
	ORDERING_BO_QUEUES_AGING_DAYS_LABEL_IN_SEARCH_XPATH("//input[@name='agingSearch']//following-sibling::label"),
	ORDERING_BO_QUEUES_AGING_DAYS_LABEL_IN_TOGGLE_COLUMN_XPATH("//label[@title='Days Aging']"),
	ORDERING_BO_QUEUES_CLIENT_COLUMN_DATA_LIST_XPATH("//td[@data-name='clientNumber']"),
	ORDERING_BO_QUEUES_CLIENT_SEARCH_XPATH("//input[@name='clientNumber']"),
	ORDERING_BO_QUEUES_UNIT_SEARCH_XPATH("//input[@name='unitNumber']"),
	ORDERING_BO_QUEUES_UNIT_COLUMN_DATA_LIST_XPATH("//td[@data-name='unitNumber']"),
	ORDERING_BO_QUEUES_DAYS_AGING_COLUMN_DATA_LIST_XPATH("//td[@data-name='aging']"),

	;

	private String value;

	OrderingBOQueuePageEnum(String value) {
		this.value = value;
	}

	public String getValue() {
		return value;
	}

	@Override
	public String toString() {
		return value;
	}

}
