package com.element.fleet.ordering.enums;

public enum OrderingVehicleConfigFleetSpecsPageEnum {

	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_PAGE_ID("searchHeading"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_PAGE_ADD_NEW_BUTTON_XPATH("//a[contains(text(),'Add New')]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_PAGE_MAKE_TEXTBOX_XPATH("//select[@name='fromScratch[vcle__make]']//following-sibling::span//input"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_PAGE_MODEL_TEXTBOX_XPATH("//select[@name='fromScratch[vcle__modelDesc]']//following-sibling::span//input"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_SELECT_VEHICLE_FIRST_SEARCH_CSS("#scratch-table > tbody > tr:nth-child(1)"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_SELECT_INTERIOR_COLOR_XPATH("//div[contains(text(),'INTERIOR COLORS')]//following::ul[1]//li[1]//input"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_SELECT_PRIMARY_COLOR_XPATH("//div[contains(text(),'PRIMARY COLORS')]//following::ul[1]//li[1]//input"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_SAVE_BUTTON_XPATH("//a[@id='spec-btn-save-list']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_NAME_TEXTBOX_ID("conf-save-name"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_NOTES_TEXTAREA_XPATH("//textarea[@id='conf-save-note']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_ACCEPT_BUTTON_ID("modal-accept-btn"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_ACCEPT_BUTTON_XPATH("//button[@id='modal-accept-btn']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_CANCEL_BUTTON_ID("modal-close-btn"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_SEARCH_BUTTON_XPATH("//button[@id='search-by-filters-btn']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_ROWS_CSS("table#specs-queue-table > tbody > tr"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_SELECT_FIRST_AFTER_SEARCH_CSS("div.DTFC_LeftWrapper > div.DTFC_LeftBodyWrapper table.specs-data-table > tbody > tr label.data-table__checkbox-label"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_ROW_COLUMNS_XPATH("//table[@id='specs-queue-table']//tbody//tr[1]/td[position]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_CLIENT_APPROVE_BUTTON_ID("btnApproveClient"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_ELEMENT_APPROVE_BUTTON_ID("btnApprove"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_ACTION_LINK_XPATH("//a[@class='spec-actions btn btn-neutral']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_UPFIT_PENDING_STATUS_XPATH("//li[contains(text(),'Upfit Pending')]"),
	ORDERING_PRICE_AND_CONFIG_ACTION_CONVERT_TO_ORDER_XPATH("//li[contains(text(),'Convert To Order')]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_TABLE_ROW_XPATH("//table[@id='specs-queue-table']/tbody/tr"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_CANCEL_BUTTON_CSS("div.pull-right.btn.cancel.configurator-cancel"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_CONFIRM_CANCEL_BUTTON_CSS("button#leaveUnlock"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_CREATE_PDF_BUTTON_ID("spec-btn-export"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_OPEN_FIRST_FOR_PDF_XPATH("//table[@id='specs-table']//tbody//tr[1]//td[3]"),
	ORDERING_VEHICLE_BUILD_FROM_SCRATCH_YEAR_DROPDOWN_BUTTON_XPATH("//label[@class='from-scratch-field'][contains(text(),'Year')]//following::div//button[@class='multiselect dropdown-toggle btndropdown btn btn-default']"),
	ORDERING_VEHICLE_BUILD_FROM_SCRATCH_YEAR_DROPDOWN_XPATH("//label[@class='from-scratch-field'][contains(text(),'Year')]//following::div//ul//label[@class='radio']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_SELECT_2SPEAKERRADIO_OTHERS_XPATH("//a[contains(text(),' 2-Speaker Radio Prep Package ')]//parent::*//parent::*//following::input[@id='58F']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_WORK_IN_PROCESS_XPATH("//td[contains(text(),\"Work In Process\")]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_WORK_IN_PROCESS_VALUE("Work In Process"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_UPFIT_PENDING_XPATH("//td[contains(text(),\"Upfit Pending\")]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_UPFIT_PENDING_VALUE("Upfit Pending"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_ELEMENT_APPROVED_XPATH("//td[contains(text(),\"Element Approved\")]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_ELEMENT_APPROVED_VALUE("Element Approved"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_CLIENT_APPROVED_XPATH("//td[contains(text(),\"Client Approved\")]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_CLIENT_APPROVED_VALUE("Client Approved"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_COPY_FLEET_SPECS_XPATH("//li[contains(text(), 'Copy Fleet Spec')]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_COPYFLEETSPECS_TOCLIENTNUMBER_XPATH("//input[@id='spec-copy-to-client']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_COPYFLEETSPECS_FLEETSPECNAME_XPATH("//input[@id='conf-save-name']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_COPYFLEETSPECS_COPYNOTE_XPATH("//textarea[@id='conf-save-note']"),
	ORDERING_PRICE_AND_CONFIG_EDIT_XPATH("//a[@id='row-action-edit-0']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_EDIT_INTERIOR_COLOR_XPATH("//div[contains(text(),'INTERIOR COLORS')]//following::ul[2]//li[1]//input"),
	ORDERING_VEHICLE_CONFIG_MODEL_ACCEPT_ID("modal-accept-btn"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_EDIT_ACCEPT_BUTTON_XPATH("//label[contains(text(),'Save Price and Configuration As')]//following::button[@id='modal-accept-btn']"),
	ORDERING_VEHICLE_CONFIG_PRICE_CONFIG_TOGGLE_IMAGE_BUTTON_VALUE_CSS("button.btn.spec-toggle.toggleImg"),
	ORDERING_VEHICEL_CONFIG_PRICE_CONFIG_IMAGE_COLUMN_XPATH("//th[contains(text(),'Image')]"),
	ORDERING_VEHICLE_CONFIG_PRICE_CONFIG_EXPORT_BUTTON_VALUE_XPATH("//div[@id='spec-list-specs']//a[text()='Export']"),
	ORDERING_VEHICLE_COPY_PRICE_CONFIG_BUTTON_VALUE_XPATH("//li[contains(text(),' Copy Price & Config')]"),
	ORDERING_VEHICLE_PRICE_AND_CONFIG_CONVERT_TO_FLEETSPEC_XPATH("//li[contains(text(),' Convert To Fleet Spec')]"),
	ORDERING_VEHICLE_PRICE_AND_CONFIG_EXPORT_XPATH("//li[contains(text(),' Export to PDF/Print')]"),
	ORDERING_VEHICLE_COPY_PRICE_AND_CONFIG_CLIENT_NUMBER_ID("spec-copy-to-client"),
	ORDERING_VEHICLE_PRICE_AND_CONFIG_FLEET_SPECS_NAME_TEXTBOX_ID("spec-copy-name"),
	ORDERING_VEHICLE_PRICE_AND_CONFIG_FLEET_SPECS_NOTES_TEXTAREA_ID("spec-copy-note"),
	ORDERING_VEHICLE_PRICE_AND_CONFIG_NAME_XPATH("//table[@id='specs-table']//td[8]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_EDIT_ACCEPT_BUTTON_CSS("div#specs-copy.modal.fade.in button#modal-accept-btn"),
	ORDERING_VEHICLE_PRICE_AND_CONFIG_ACTIONS_CHECKBOX_ROW1_XPATH("//table[@id='specs-table']/tbody/tr[1]/td/input[@type='checkbox']"),
	ORDERING_VEHICLE_PRICE_AND_CONFIG_ARCHIEVE_BTN_ID("btnArchive"),
	ORDERING_VEHICLE_PRICE_AND_CONFIG_UNARCHIEVE_BTN_ID("btnUnArchive"),
	ORDERING_VEHICLE_PRICE_AND_CONFIG_STATUS_ROW1_XPATH("//table[@id='specs-table']/tbody/tr[1]/td[4]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_ACTIONS_OK_BUTTON_ID("modal-ok-btn"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_ACTIONS_CANCEL_BUTTON_ID("modal-close-btn"),
	ORDERING_VEHICLE_PRICE_AND_CONFIG_CLIENT_NUMBER_ID("spec-client-number"),
	ORDERING_VEHICLE_CONFIG_PRICE_CONFIG_ID_COLUMN_TABLE_DATA_XPATH("//div[@id='spec-list-specs']//div[@class='dataTables_scrollBody']//td[@data-spec-id]"),
	ORDERING_VEHICLE_CONFIG_PRICE_CONFIG_DATE_COLUMN_TABLE_DATA_XPATH("//div[@id='spec-list-specs']//div[@class='dataTables_scrollBody']//td[14]"),
	ORDERING_VEHICLE_CONFIG_PRICE_CONFIG_DATE_COLUMN_TABLE_HEADING_XPATH("//th[text()='Last Updated Date']") ,
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_FLEET_SPEC_ID_COLUMN_HEADING_XPATH("//th[contains(text(),'columnHeading')]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_SEARH_FIELDS_XPATH("//p[contains(text(),'%s')]//following::input[1]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_SEARCHED_ROWS_XPATH("//table[@id='specs-table']//tbody//tr"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_CLEAR_FILTERS_XPATH("//button[@id='clear-all-filters-btn']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_SEARCHED_ROWS_RESULT_XPATH("//table[@id='specs-table']/tbody/tr/td[contains(text(),'%s')]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_CLIENT_NUMBER_TEXTFIELD_ID("clientNumber-input"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_NAME_SEARCH_ID("specName-input"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_ID_SEARCH_ID("businessAccessKey-input"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_CREATED_BY_TEXTFIELD_ID("unitSpecLastUpdatedBy-input"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_STATUS_DROPDOWN_CSS("select#js-specStatusCode-multi-select + div,multiselect-wrapper > button"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_STATUS_DROPDOWN_SEARCH_FIELD_CSS("#search-filters div.table-filters__field.field-specStatusCode li.multiselect-item.multiselect-filter input"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_STATUS_DROPDOWN_SEARCH_FIELD_SELECT_DIPLAYED_CSS("ul > li[style='display: block;']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_ID("businessAccessKey-input"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_REVISION_NUMBER_ID("specVersion-input"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_YEAR_DROPDOWN_CSS("select#js-unitYear-multi-select + div,multiselect-wrapper > button"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_MAKE_ID("unitMake-input"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_MODEL_ID("unitModel-input"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_MODEL_CODE_ID("unitModel-input"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_TRIM_ID("unitTrim-input"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_VEHICLE_TABLE_ID("scratch-table_wrapper"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_SELECT_SEARCHED_VEHICLE_XPATH("//div[@id='scratch-table_wrapper']//td[text()='%s']//following-sibling::td[text()='%s']//following-sibling::td[text()='%s']//following-sibling::td[contains(text(), '%s')]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_OPTION_CODE_ID("unitOptionCode-input"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_VEHICLE_OPTION_DESCRIPTION_ID("unitOptionDescription-input"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_CREATE_FROM_DATE_ID("specDateSearchSTART1-input"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_CREATE_TO_DATE_ID("specDateSearchEND2-input"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_STATUS_FROM_DATE_ID("effDateSTART7-input"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_STATUS_TO_DATE_ID("effDateEND8-input"),
	ORDERING_VEHICLE_CONFIG_TABLE_HEADINGS_CSS("div#specs-table_wrapper.dataTables_wrapper div.dataTables_scrollHead th"),
	ORDERING_VEHICLE_CONFIG_TABLE_COLUMN_DATA_ROW_CSS("table#specs-table > tbody > tr"),
	ORDERING_VEHICLE_CONFIG_TABLE_COLUMN_DATA_CSS("table#specs-table > tbody > tr >td:nth-child(number)"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_OPTIONS_CSS("ul.context-menu-list.context-menu-root:not(.bulk-actions-customs) li:not(.context-menu-disabled).context-menu-icon-updated"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_DOWNLOAD_PDF_POP_UP_CSS("div.new-success-modal"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_DOWNLOAD_PDF_POP_UP_CURRENT_COUNT_ID("currentPdfCount"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_DOWNLOAD_PDF_POP_UP_TOTAL_COUNT_ID("totalPdfCount"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_PAGE_TRIM_TEXTBOX_XPATH("//select[@name='fromScratch[make]']//following-sibling::span//input"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_PAGE_FUEL_TYPE_TEXTBOX_XPATH("//select[@name=' ' and @id='fuelType']//following-sibling::span//input"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_PAGE_TRACTION_TEXTBOX_XPATH("//select[@name=' ' and @id='driveType']//following-sibling::span//input"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_PAGE_PRICE_CONFIG_LABEL_XPATH("//label[contains(text(),'Save Price and Configuration As')]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_PAGE_SAVE_CLIENT_LABEL_XPATH("//label[contains(text(),'To Client Number')]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_PAGE_NOTES_LABEL_XPATH("//label[contains(text(),'Price and Configuration Notes')]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_DISABLEOPTIONS_CLASS("context-menu-item context-menu-disabled context-menu-icon-updated"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_RED_INSTRUCTIONS_CLASS("note_desc"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_OPTIONS_NOTES_CLASS("ext-desc"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_BASE_INVOICE_XPATH("//td[contains(text(),'Base Invoice:')]"),	
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_BASE_MSRP_XPATH("//td[contains(text(),'Base MSRP:')]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_OPTIONS_INVOICE_XPATH("//td[contains(text(),'Options Invoice:')]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_OPTIONS_MSRP_XPATH("//td[contains(text(),'Options MSRP:')]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_INVOICE_XPATH("//div[@class='vehicle-configurator-wrapper active']//tr[5]//td[1]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_MSRP_XPATH("//div[@class='vehicle-configurator-wrapper active']//tr[6]//td[1]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_DESTINATION_FEE_XPATH("//td[contains(text(),'Destination Fee:')]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_FLEET_NAME_XPATH("//label[@class='unitInfo__makeNModel']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_VEHICLE_IMAGE_XPATH("//div[@id='vehicle__ext_carousel']//div[@class='item active']//img[@class='imageOnTheFly']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_CANCEL_BUTTON_XPATH("//div[@class='pull-left btn cancel configurator-cancel']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_ACTION_BUTTON_XPATH("//tr[1]//td[2]//a[1]"),
	ORDERING_FLEET_SPEC_STANDARD_EQUIPMENT_XPATH("//div[@id=\"optionsListOfSpecs\"]/div[2]/p/button"),
	ORDERING_FLEET_SPEC_STANDARD_EQUIPMENT_TABLE1_XPATH("//thead//th[contains(text(),'Powertrain')]"),
	ORDERING_FLEET_SPEC_NOTES1_XPATH("(//div[@class='desciption'])[1]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_ADVANCED_SEARCH_BUTTON_ID("toggle-advanced"),
	ORDERING_VEHICLE_CONFIG_TABLE_COLUMN_DATA_ACTION_XPATH("//button[@class='text-button text-button--overflow js-row-menu-button']"),	
	ORDERING_VEHICLE_CONFIG_SPEC_SAVE_DROPDOWN_ID("dropdown-menu-save"),
	ORDERING_VEHICLE_CONFIG_SPEC_SAVE_BUTTON_XPATH("//button[@id='spec-btn-save']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_SAVE_AS_BUTTON_XPATH("//a[@id='spec-btn-save-as-list']"),
	ORDERING_PRICE_AND_CONFIG_INDIVIDUAL_ACTION_MENU_ID("row-action-export-0"),
	ORDERING_PRICE_AND_CONFIG_EXPORT_TO_PDF_XPATH("//a[@id='row-action-export-pdf-0']"),
	ORDERING_PRICE_AND_CONFIG_EXPORT_TO_EXCEL_XPATH("//a[@id='row-action-export-excel-0']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_EXPORT_PDF_MOEDL_POPUP_ID("reset-form-pdf"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_EXPORT_PDF_CLIENT_VIEW_XPATH("//span[contains(text(),'Client View')]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_EXPORT_PDF_CLIENT__STD_NET_EQUIPMENT_CHECKBOX_XPATH("//div[@class='client-view-selected show']//input[@name='equipment']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_EXPORT_PDF_CLIENT__STD_NET_EQUIPMENT_CHECKBOX_TEXT_XPATH("//div[@class='client-view-selected show']//input[@name='equipment']//parent::span"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_EXPORT_PDF_CLIENT_FEES_CHECKBOX_XPATH("//input[@name='fees']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_EXPORT_PDF_CLIENT_FEES_CHECKBOX_TEXT_XPATH("//input[@name='fees']//parent::span"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_EXPORT_PDF_CLIENT_INVOICE_CHECKBOX_XPATH("//div[@class='clientCheckboxWithoutNet show']//input[@value='Invoice Pricing']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_EXPORT_PDF_CLIENT_INVOICE_CHECKBOX_TEXT_XPATH("//div[@class='clientCheckboxWithoutNet show']//input[@value='Invoice Pricing']//parent::span"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_EXPORT_PDF_EXPORT_BUTTON_XPATH("//button[contains(text(),'Export')]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_EXPORT_PDF_EXPORT_COMPLETE_POPUP_XPATH("//span[contains(text(),'Exporting complete')]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_EXPORT_PDF_EXPORT_SUCESS_MESSAAGE1_ID("pdfmsg3Success"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_EXPORT_PDF_DRIVER_VIEW_XPATH("//span[contains(text(),'Driver View')]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_EXPORT_PDF_DRIVER__STD_NET_EQUIPMENT_CHECKBOX_XPATH("//div[@class='driver-view-selected show']//input[@name='equipment']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_EXPORT_PDF_DRIVER__STD_NET_EQUIPMENT_CHECKBOX_TEXT_XPATH("//div[@class='driver-view-selected show']//input[@name='equipment']//parent::span"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_EXPORT_PDF_DRIVER_INVOICE_CHECKBOX_ID("invoice-driver"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_EXPORT_PDF_DRIVER_INVOICE_CHECKBOX_TEXT_XPATH("//input[@id='invoice-driver']//parent::span"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_EXPORT_PDF_DRIVER_MSRP_CHECKBOX_ID("msrp-driver"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_EXPORT_PDF_DRIVER_MSRP_CHECKBOX_TEXT_XPATH("//input[@id='msrp-driver']//parent::span"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_EXPORT_PDF_PRICING_VIEW_XPATH("//span[contains(text(),'Pricing View')]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_EXPORT_PDF_PRICING__STD_NET_EQUIPMENT_CHECKBOX_XPATH("//div[@class='pricing-view-selected show']//input[@value='equipment']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_EXPORT_PDF_PRICING__STD_NET_EQUIPMENT_CHECKBOX_TEXT_XPATH("//div[@class='pricing-view-selected show']//input[@value='equipment']//parent::span"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_EXPORT_PDF_PRICING_FEES_CHECKBOX_XPATH("//div[@class='pricing-view-selected show']//input[@value='fees']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_EXPORT_PDF_PRICING_FEES_CHECKBOX_TEXT_XPATH("//div[@class='pricing-view-selected show']//input[@value='fees']//parent::span"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_EXPORT_PDF_PRICING_INVOICE_CHECKBOX_XPATH("//div[@class='pricing-view-selected show']//div[@class='pricingCheckboxWithoutNet show']//input[@value='Invoice Pricing']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_EXPORT_PDF_PRICING_INVOICE_CHECKBOX_TEXT_XPATH("//div[@class='pricing-view-selected show']//div[@class='pricingCheckboxWithoutNet show']//input[@value='Invoice Pricing']//parent::span"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_EXPORT_PDF_PRICING_MSRP_CHECKBOX_XPATH("//div[@class='pricing-view-selected show']//div[@class='pricingCheckboxWithoutNet show']//input[@value='MSRP Pricing']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_EXPORT_PDF_PRICING_MSRP_CHECKBOX_TEXT_XPATH("//div[@class='pricing-view-selected show']//div[@class='pricingCheckboxWithoutNet show']//input[@value='MSRP Pricing']//parent::span"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_EXPORT_PDF_CANCEL_POPUP_ID("back-Btn-Selection-Click"),
	ORDERING_VEHICLE_CONFIG_PRICE_AND_CONFIG_SPEC_EXPORT_PDF_CLIENT_VIEW_ALL_AVAILABEL_OPTIONS_CHECKBOX_XPATH("//span[@id='client-view-prso']//input[@value='allOptionsAvailable']"),
	ORDERING_VEHICLE_CONFIG_PRICE_AND_CONFIG_SPEC_EXPORT_PDF_CLIENT_VIEW_ALL_AVAILABEL_OPTIONS_TEXT_XPATH("//span[@id='client-view-prso']"),
	ORDERING_VEHICLE_CONFIG_PRICE_AND_CONFIG_SPEC_EXPORT_PDF_PRICING_VIEW_ALL_AVAILABEL_OPTIONS_CHECKBOX_XPATH("//span[@id='pricing-view-prso']//input[@value='allOptionsAvailable']"),
	ORDERING_VEHICLE_CONFIG_PRICE_AND_CONFIG_SPEC_EXPORT_PDF_PRICING_VIEW_ALL_AVAILABEL_OPTIONS_TEXT_XPATH("//span[@id='pricing-view-prso']"),
	ORDERING_VEHICLE_CONFIG_SEARCH_INDIVIDUAL_PENDING_AUDIT_STATUUS_ID("audit-pending-0"),
	ORDERING_VEHICLE_CONFIG_SEARCH_INDIVIDUAL_RETURN_FOR_REWORK_STATUUS_ID("audit-pending-0"),
	ORDERING_VEHICLE_CONFIG_SEARCH_INDIVIDUAL_PLACE_ON_HOLD_STATUUS_ID("hold-0"),
	ORDERING_VEHICLE_CONFIG_SEARCH_INDIVIDUAL_ON_HOLD_POPUP_CLASS("modal-content"),
	ORDERING_VEHICLE_CONFIG_SEARCH_INDIVIDUAL_ON_HOLD_POPUP_ACCEPT_BUTTON_ID("modal-accept-btn"),
	ORDERING_VEHICLE_CONFIG_SEARCH_INDIVIDUAL_ELEMENT_REVIEW_STATUS_ID("element-reviewed-approved-0"),
	ORDERING_VEHICLE_CONFIG_SEARCH_INDIVIDUAL_PENDING_CLIENT_APPROVAL_STATUS_ID("pending-customer-approval-0"),
	ORDERING_VEHICLE_CONFIG_SEARCH_INDIVIDUAL_PENDING_CLIENT_APPROVAL_POPUP_XPATH("//div[@class='modal-content']//span[contains(text(),'Pending Client Approval')]"),
	ORDERING_VEHICLE_CONFIG_SEARCH_INDIVIDUAL_PENDING_CLIENT_APPROVAL_ADD_INTERNAL_APPROVER_ID("search-internal-user"),
	ORDERING_VEHICLE_CONFIG_SEARCH_INDIVIDUAL_PENDING_CLIENT_APPROVAL_ADD_INTERNAL_APPROVER_LIST_CSS("div.tt-suggestion.tt-selectable.tt-client"),
	ORDERING_VEHICLE_CONFIG_SEARCH_INDIVIDUAL_PENDING_CLIENT_APPROVAL_ADD_INTERNAL_APPROVER_ADD_BUTTON_ID("addinternal"),
	ORDERING_VEHICLE_CONFIG_SEARCH_INDIVIDUAL_MODEL_POPUP_SUBMIT_BUTTON_ID("modal-ok-btn"),
	ORDERING_VEHICLE_CONFIG_SEARCH_INDIVIDUAL_CLIENT_DECLINED_STATUS_ID("client-declined-0"),
	ORDERING_VEHICLE_CONFIG_SEARCH_INDIVIDUAL_CLIENT_DECLINED_MODEL_POPUP_XPATH("//div[@class='modal-content']//span[contains(text(),'Confirmation Required')]"),
	ORDERING_VEHICLE_CONFIG_SEARCH_INDIVIDUAL_CLIENT_DECLINED_MODEL_POPUP_COMMENT_XPATH("//textarea[@id='clientDeclineModalCommentBox']"),
	ORDERING_VEHICLE_CONFIG_SEARCH_INDIVIDUAL_ARCHIVE_STATUS_ID("archived-0"),
	ORDERING_VEHICLE_CONFIG_SEARCH_INDIVIDUAL_ARCHIVE_STATUS_POPUP_XPATH("//div[@class='modal-content']//span[contains(text(),'Warning')]"),
	ORDERING_VEHICLE_CONFIG_SEARCH_SPEC_STATUS_CLASS("js-fleet-status"),
	ORDERING_VEHICLE_CONFIG_SEARCH_INDIVIDUAL_PENDING_CLIENT_APPROVAL_POPUP_SPECS_COUNT_XPATH("//div[@class='right-row-number']"),
	ORDERING_VEHICLE_CONFIG_SEARCH_INDIVIDUAL_PENDING_CLIENT_APPROVAL_POPUP_HEADER1_XPATH("//div[@class='pendingclientapproval-header flex-one-dottwo']"),
	ORDERING_VEHICLE_CONFIG_SEARCH_INDIVIDUAL_PENDING_CLIENT_APPROVAL_POPUP_HEADER2_XPATH("//div[@class='pendingclientapproval-header flex-one']"),
	ORDERING_VEHICLE_CONFIG_SEARCH_INDIVIDUAL_PENDING_CLIENT_APPROVAL_POPUP_SPECDATA_XPATH("//div[@class='pendingclientapproval-row-data flex-one']"),
	ORDERING_VEHICLE_CONFIG_SEARCH_INDIVIDUAL_PENDING_CLIENT_APPROVAL_POPUP_SPECDATA2_XPATH("//div[@class='pendingclientapproval-row-data flex-one-dottwo']"),
	ORDERING_VEHICLE_CONFIG_SEARCH_INDIVIDUAL_PENDING_CLIENT_APPROVAL_POPUP_FLAG_FOR_REVIEW_XPATH("//input[@id='flagReviewApproval']"),
	ORDERING_VEHICLE_CONFIG_SEARCH_INDIVIDUAL_PENDING_CLIENT_APPROVAL_POPUP_FLAG_FOR_REVIEW_NEW_XPATH("//input[@name='flagReviewApproval']"),
	ORDERING_VEHICLE_CONFIG_SEARCH_INDIVIDUAL_PENDING_CLIENT_APPROVAL_POPUP_FLAG_FOR_REVIEW_TEXT_XPATH("//input[@id='flagReviewApproval']//parent::label"),
	ORDERING_VEHICLE_CONFIG_SEARCH_INDIVIDUAL_PENDING_CLIENT_APPROVAL_POPUP_COMMENT_XPATH("//textarea[@class='comments-box']"),
	ORDERING_VEHICLE_CONFIG_SEARCH_INDIVIDUAL_PENDING_CLIENT_APPROVAL_POPUP_INTERNAL_APPROVAL_EMAIL_BOX_XPATH("//input[@id='internal-user-email']"),
	ORDERING_VEHICLE_CONFIG_TABLE_SELECT_CHECKBOXES_XPATH("//input[contains(@id,'data-table__checkbox') and @type='checkbox']"),
	ORDERING_VEHICLE_CONFIG_TABLE_BULK_ACTIONS_XPATH("//div[@id='bulk-actions-container']//button"),
	ORDERING_VEHICLE_CONFIG_TABLE_ACTIONS_DOTS_XPATH("//div[contains(@id,'row-action-menu-')]//button"),
	ORDERING_VEHICLE_CONFIG_TABLE_ROW_ACTIONS_OPEN_MENU_ITEMS_XPATH("//div[contains(@id,'row-action-menu-')]//div[@class='row-actions dropdown open']//ul[1]/li"),
	ORDERING_VEHICLE_CONFIG_TABLE_BULK_ACTIONS_OPEN_MENU_ITEMS_XPATH("//div[contains(@id,'row-action-menu-')]//div[@class='row-actions dropdown open']//ul[2]/li"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_TABLE_HEADER_XPATH("//div[@id='specs-queue-table_wrapper']//table//tr/th"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_REVIEW_FLAG_DROPDOWN_XPATH("//select[@id='notify-select']"),
	ORDERING_VEHICLE_CONFIG_TABLE_COLUMN_DATA_XPATH("//div[@id='specs-queue-table_wrapper']//tbody/tr/td"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_TABLE_ROWS_XPATH("//table[@id='specs-queue-table']/tbody/tr"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_TABLE_CONTAINER_XPATH("//table[@id='specs-queue-table']/tbody/tr[rowNo]/td[column]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_SOURCE_DROPDOWN_XPATH("//select[@id='internalExternalIndicator-select']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_IN_USE_POP_UP_EDITMODE_XPATH("//button[@id='edit-mode']"),
	ORDERING_VEHICLE_CONFIG_PRICE_CONFIG_REVIEW_FLAG_DROPDOWN_XPATH("//select[@id='notify-select']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_STATUS_DROPDOWN_SELECTALL_XPATH("(//div[@id='search-filters']//li[2]/a/label/input)[2]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_ID_NAME_XPATH("//div[@id='spec-conf-header']/div[2]/div[2]/div"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_APPROVE_BUTTON_XPATH("//button[@id='approve-btn']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_DECLINE_BUTTON_XPATH("//button[@id='decline-btn']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_DECLINE_POPUP_CANCEL_BUTTON_XPATH("//button[@id='modal-close-btn']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_DECLINE_POPUP_SUBMIT_BUTTON_XPATH("//button[@id='modal-ok-btn']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_DECLINE_POPUP_SELECT_FILE_BUTTON_XPATH("//button[@id='file-upload-btn']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_DECLINE_POPUP_HEADLINE_XPATH("//div[@id='client-decline']/div/div/div[2]/div/div[1]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_DECLINE_COMMENT_BOX_XPATH("//textarea[@id='clientDeclineModalCommentBox']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_DETAIL_PAGE_CANCEL_XPATH("//div[@id='manage__fleetSpecsSection']/div[3]/div[1]/div[1]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_NO_OF_RECORDS_XPATH("//div[@id='specs-queue-table_info']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_SELECTALL_XPATH("(//div[@id='specs-queue-table_wrapper']//thead//input)[1]"),
	ORDERING_VEHICLE_SPEC_DETAILS_PAGE_OPTION_AVAILABLE_XPATH("//li[contains(text(),'4X4')]"),
	ORDERING_VEHICLE_SPEC_DETAILS_OPTIONS_lABEL_XPATH("//div[@data-header='Port Installed Options']"),
	ORDERING_VEHICLE_SPEC_DETAILS_OPTIONS_STATE_lABEL_XPATH("//ul[@data-code='4X4']/li[@class='col-sm-1 text-center options__ first-element']"),
	ORDERING_VEHICLE_SPEC_DETAILS_OPTIONS_TYPE_lABEL_XPATH("//ul[@data-code='4X4']//select[@class='options-type-dropdown']"),
	ORDERING_VEHICLE_SPEC_DETAILS_OPTIONS_TYPE_SELECT_XPATH("//ul[@data-code='4X4']//select[@class='options-type-dropdown']/option[@value='DriverPaid']"),
	ORDERING_VEHICLE_SPEC_DETAILS_DPO_MODEL_POPUP_XPATH("//div[@class='modal-content']"),
	ORDERING_VEHICLE_SPEC_DETAILS_DPO_MODEL_POPUP_CLOSE_BUTTON_XPATH("//button[@id='modal-accept-btn']"),
	ORDERING_VEHICLE_SPEC_DETAILS_DPO_ADJUSTMENT_TYPE_XPATH("//select[@id='short-4X4']"),
	ORDERING_VEHICLE_SPEC_DETAILS_DPO_INVOICE_PRICE_XPATH("//input[@id='driverPrice-4X4']"),
	ORDERING_VEHICLE_SPEC_DETAILS_DPO_TOTAL_INVOICE_XPATH("//ul[@data-code='4X4']//li[@class='col-sm-1 invoice currency']"),
	ORDERING_VEHICLE_SPEC_DETAILS_STD_EQUIPMENT_TAB_XPATH("//li[@class='standardequipment-tabcontent']"),
	ORDERING_VEHICLE_SPEC_DETAILS_STD_EQUIPMENT_SECTIONS_XPATH("//div[@id='accordion']//div[@class='accordion']/h3"),
	ORDERING_VEHICLE_SPEC_DETAILS_GROWL_MESSAGE_XPATH("//div[@class='noty-msg x-style']"),
	ORDERING_VEHICLE_SPEC_CLIENT_SEARCH_BOX_XPATH("//input[@class='input-xl search-client']"),
	ORDERING_PRICE_AND_CONFIG_SPEC_FEESADJUSTMENT_XPATH("//a[text()='Fees & Adjustments']"),
	ORDERING_PRICE_AND_CONFIG_SPEC_CONTRACTTYPE_XPATH("//h6[text()='Contract Type']"),
	ORDERING_PRICE_AND_CONFIG_SPEC_CONTRACTTYPEBYDEFAULT_XPATH("//select[@id='document-category-code']/option[@selected]"),
	ORDERING_PRICE_AND_CONFIG_SPEC_CONTRACTDROPDOWN_XPATH("//select[@id='document-category-code']//option"),
	ORDERING_PRICE_AND_CONFIG_SPEC_CUSTOMADJUSTMENT_XPATH("(//th[contains(@class,'heading-title')])[2]/b[text()='Custom Adjustment Fees']"),
	ORDERING_PRICE_AND_CONFIG_SPEC_CUSTOMADJUSTMENTDESC_XPATH("//input[@name='descript']"),
	ORDERING_PRICE_AND_CONFIG_SPEC_CUSTOMADJUSTMENTFEES_XPATH("//input[@id='myInput']"),
	ORDERING_PRICE_AND_CONFIG_SPEC_CUSTOMADJUSTMENTFEESREFLECTED_XPATH("//tr[@class='feesdetails fees-data-row']//td[contains(@class,'custom-fee-invoice value-position')]"),
	ORDERING_PRICE_AND_CONFIG_SPEC_CUSTOMADJUSTMENTFEESVALIDATION_XPATH("///tr[@class='data-table__feesdetails subtotal']//td[contains(@class,'subtotal-invoice value-position')]/b"),
	ORDERING_PRICE_AND_CONFIG_SPEC_CLIENTBREAKDOWNRESULTS_XPATH("//input[@id='search-items']"),
	ORDERING_PRICE_AND_CONFIG_SPEC_CLIENTBREAKDOWNCHKBOX_XPATH("(//div[@id='breakdown-accordion-search']//following::input[@class='select-bkd'])[1]"),
	ORDERING_PRICE_AND_CONFIG_SPEC_CLIENTBREAKDOWNNAME_XPATH("(//div[@id='breakdown-accordion-search']//following::input[@class='select-bkd']/following::span)[1]"),
	ORDERING_PRICE_AND_CONFIG_SPEC_CLIENTBREAKDOWNNAMEVALIDATION_XPATH("//div[@class='bkd-list']//span/text()[1]"),
	ORDERING_PRICE_AND_CONFIG_SPEC_COPYPRICECONFIG_XPATH("//a[@id='row-action-copy-fleet-spec-0']"),
	ORDERING_PRICE_AND_CONFIG_SPEC_COPYPRICECONFIGPOPUP_XPATH("//i[@class='modal__header-icon']"),
	ORDERING_PRICE_AND_CONFIG_SPEC_COPYPRICECONFIGPOPUPCLIENTNUMBER_XPATH("//input[@id='spec-copy-to-client']"),
	ORDERING_PRICE_AND_CONFIG_SPEC_COPYPRICECONFIGPOPUPVEHICLETAB_XPATH("//label[text()='Vehicle tab']"),
	ORDERING_PRICE_AND_CONFIG_SPEC_COPYPRICECONFIGPOPUPUPFITTINGTAB_XPATH("//label[text()='Upfitting tab']"),
	ORDERING_PRICE_AND_CONFIG_SPEC_COPYPRICECONFIGPOPUPVEHICLETABCHKBOX_XPATH("//label[text()='Vehicle tab']/..//input[@id='vehicle']"),
	ORDERING_PRICE_AND_CONFIG_SPEC_COPYPRICECONFIGPOPUPSAVEBTN_XPATH("//button[@id='modal-accept-btn']"),
	ORDERING_PRICE_AND_CONFIG_SPEC_COPYPRICECONFIGPOPUPSAVEBTN1_XPATH("(//button[@id='modal-accept-btn'])[2]"),
	ORDERING_PRICE_AND_CONFIG_SPEC_SAVEASCLIENTBREAKDOWNCHKBOX_XPATH("//a[@class='outer__item_parent']/input[@class='select-bkd'][contains(@data-brkdwn,'NAL-CAM-00SUR-000113-0113501041-US10-A455')]"),
	ORDERING_PRICE_AND_CONFIG_SPEC_UPDATEDSAVEASCLIENTBREAKDOWNCHKBOX_XPATH("//a[@class='outer__item_parent']/input[@class='select-bkd'][1]"),
	ORDERING_PRICE_AND_CONFIG_SPEC_PLUSICONBREAKDOWN_XPATH("//i[@class='fa input-popup-icon-plus']"),
	ORDERING_PRICE_AND_CONFIG_SPEC_PLUSICONBREAKDOWNSAVE_XPATH("(//button[contains(text(),'Continue')])[2]"),
	ORDERING__PRICE_AND_CONFIG_SPEC_CREATEDMESSAGE_XPATH("//div[@class='noty-msg x-style']"),
	ORDERING__PRICE_AND_CONFIG_SPEC_AMOUNTREFLECTED_XPATH("//td[contains(@class,'subtotal-invoice value-position')]"),
	ORDERING__PRICE_AND_CONFIG_SPEC_COPY_DPO_POPUP_XPATH("//div[@id='specs-copy-driver']//div[@class='modal-content']"),
	ORDERING__PRICE_AND_CONFIG_SPEC_COPY_DPO_BUTTON_XPATH("//div[@id='specs-copy-driver']//div[@class='modal-content']//button[@id='modal-close-btn']"),
	ORDERING_FLEET_SPEC_STANDARD_VIEW_BUTTON_XPATH("//button[@id='default-view-button']"),
	ORDERING_FLEET_SPEC_STANDARD_AUTO_CHECK_BUTTON_XPATH("//span[@class='default-view-preference js-default-view-preference']"),
	ORDERING_FLEET_SPEC_MANAGE_VIEW_BUTTON_XPATH("//div[@id='queue-actions']/div/div/div[2]/span/ul/li[2]/a"),
	ORDERING_FLEET_SPEC_MANAGE_VIEW_SAVE_BUTTON_XPATH("//button[@id='modal-save-close']"),
	ORDERING_FLEET_SPEC_MANAGE_VIEW_SAVE_AND_DEFAULT_BUTTON_XPATH("(//button[@class='modal-save-default button button--secondary'])"),
	ORDERING_FLEET_SPEC_MANAGE_VIEW_DELETE_BUTTON_XPATH("//button[@id='modal-delete']"),
	ORDERING_FLEET_SPEC_MANAGE_VIEW_DELETE_BUTTON_BO_XPATH("//button[@class='button button--primary modal-delete']"),
	ORDERING_FLEET_SPEC_CLEAR_FILTER_BUTTON_XPATH("//button[@id='search-by-filters-btn']"),
	ORDERING_FLEET_SPEC_STANDARD_VIEW_DROPDOWN_XPATH("(//select[@class='current-view-dropdown js-current-view-select-option'])"),
	ORDERING_FLEET_SPEC_MANAGE_VIEW_CONFIRMATION_YES_BUTTON_XPATH("//button[@id='modal-accept-btn']"),
	ORDERING_FLEET_SPEC_MANAGE_VIEW_NOTIFICATION_ERROR_XPATH("//div[@class='noty-msg x-style']"),
	ORDERING_FLEET_SPEC_MANAGE_VIEW_SPEC_VERSION_ID_CHECKBOX_XPATH("(//div[@class='checkbox-groups'])[30]"),
	ORDERING_FLEET_SPEC_MANAGE_VIEW_SPEC_REVISION_NUMBER_CHECKBOX_XPATH("(//div[@class='checkbox-groups'])[9]"),
	ORDERING_FLEET_SPEC_MANAGE_VIEW_SPEC_LINKED_CLIENT_CHECKBOX_XPATH("(//div[@class='checkbox-groups'])[6]"),
	ORDERING_FLEET_SPEC_MANAGE_VIEW_SPEC_ORDER_COUNT_CHECKBOX_XPATH("(//div[@class='checkbox-groups'])[10]"),
	ORDERING_FLEET_SPEC_MANAGE_VIEW_SPEC_GEOGRAPHICAL_RES_CHECKBOX_XPATH("(//div[@class='checkbox-groups'])[23]"),
	ORDERING_FLEET_SPEC_MANAGE_VIEW_SPEC_ON_HOLD_REASON_CHECKBOX_XPATH("(//div[@class='checkbox-groups'])[35]"),
	ORDERING_FLEET_SPEC_MANAGE_VIEW_SPEC_ON_HOLD_FIRST_REASON_CHECKBOX_XPATH("(//div[@class='checkbox-groups'])[34]"),
	ORDERING_FLEET_SPEC_MANAGE_VIEW_NEW_VIEW_NAME_RADIO_BUTTON_XPATH("(//input[@id='create-new-view-radio'])"),
	ORDERING_FLEET_SPEC_MANAGE_VIEW_NEW_VIEW_NAME_INPUT_BOX_XPATH("(//input[@id='create-new-view-text-input'])"),
	ORDERING_FLEETSPEC_TABLE_FLEETSPEC_STATUS_COLUMN_XPATH("(//th[contains(@aria-label,'Fleet Spec Status')])[1]"),
	ORDERING_PRICE_CONFIG_STATUS_COLUMN_XPATH("(//th[contains(@aria-label,'Price &amp')])[1]"),
	ORDERING_PRICE_CONFIG_ID_COLUMN_XPATH("(//th[contains(@aria-label,'Price &amp')])[2]"),
	ORDERING_PRICE_CONFIG_NAME_COLUMN_XPATH("(//th[contains(@aria-label,'Price &amp')])[3]"),
	ORDERING_FLEETSPEC_TABLE_IMAGE_COLUMN_XPATH("(//th[contains(@aria-label,'Image')])[1]"),
	ORDERING_FLEETSPEC_TABLE_CLIENT_NUMBER_COLUMN_XPATH("(//th[contains(@aria-label,'Client Number')])[1]"),
	ORDERING_FLEETSPEC_TABLE_CLIENT_NAME_COLUMN_XPATH("(//th[contains(@aria-label,'Client Name')])[1]"),
	ORDERING_FLEETSPEC_TABLE_BREAKDOWN_COLUMN_XPATH("(//th[contains(@aria-label,'Breakdown')])[1]"),
	ORDERING_FLEETSPEC_TABLE_FLEETSPEC_ID_COLUMN_XPATH("(//th[contains(@aria-label,'Fleet Spec ID')])[1]"),
	ORDERING_FLEETSPEC_TABLE_FLEETSPEC_NAME_COLUMN_XPATH("(//th[contains(@aria-label,'Fleet Spec Name')])[1]"),
	ORDERING_FLEETSPEC_TABLE_PRICE_PROTECTED_COLUMN_XPATH("(//th[contains(@aria-label,'Price Protected')])[1]"),
	ORDERING_FLEETSPEC_TABLE_UPFIT_INDICATOR_COLUMN_XPATH("(//th[contains(@aria-label,'Upfit Indicator')])[1]"),
	ORDERING_FLEETSPEC_TABLE_YEAR_COLUMN_XPATH("(//th[contains(@aria-label,'Year')])[1]"),
	ORDERING_FLEETSPEC_TABLE_MAKE_COLUMN_XPATH("(//th[contains(@aria-label,'Make')])[1]"),
	ORDERING_FLEETSPEC_TABLE_MODEL_COLUMN_XPATH("(//th[contains(@aria-label,'Model')])[1]"),
	ORDERING_FLEETSPEC_TABLE_TRIM_COLUMN_XPATH("(//th[contains(@aria-label,'Trim')])[1]"),
	ORDERING_FLEETSPEC_TABLE_MODEL_CODE_COLUMN_XPATH("(//th[contains(@aria-label,'Model Code')])[1]"),
	ORDERING_FLEETSPEC_TABLE_LAST_UPDATED_ON_COLUMN_XPATH("(//th[contains(@aria-label,'Last Updated On')])[1]"),
	ORDERING_FLEETSPEC_TABLE_LAST_UPDATED_BY_COLUMN_XPATH("(//th[contains(@aria-label,'Last Updated By')])[1]"),
	ORDERING_FLEETSPEC_TABLE_INTERNAL_VS_EXTERNAL_COLUMN_XPATH("(//th[contains(@aria-label,'Fleet Spec Source')]"),
	ORDERING_FLEETSPEC_TABLE_CREATED_BY_COLUMN_XPATH("(//th[contains(@aria-label,'Created By')])[1]"),
	ORDERING_FLEETSPEC_TABLE_ON_HOLD_REASON_COLUMN_XPATH("(//th[contains(@aria-label,'On Hold Reason')])[1]"),
	ORDERING_FLEETSPEC_TABLE_ON_HOLD_SOURCE_COLUMN_XPATH("(//th[contains(@aria-label,'On Hold Source')])[1]"),
	ORDERING_FLEETSPEC_TABLE_PREVIOUS_STATUS_COLUMN_XPATH("(//th[contains(@aria-label,'Previous Status')])[1]"),
	ORDERING_FLEETSPEC_TABLE_BUILD_OUT_FLAG_COLUMN_XPATH("(//th[contains(@aria-label,'Built Out Flag')])[1]"),
	ORDERING_VEHICLE_CONFIG_SEARCH_FLEET_SPEC_BUTTON_XPATH("(//a[@class='vehicleConfig vconfig'])[1]"),
	ORDERING_VEHICLE_CONFIG_SEARCH_PRICE_CONFIG_BUTTON_XPATH("(//a[@class='vehicleConfig vconfig'])[3]"),    	
	ORDERING_VEHICLE_CONFIG_SEARCH_EXPORT_RESULTS_XPATH("//button[@id='export-CSV-button']"),
	ORDERING_FLEET_SPEC_MANAGE_VIEW_POP_UP_CHECKBOX_XPATH("//div[@class='checkbox-groups']"),
	ORDERING_SEARCH_FLEET_SPEC_TABLE_HEADER_XPATH("(//tr[@class='data-table__header-row'])[1]//th[@aria-controls='specs-queue-table']"),
	ORDERING_PRICE_AND_CONFIG_SPEC_ADJUSTMENTFEES_XPATH("//tbody/tr[@id='DPRI']/td[3]/input[1]"), 
	ORDERING_SEARCH_SPEC_MANAGEVIEW_XPATH("//button[@id='default-view-button']/span"),
	ORDERING_SEARCH_SPEC_MANAGEVIEW_VIEWS_LIST_XPATH("//div[@id='queue-actions']/div/div/div[2]/span/ul/li"),
	ORDERING_SEARCH_SPEC_TABLE_COLUMNS_XPATH("//*[@id='specs-queue-table']/tbody/tr[1]/td"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_PAGE_CLIENT_TEXTBOX_XPATH("//input[@id='client-search']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPECS_PAGE_CLIENT_NUMBER_XPATH("//div[@id='vehicle__buildNew']//span/span/div/div/div[1]"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_ACCEPT_BUTTON_XPATH("//button[@id='modal-accept-btn']"),
	ORDERING_FLEET_SPEC_STANDARD_VIEW_BUTTON_PREVIOUS_CSS("div.table-action-panel"),
	ORDERING_FLEET_SPEC_UPDATE_SPEC_STATUS_BROWSE_FILE_OPTION_XPATH("//input[@type='file' and @class='browse-file']"),
	ORDERING_FLEET_SPEC_UPDATE_SPEC_STATUS_DELETE_FILE_OPTION_XPATH("//div[@class='col-md-1 file-action']"),
	ORDERING_FLEET_SPEC_UPDATE_SPEC_STATUS_FILE_NAME_XPATH("//div[@class='col-md-4 file-name ']"),
	ORDERING_FLEET_SPEC_UPDATE_SPEC_STATUS_COMMENT_BOX_PENDING_APPROVAL_XPATH("//textarea[@class='comments-box']"),
	ORDERING_FLEET_SPEC_UPDATE_SPEC_COMMENTS_BUTTON_XPATH("//div[@class='btn js-comments']"),
	ORDERING_FLEET_SPEC_UPDATE_SPEC_COMMENTS_XPATH("//span[@class='comment-span']/span/span"),
	ORDERING_FLEET_SPEC_UPDATE_SPEC_COMMENTS_CLOSE_ICON_XPATH("//div[@id='close-view']/div[1]"), 
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_LEAVE_WITHOUT_SAVE_XPATH("//button[@id='leaveUnlock']"),
	ORDERING_VEHICLE_CONFIG_FLEET_SPEC_ONHOLD_MODAL_POPUP_XPATH("//div[@id='on-hold-popup']/div/div/div[1]"), 
	ORDERING_FLEET_SPEC_UPDATE_SPEC_STATUS_COMMENT_BOX_ONHOLD_XPATH("//textarea[@class='comments-box']"),
	ORDERING_FLEET_SPEC_UPDATE_SPEC_STATUS_BUTTON_PLACE_ONHOLD_XPATH("//button[@class='button button--primary modal-ok-btn']"),
	;

	private String value;

	OrderingVehicleConfigFleetSpecsPageEnum(String value) {
		this.value = value;
	}

	public String getValue() {
		return value;
	}

	@Override
	public String toString() {
		return value;
	}

}
