package com.element.fleet.ordering.enums;

public enum OrderingBOOrdMaintPageEnum {
	
	ORDERING_BO_ORD_MAINT_ID("order-maintenance-screen"), 
	ORDERING_BO_ORD_MAINT_CANCEL_BUTTON_ID("cancel"),
	ORDERING_BO_ORD_MAINT_CANCEL_BUTTON_DISABLED_XPATH("//button[@id='cancel' and @disabled='disabled']"),
	ORDERING_BO_ORD_MAINT_CANCEL_ORDER_POPUP_CSS("div#new-modal.modal.fade.in div.modal-content"),
	ORDERING_BO_ORD_MAINT_CANCEL_ORDER_POPUP_NO_CSS("div#new-modal.modal.fade.in div.modal-content > div.modal-footer > button:nth-child(1)"),
	ORDERING_BO_ORD_MAINT_CANCEL_ORDER_POPUP_YES_CSS("div#new-modal.modal.fade.in div.modal-content > div.modal-footer > button:nth-child(2)"),
	ORDERING_BO_ORD_MAINT_CANCEL_INDICATOR_LABEL_XPATH("//form[@id='generalInfo-form']//div[@class='label-wrapper']/label[text()='label-heading']//parent::div[@class='label-wrapper']//following-sibling::div/span"),
	ORDERING_BO_ORD_MAINT_SAVE_ORDER_ID("save-order"),
	ORDERING_BO_ORD_MAINT_SAVE_VEHICLE_TAB_ORDER_ID("save-vehicle-Info"),
	ORDERING_BO_ORD_MAINT_ORD_STATUS_NAME("poStatusDescription:string"),
	ORDERING_BO_ORD_MAINT_ORD_STATUS_CODE_LETTERS_NAME("majorCode:string"),
	ORDERING_BO_ORD_MAINT_ORD_STATUS_CODE_NUMBS_NAME("minorCode:string"),
	ORDERING_BO_ORD_MAINT_GENERALTAB_ID("generalInfoTabId"),
	ORDERING_BO_ORD_MAINT_UPFITTAB_ID("upfitInfoTabId"),
	ORDERING_BO_ORD_MAINT_VEHICLE_ID("vehicleInfoTabId"),
	ORDERING_BO_ORD_MAINT_VEHICLE_APPROVE_BUTTON_BEFORE_XPATH("//input[@id='h-approve' and @value='false']//preceding-sibling::span[contains(text(),'Approve')]"),
	ORDERING_BO_ORD_MAINT_VEHICLE_APPROVE_BUTTON_AFTER_XPATH("//input[@id='h-approve' and @value='true']//preceding-sibling::span[contains(text(),'Approve')]"),
	ORDERING_BO_ORD_MAINT_VEHICLE_APPROVE_BUTTON_DISABLED_CSS("#approve[disabled]"),
	ORDERING_BO_ORD_MAINT_VEHICLE_APPROVE_BUTTON_ID("save-approval-indicators"),
	ORDERING_BO_ORD_MAINT_UPFITSECTION_ID("upfitInfo-form-header"),
	ORDERING_BO_ORD_MAINT_ADDPO_ID("add-po"),
	ORDERING_BO_ORD_MAINT_APPROVE_BTN_ID("approve"),
	ORDERING_BO_ORD_MAINT_PDF_BTN_ID("exportPDF"),
	ORDERING_BO_ORD_MAINT_APPROVALTAB_LINK("Approval"),
	ORDERING_BO_ORD_MAINT_APPROVALTAB_LIST_ERROR_XPATH("//input[contains(@id,'approval-')][@checked='']//parent::div//preceding::div[1]//label"),
	ORDERING_BO_ORD_MAINT_APPROVALTAB_LIST_ERROR_CSS("label[for^=approval-]"),
	ORDERING_BO_ORD_MAINT_APPROVALTAB_LIST_ERROR_LABEL_XPATH(".//ancestor::div[@class='input-wrapper']//preceding-sibling::div[@class='label-wrapper']/label"),
	ORDERING_BO_ORD_MAINT_APPROVALTAB_CREDIT_ERROR_XPATH("//select[@name='creditIndicator']//option[@value='F'][@selected='']//parent::select//preceding::div[1]//label"),
	ORDERING_BO_ORD_MAINT_APPROVALTAB_CREDIT_ERROR_NAME("creditIndicator"),
	ORDERING_BO_ORD_MAINT_UPFITTAB_ADDED_UPFITS_LIST_XPATH("div#upfitInfo-form-tab a.upfit-po-header"),
	ORDERING_BO_ORD_MAINT_UPFITTAB_ADDED_UPFIT_SUPPLIER_SEARCH_POS_XPATH("//input[@id='supplier-%s-search']"),
	ORDERING_BO_ORD_MAINT_UPFITTAB_ADDED_UPFIT_ESTIMEATED_LEAD_TIME_WEEK_POS_XPATH("//input[@id='lead-time']"),
	ORDERING_BO_ORD_MAINT_UPFITTAB_ADDED_UPFIT_WORK_TYPE_POS_XPATH("//select[@id='work-type']"),
	ORDERING_BO_ORD_MAINT_UPFITTAB_ADDED_UPFITS_CONTAINER_ID("accordion"),
	ORDERING_BO_ORD_MAINT_UPFITTAB_ADDED_UPFIT_SUPPLIER_SEARCHED_RESULT_XPATH("(//div[@class='tt-suggestion tt-selectable empty'])[1]"),
	ORDERING_BO_ORD_MAINT_UPFITTAB_ADDED_UPFITS_LIST_CSS("div#upfitInfo-form-tab a.upfit-po-header"),
	ORDERING_BO_ORD_MAINT_UPFITTAB_ADDED_UPFITS_LIST_BODY_XPATH(".//div[@class='panel-collapse isCollapsed collapse in']"),
	ORDERING_BO_ORD_MAINT_UPFITTAB_ADDED_UPFITS_LIST_PDF_BUTTON_XPATH(".//div[starts-with(@id,'export')]"),
	ORDERING_BO_ORD_MAINT_UPFITTAB_LIST_UPFIT_CLICK_XPATH("(//div[@id='upfitInfo-form-tab']//div[@id='accordion']//div[@class='panel panel-default'][1]//a[1])[1]"),
	ORDERING_BO_ORD_MAINT_UPFITTAB_LIST_UPFIT_XPATH("//div[@id='upfitInfo-form-tab']//div[@id='accordion']//div[@class='panel panel-default']"),
	ORDERING_BO_ORD_MAINT_PDF_UPFIT_CSS("div.export-po-upfit"),
	ORDERING_BO_ORD_MAINT_UPFIT_LINE_ITEM_SUPPLIER_CSS("input.full-input.tt-input[name='supplier-search:skip']"),
	ORDERING_BO_ORD_MAINT_UPFIT_LINE_ITEM_SUPPLIER_TEXT_SEARCH_XPATH("//a[@aria-expanded='true']//following::div[@aria-expanded='true']//input[@name='supplier-search:skip']"),
	ORDERING_BO_ORD_MAINT_UPFIT_LINE_ITEM_SUPPLIER_FIRST_SEARCH_XPATH("//a[@aria-expanded='true']//following::div[@aria-expanded='true']//input[@name='supplier-search:skip']//following::div[1]//div//div[1]"),
	ORDERING_BO_ORD_MAINT_UPFIT_LINE_ITEM_SUPPLIER_ESTIMATED_LEAD_TIME_XPATH("//a[@aria-expanded='true']//following::div[@aria-expanded='true']//input[starts-with(@id,'leadWeek')]"),
	ORDERING_BO_ORD_MAINT_UPFIT_LINE_ITEM_SUPPLIER_WORK_TYPE_XPATH("//a[@aria-expanded='true']//following::div[@aria-expanded='true']//select[starts-with(@id,'workType')]"),
	ORDERING_BO_ORDER_NOT_SAVED_WARNING_POPUP_XPATH("//div[@id='new-modal']//div[@class='modal-content']"),
	ORDERING_BO_ORDER_NOT_SAVED_WARNING_POPUP_ERROR_MESSAGE_XPATH("//div[@id='new-modal']//div[@class='modal-body new-modal__body']/div"),
	ORDERING_BO_ORDER_NOT_SAVED_WARNING_POPUP_OK_BUTTON_XPATH("//div[@id='new-modal']//button[contains(text(), 'Yes')]"),
	ORDERING_BO_ON_ORDER_DRIVER_TAB_ID("driverInfoTabId"),
	ORDERING_BO_ON_ORDER_DRIVER_TAB_DRIVER_FNAME_NAME("driver[firstName]:string"),
	ORDERING_BO_ON_ORDER_DRIVER_TAB_DRIVER_MNAME_NAME("driver[middleName]:string"),
	ORDERING_BO_ON_ORDER_DRIVER_TAB_DRIVER_LNAME_NAME("driver[lastName]:string"),
	ORDERING_BO_ON_ORDER_DRIVER_TAB_DRIVER_EMPID_NAME("driver[employeeId]:string"),
	ORDERING_BO_ON_ORDER_DRIVER_TAB_DRIVER_ADDRESS_ONE_NAME("driver[contactAddress][addressLine1]:string"),
	ORDERING_BO_ON_ORDER_DRIVER_TAB_DRIVER_ADDRESS_TWO_NAME("driver[contactAddress][addressLine2]:string"),
	ORDERING_BO_ON_ORDER_DRIVER_TAB_DRIVER_CITY_NAME("driver[contactAddress][city]:string"),
	ORDERING_BO_ON_ORDER_DRIVER_TAB_DRIVER_STATE_NAME("driver[contactAddress][stateProvince]:string"),
	ORDERING_BO_ON_ORDER_DRIVER_TAB_DRIVER_COUNTRY_NAME("driver[contactAddress][county]:string"),
	ORDERING_BO_ON_ORDER_DRIVER_TAB_DRIVER_ZIPCODE_NAME("driver[contactAddress][postalCode]:string"),
	ORDERING_BO_ON_ORDER_DRIVER_TAB_DRIVER_EMAIL_NAME("driver[email]:string"),
	ORDERING_BO_ON_ORDER_DRIVER_TAB_DRIVER_PHONE_NAME("driver[phone]:string"),
	ORDERING_BO_ON_ORDER_VEHICLE_TAB_BO_FLEET_NAME_XPATH("//label[contains(text(),'Fleet Spec Name')]//following::span[1]"),
	ORDERING_BO_OOQ_ORDER_STATUS_TEXT_FIELD_NAME("addStatusCode:string"),
	ORDERING_BO_OOQ_ORDER_STATUS_DATE_TEXT_FIELD_NAME("statusDate:string"),
	ORDERING_BO_OOQ_ORDER_STATUS_SELECT_CURRENT_DATE_XPATH("//td[@data-handler='selectDay']//a[@class='ui-state-default ui-state-highlight ui-state-hover']"),
	ORDERING_BO_OOQ_ORDER_STATUS_STATE_DROPDOWN_NAME("statusIndicator"),
	ORDERING_BO_OOQ_ORDER_STATUS_ACTUAL_TEXT_XPATH("//form[@id='generalInfo-form']//label[contains(text(),'Order Status')]//following::span[1]"),
	ORDERING_BO_OOQ_ORDER_NO_DATA_AVAILABLE_TABLE_XPATH("//td[contains(text(),'No data available in table')]"),
	ORDERING_BO_ON_ORDER_BILLING_TAB_ID("billingInfoTabId"),
	ORDERING_BO_ON_ORDER_BILLING_LEASE_TERM_DROPDOWN_XPATH("//*[@name='orderBilling[leaseTerm]:string']"),
	ORDERING_BO_ON_ORDER_BILLING_ASSET_ID_XPATH("//*[@name='orderBilling[clientUnitNumber]:string']"),
	ORDERING_BO_ON_ORDER_BILLING_CLIENT_PONUM_XPATH("//*[@name='orderBilling[clientPoNumber]:string']"),
	ORDERING_BO_ON_ORDER_BILLING_LEASE_TERM_DROPDOWN_SELECTED_XPATH("//*[@name='orderBilling[leaseTerm]:string']/option[@selected]"),
	ORDERING_BO_EDIT_ORDER_LINK_XPATH("//span[contains(text(),'Edit Order')]"),
	ORDERING_BO_EDIT_ORDER_INVOICE_ENTRY_LINK_XPATH("//span[contains(text(),'Invoice Entry')]"),
	ORDERING_BO_OOQ_ORDER_MFR_DAN_TEXT_FIELD_NAME("mfgDan:string"),
	ORDERING_BO_OOQ_ORDER_NEW_UNIT_TEXT_FIELD_NAME("newUnit:string"),
	ORDERING_BO_OOQ_ORDER_NEW_UNIT_VALUE_XPATH("//div[@id='main-info']//label[contains(text(),'Unit')]//following::span[1]"),
	ORDERING_BO_OOQ_ORDER_NEW_VIN_TEXT_FIELD_NAME("newVin:string"),
	ORDERING_BO_OOQ_ORDER_NEW_VIN_VALUE_XPATH("//div[@id='main-info']//label[contains(text(),'VIN')]//following::span[1]"),
	ORDERING_BO_OOQ_ORDER_NEW_FO_NUMBER_NAME("newFONumber:string"),
	ORDERING_BO_OOQ_ORDER_NEW_FO_DATE_NAME("newFactoryOrderDate"),
	ORDERING_BO_OOQ_ORDER_NEW_PO_DATE_VALUE_XPATH("//div[@id='main-info']//label[contains(text(),'PO Date')]//following::span[1]"),
	ORDERING_BO_OOQ_ORDER_DOE_INDICATOR_TOGGLE_XPATH("//input[@name='doeIndicator:boolean']//following::label[1]"),
	ORDERING_BO_OOQ_ORDER_RENTAL_INDICATOR_TOGGLE_XPATH("//input[@id='rental-indicator']//following::label[1]"),
	ORDERING_BO_OOQ_ORDER_VEHICLE_USAGE_DROP_DOWN_NAME("coreOrder[vehicleUsage]:skip"),
	ORDERING_BO_OOQ_ORDER_POOL_TYPE_DROP_DOWN_NAME("coreOrder[poolType]:skip"),
	ORDERING_BO_OOQ_ORDER_CONTACT_FIRST_NAME_NAME("clientContact[firstName]:string"),
	ORDERING_BO_OOQ_ORDER_CONTACT_LAST_NAME_NAME("clientContact[lastName]:string"),
	ORDERING_BO_OOQ_ORDER_CLIENT_CONTACT_PHONE_NAME("clientContact[phone]:string"),
	ORDERING_BO_OOQ_ORDER_CLIENT_CONTACT_EMAIL_NAME("clientContact[email]:string"),
	ORDERING_BO_OOQ_ORDER_CLIENT_EXTENSION_NAME("clientContact[phoneExtension]:string"),
	ORDERING_BO_OOQ_ORDER_DEALERSHIP_NAME_NAME("dealerContact[contactName]:string"),
	ORDERING_BO_OOQ_ORDER_DEALER_CONTACT_FIRST_NAME_NAME("dealerContact[firstName]:string"),
	ORDERING_BO_OOQ_ORDER_DEALER_CONTACT_LAST_NAME_NAME("dealerContact[lastName]:string"),
	ORDERING_BO_OOQ_ORDER_DEALER_CONTACT_PHONE_NAME("dealerContact[phone]:string"),
	ORDERING_BO_OOQ_ORDER_DEALER_EXTENSION_NAME("dealerContact[phoneExtension]:string"),
	ORDERING_BO_OOQ_ORDER_DEALER_CONTACT_EMAIL_NAME("dealerContact[email]:string"),
	ORDERING_BO_OOQ_ORDER_USED_UNIT_INFO_USED_FLEET_ID("used-unit-client-search"),
	ORDERING_BO_OOQ_ORDER_USED_UNIT_INFO_USED_FLEET_SELECT_OPTION_XPATH("//div[@class='tt-suggestion tt-selectable tt-client']//strong"),
	ORDERING_BO_OOQ_ORDER_USED_UNIT_INFO_USED_UNIT_ID("used-unit-search"),
	ORDERING_BO_OOQ_ORDER_USED_UNIT_INFO_USED_UNIT_SELECTION_OPTION_XPATH("//input[@id='used-unit-search']//following::div[@class='tt-suggestion tt-selectable sugg-item'][1]"),
	ORDERING_BO_OOQ_ORDER_WHO_TO_SELL_DROP_DOWN_NAME("usedUnit[whoToSell]:skip"),
	ORDERING_BO_OOQ_ORDER_DELIVERING_DELAER_CODE_NAME("deliveringDealer[supplierCode]:string"),
	ORDERING_BO_OOQ_ORDER_CD_FEE_MARKUP_XPATH("//label[contains(text(),'CD Fee/Markup')]//following::input[2]"),
	ORDERING_BO_OOQ_ORDER_DELIVERING_DEALER_NAME_XPATH("//h2[contains(text(),'Delivering Dealer')]//following::label[contains(text(),'Dealer Name')][1]//following::input[1]"),
	ORDERING_BO_OOQ_ORDER_DELIVERING_DEALER_PHONE_XPATH("//h2[contains(text(),'Delivering Dealer')]//following::label[contains(text(),'Dealer Phone')][1]//following::input[1]"),
	ORDERING_BO_OOQ_ORDER_DELIVERING_DEALER_ADDRESS1_XPATH("//label[contains(text(), 'Dealer Address 1')]//following::input[1]"),
	ORDERING_BO_OOQ_ORDER_DELIVERING_DEALER_ADDRESS2_XPATH("//label[contains(text(), 'Dealer Address 2')]//following::input[1]"),
	ORDERING_BO_OOQ_ORDER_DELIVERING_DEALER_CITY_XPATH("//label[contains(text(), 'Dealer City')]//following::input[1]"),
	ORDERING_BO_OOQ_ORDER_DELIVERING_DEALER_STATE_XPATH("//label[contains(text(),'Dealer City')]//following::input[2]"),
	ORDERING_BO_OOQ_ORDER_DELIVERING_DEALER_ZIP_CODE_XPATH("//label[contains(text(),'Dealer City')]//following::input[3]"),
	ORDERING_BO_OOQ_ORDER_CD_FEE_MARKUP_FACTORY("300.00"),
	ORDERING_BO_OOQ_ORDER_DELIVERING_DEALER_NAME("ROUNTREE FORD"),
	ORDERING_BO_OOQ_ORDER_DELIVERING_DEALER_PHONE("318-798-3673"),
	ORDERING_BO_OOQ_ORDER_DELIVERING_DEALER_ADDRESS1("PO BOX 52048 SHREVEPORT LA US 71105"),
	ORDERING_BO_OOQ_ORDER_DELIVERING_DEALER_ADDRESS2("8770 BUSINESS PARK DRIVE"),
	ORDERING_BO_OOQ_ORDER_DELIVERING_DEALER_CITY("SHREVEPORT"),
	ORDERING_BO_OOQ_ORDER_DELIVERING_DEALER_STATE("LA"),
	ORDERING_BO_OOQ_ORDER_DELIVERING_DEALER_ZIP_CODE("71105"),
	ORDERING_BO_OOQ_ORDER_DEALER_TAB_ID("dealerInfoTabId"),
	ORDERING_BO_OOQ_ACTION_FORM_EQUIPCATEGORY_TEXTBOX_XPATH("//form[@id='addOption-form']//label[text()='Equipment Category']/../..//input[@type='text']"),
	ORDERING_BO_OOQ_ACTION_FORM_OPTIONCODE_TEXTBOX_XPATH("//form[@id='addOption-form']//label[text()='Option Code']/../..//input[@type='text']"),
	ORDERING_BO_OOQ_ACTION_FORM_EXT_OPTIONCODE_TEXTBOX_XPATH("//form[@id='addOption-form']//label[text()='Option External Code']/../..//input[@type='text']"),
	ORDERING_BO_OOQ_ACTION_FORM_OPTION_DESCRIPTION_TEXTBOX_XPATH("//form[@id='addOption-form']//label[text()='Option Description']/../..//input[@type='text']"),
	ORDERING_BO_OOQ_ACTION_FORM_QUANTITY_TEXTBOX_XPATH("//form[@id='addOption-form']//label[text()='Quantity']/../..//input[@type='text']"),
	ORDERING_BO_OOQ_ACTION_ADD_XPATH("//table[@id='vehicle-table']//*[contains(@class,'plus')]"),
	ORDERING_BO_OOQ_ACTION_FORM_SAVE_XPATH("//input[@value='Save']"),
	ORDERING_BO_OOQ_ACTION_SEARCH_XPATH("//div[@id='vehicle-table_filter']//input"),
	ORDERING_BO_OOQ_ACTION_EDIT_XPATH("//table[@id='vehicle-table']//a[@class='edit']"),
	ORDERING_BO_OOQ_ACTION_DELETE_XPATH("//table[@id='vehicle-table']//a[@class='delete']"),
	ORDERING_BO_OOQ_ACTION_UNDO_DELETE_XPATH("//table[@id='vehicle-table']//a[@class='undo']"),
	ORDERING_BO_OOQ_ACTION_FIRST_RECORD_VEHICLE_TABLE_XPATH("//table[@id='vehicle-table']//tr[@class='odd']"),
	ORDERING_BO_OOQ_ACTION_SOFT_DELETE_VEHICLE_TABEL_XPATH("(//table[@id='vehicle-table']//td[contains(@class,'to-be-deleted')])[1]"),
	ORDERING_BO_OOQ_GENERAL_ORDER_MAININFO_FIELDS_LABEL_XPATH("//form[@id='generalInfo-form']//div[@id='main-info']//label"),
	ORDERING_BO_OOQ_GENERAL_ORDER_MAININFO_FIELDS_VALUE_XPATH("//form[@id='generalInfo-form']//label[text()='%s']//following-sibling::div//span"),
	ORDERING_BO_OOQ_GENERAL_ORDER_SECTION_FIELDS_LABEL_XPATH("//form[@id='generalInfo-form']//span/..//label"),
	ORDERING_BO_OOQ_GENERAL_ORDER_SECTION_FIELDS_VALUE_XPATH("//form[@id='generalInfo-form']//label[text()='%s']/../..//span"),
	ORDERING_BO_OOQ_VEHICLE_SPECIFICATION_SECTION_LABEL_XPATH("//form[@id='vehicleInfo-form']//input[@type='text']//parent::div/..//label"),
	ORDERING_BO_OOQ_VEHICLE_SPECIFICATION_SECTION_VALUE_XPATH("//form[@id='vehicleInfo-form']//label[text()='%s']//parent::div/..//input"),
	ORDERING_BO_OOQ_DRIVER_SECTION_LABEL_XPATH("//form[@id='driverInfo-form']//input[@type='text']//parent::div/..//label"),
	ORDERING_BO_OOQ_DRIVER_SECTION_VALUE_XPATH("//form[@id='driverInfo-form']//label[text()='%s']//parent::div/..//input"),
	ORDERING_BO_OOQ_VEHICLE_SPECIFICATION_SECTION_FLEET_VALUE_XPATH("//form[@id='vehicleInfo-form']//label[text()='%s']//parent::div/..//span"),
	ORDERING_BO_OOQ_BILLING_SECTION_SELECTFIELDS_VALUE_XPATH("//form[@id='billingInfo-form']//select[@id='%s']/..//span"),
	ORDERING_BO_OOQ_VEHICLE_TABLE_COLUMN_XPATH("//table[@id='vehicle-table']//th[text()=' %s ']"),
	ORDERING_BO_OOQ_VEHICLE_TABLE_COLUMN_VALUE_XPATH("//table[@id='vehicle-table']//td[contains(@class, 'sort')]"),
	ORDERING_BO_ORD_MAINT_UPFIT_ADD_UPFIT_SUPPRESS_PO_CSS("#suppress-po + label"),
	ORDERING_BO_ORD_MAINT_UPFIT_SUPPRESS_PO_CSS("#suppress-indicator>div>div>label"),
	ORDERING_BO_ORD_MAINT_UPFIT_CC_XPATH("//textarea[contains(@id, 'email_cc')]"),
	ORDERING_BO_ORD_MAINT_UPFIT_SEND_PO_NOW_CSS("div#send-po-btn>div"),
	ORDERING_BO_ORD_MAINT_EMAIL_POPUP_PO_NUMBER_CSS("#detailed-page > ul > li > a"),
	ORDERING_BO_ORD_MAINT_EMAIL_POPUP_TO_ID("email-to"),
	ORDERING_BO_ORD_MAINT_EMAIL_POPUP_CC_ID("email-cc"),
	ORDERING_BO_ORD_MAINT_EMAIL_POPUP_SUBJECT_ID("subject"),
	ORDERING_BO_ORD_MAINT_EMAIL_POPUP_ATTACHMENT_CSS("div.download-attachment>a"),
	ORDERING_BO_ORD_MAINT_EMAIL_POPUP_DOWNLOAD_ALL_CSS("div.download-all>a"),
	ORDERING_BO_ORD_MAINT_EMAIL_POPUP_CANCEL_CSS("div#cancel-email"),
	ORDERING_BO_ORD_MAINT_EMAIL_POPUP_SEND_ID("send-email"),
	ORDERING_BO_ORD_MAINT_EMAIL_POPUP_ADDITIONAL_TEXT_ID("additional-text"),
	ORDERING_BO_ORD_MAINT_EMAIL_POPUP_ADDITIONAL_TEXT_LIMIT_ID("additional-text-limit"),
	ORDERING_BO_ORD_MAINT_EMAIL_POPUP_IFRAME_ID("email-template"),
	ORDERING_BO_ORD_MAINT_EMAIL_POPUP_CLIENTUNIT_XPATH("//td[text()='Client-Unit number:']/following-sibling::td"),
	ORDERING_BO_ORD_MAINT_EMAIL_POPUP_FACTORY_ORDER_XPATH("//td[text()='Factory order number:']/following-sibling::td"),
	ORDERING_BO_ORD_MAINT_EMAIL_POPUP_VIN_XPATH("//td[contains(text(), 'VIN:')]/following-sibling::td"),
	ORDERING_BO_ORD_MAINT_EMAIL_POPUP_PO_NUMBER_XPATH("//td[contains(text(), 'Purchase order number:')]/following-sibling::td"),
	ORDERING_BO_ORD_MAINT_EMAIL_POPUP_SUPPLIER_QUOTE_NO_XPATH("//td[contains(text(), 'Supplier quote number:')]/following-sibling::td"),
	ORDERING_BO_ORD_MAINT_EMAIL_POPUP_SUPPLIER_QUOTE_DATE_XPATH("//td[contains(text(), 'Supplier quote  date:')]/following-sibling::td"),
	ORDERING_BO_ORD_UPFIT_LINE_ITEM_PO_NUM_CSS("a.upfit-po-header>div>div:nth-child(2)>div"),
	ORDERING_BO_ORD_MAINT_FO_NUM_XPATH("//div[@id='main-info']//label[contains(text(),'FO Number')]//following::span[1]"),
	ORDERING_BO_ORD_UPFIT_SUPPLIER_QUOTE_NO_CSS("div#supplier-quote>div:nth-child(2)>span"),
	ORDERING_BO_ORD_UPFIT_SUPPLIER_QUOTE_DATE_XPATH("//input[contains(@id, 'po-quote-date')]"),
	ORDERING_BO_ORD_UPFIT_SUPPLIER_EMAIL_XPATH("//span[contains(@id, 'supplier-email')]"),
	ORDERING_BO_ORD_CONFIRM_WARNING_OK_XPATH("//div[@id='new-modal']//button[contains(text(), 'Yes')]"),
	ORDERING_BO_ORD_SEND_PO_FIRST_ADDITIONAL_TEXT_CSS("#bodyTable > tbody > tr:nth-child(2) > td > div > div"),
	ORDERING_BO_ORD_UPFIT_LINE_ITEM_CURRENT_PO_STATUS_CSS("a.upfit-po-header>div>div:nth-child(8)"),
	ORDERING_BO_ORD_UPFIT_CANCEL_PO_BUTTON_CSS("div.cancel-po"),
	ORDERING_BO_ORD_UPFIT_CANCEL_PO_CONFIRMATION_YES_CSS("button#proceed-cancel"),
	ORDERING_BO_ORD_UPFIT_SEND_CANCEL_PO_CONFIRMATION_YES_CSS("button#send-cancellation"),
	ORDERING_BO_ORD_CHANGE_ORDER_TYPE_CLASS("orderType"),
	ORDERING_BO_ORD_VEHICLE_LOCATED_DROPDOWN_XPATH("//select[@name='coreOrder[clientLocated]:skip']"),
	ORDERING_BO_ORD_NEW_FO_NUMBER_XPATH("//label[text()='Client']//following::span[4]"),
	ORDERING_BO_ORD_REMOVE_USED_UNIT_CSS("div#btn-removeUsedUnit > span:nth-child(2)"),
	ORDERING_BO_ORD_USED_UNIT_REMOVED_XPATH("//input[@id='h-removeUU' and @value='true']"),
	ORDERING_BO_OOQ_TITLE_AND_REGISTRATION_TAB_ID("titleInfoTabId"),
	ORDERING_BO_OOQ_TITLE_AND_REGISTRATION_SECTION_TITLELABEL_XPATH("//h2[contains(text(),'Title')]"),
	ORDERING_BO_OOQ_TITLE_AND_REGISTRATION_SECTION_REGISTRATIONLABEL_XPATH("//h2[contains(text(),'Registration')]"),
	ORDERING_BO_OOQ_TITLE_AND_REGISTRATION_SECTION_LIENHOLDERLABEL_XPATH("//h2[contains(text(),'Lienholder')]"),
	ORDERING_BO_OOQ_TITLE_AND_REGISTRATION_SECTION_WHO_TO_TITLE_XPATH("//select[@name='titleInfo[whoToTitle]:skip']"),
	ORDERING_BO_OOQ_TITLE_AND_REGISTRATION_SECTION_PLATE_TYPE_XPATH("//select[@name='titleInfo[plateType]:skip']"),
	ORDERING_BO_OOQ_TITLE_AND_REGISTRATION_SECTION_VEHICLETEXT_XPATH("//p[contains(., 'Vehicle' )]//parent::p"),
	ORDERING_BO_OOQ_TITLE_AND_LICENSE_SECTION_TITLE_NAME_XPATH("//h2[contains(text(),'Title Information')]"),
	ORDERING_BO_OOQ_TITLE_AND_LICENSE_SECTION_TITLE_OWNER_NAME("titleInfo[titleName]:string"),
	ORDERING_BO_OOQ_TITLE_AND_LICENSE_SECTION_TITLE_ADDRESS_NAME("titleAddress[contactAddress][addressLine1]:string"),
	ORDERING_BO_OOQ_TITLE_AND_LICENSE_SECTION_TITLE_CITY_NAME("titleAddress[contactAddress][city]:string"),
	ORDERING_BO_OOQ_TITLE_AND_LICENSE_SECTION_TITLE_ZIP_NAME("titleAddress[contactAddress][postalCode]:string"),
	ORDERING_BO_OOQ_TITLE_AND_LICENSE_SECTION_TITLE_STATE_XPATH("//select[@name='titleAddress[contactAddress][stateProvince]:string']"),
	ORDERING_BO_OOQ_TITLE_AND_LICENSE_SECTION_TITLE_STATEID_NAME("codes[title[1]][titleCd]:string"),
	ORDERING_BO_OOQ_TITLE_AND_LICENSE_SECTION_TITLE_FEDERALID_NAME("codes[title[0]][titleCd]:string"),
	ORDERING_BO_OOQ_TITLE_AND_LICENSE_SECTION_TITLE_TAXEXEMPTNO_NAME("codes[title[2]][titleCd]:string"),
	ORDERING_BO_OOQ_TITLE_AND_LICENSE_SECTION_REGISTRATION_NAME_XPATH("//h2[contains(text(),'Registration Information')]"),
	ORDERING_BO_OOQ_TITLE_AND_LICENSE_SECTION_REGISTRATION_OWNER_NAME("titleInfo[registrationName]:string"),
	ORDERING_BO_OOQ_TITLE_AND_LICENSE_SECTION_REGISTRATION_ADDRESS_NAME("registrationAddress[contactAddress][addressLine1]:string"),
	ORDERING_BO_OOQ_TITLE_AND_LICENSE_SECTION_REGISTRATION_CITY_NAME("registrationAddress[contactAddress][city]:string"),
	ORDERING_BO_OOQ_TITLE_AND_LICENSE_SECTION_REGISTRATION_ZIP_NAME("registrationAddress[contactAddress][postalCode]:string"),
	ORDERING_BO_OOQ_TITLE_AND_LICENSE_SECTION_REGISTRATION_STATE_XPATH("//select[@name='registrationAddress[contactAddress][stateProvince]:string']"),
	ORDERING_BO_OOQ_TITLE_AND_LICENSE_SECTION_REGISTRATION_FEDERALID_NAME("codes[registration[0]][titleCd]:string"),
	ORDERING_BO_OOQ_TITLE_AND_LICENSE_SECTION_REGISTRATION_STATEID_NAME("codes[registration[1]][titleCd]:string"),
	ORDERING_BO_OOQ_TITLE_AND_LICENSE_SECTION_LIENHOLDER_OWNER_NAME("titleInfo[lienholderName]:string"),
	ORDERING_BO_OOQ_TITLE_AND_LICENSE_SECTION_LIENHOLDER_ADDRESS_NAME("lienholderAddress[contactAddress][addressLine1]:string"),
	ORDERING_BO_OOQ_TITLE_AND_LICENSE_SECTION_LIENHOLDER_CITY_NAME("lienholderAddress[contactAddress][city]:string"),
	ORDERING_BO_OOQ_TITLE_AND_LICENSE_SECTION_LIENHOLDER_ZIP_NAME("lienholderAddress[contactAddress][postalCode]:string"),
	ORDERING_BO_OOQ_TITLE_AND_LICENSE_SECTION_LIENHOLDER_STATE_XPATH("//select[@name='lienholderAddress[contactAddress][stateProvince]:string']"),
	ORDERING_BO_OOQ_TITLE_AND_LICENSE_SECTION_LIENHOLDER_FEDERALID_NAME("codes[lienholder[0]][titleCd]:string"),
	ORDERING_BO_OOQ_TITLE_AND_LICENSE_SECTION_LIENHOLDER_STATEID_NAME("codes[lienholder[1]][titleCd]:string"),
	ORDERING_BO_ON_ORDER_VEHICLE_TAB_ID("vehicleInfoTabId"),
	ORDERING_BO_ORD_YEAR_TEXT_NAME("numericYear:number"),
	ORDERING_BO_ORD_MANUFACTURER_TEXT_NAME("manufacturerDescription:string"),
	ORDERING_BO_ORD_MAKE_TEXT_NAME("divisionDescription:string"),
	ORDERING_BO_ORD_MODEL_TEXT_NAME("modelDescription:string"),
	ORDERING_BO_ORD_TRIM_CODE_TEXT_NAME("trimManufacturerCode:string"),
	ORDERING_BO_ORD_TRIM_TEXT_NAME("trimDescription:string"),
	ORDERING_BO_ORD_TRIM_DESCR_TEXT_NAME("trimDescriptionLong"),
	ORDERING_BO_ORD_FUEL_TYPE_NAME("fuelType"),
	ORDERING_BO_ORD_BODY_STYLE_CODE_NAME("bodyStyleCode:string"),
	ORDERING_BO_ORD_BODY_STYLE_DESCR_NAME("bodyStyleDescription:string"),
	ORDERING_BO_ORD_PRODUCT_CLASS_NAME("productClass"),
	ORDERING_BO_ORD_ACODE_NAME("acode:string"),
	ORDERING_BO_ORD_TRANSMISSION_NAME("transmissionDescription"),
	ORDERING_BO_ORD_ENGINE_NAME("engineDescription"),
	ORDERING_BO_ORD_WHEELBASE_NAME("wheelBaseAsString:string"),
	ORDERING_BO_ORD_GVWR_NAME("gvwr:number"),
	ORDERING_BO_ORD_SEAT_CAPACITY_NAME("numberOfSeats:number"),
	ORDERING_BO_ORD_NUMBER_OF_DOORS_NAME("numberOfDoors:number"),
	ORDERING_BO_ORD_BILLING_TAB_ID("billingInfoTabId"),
	ORDERING_BO_ORD_BILLING_LEASE_TERM_NAME("orderBilling[leaseTerm]:string"),
	ORDERING_BO_ORD_BILLING_ASSET_ID_NAME("orderBilling[clientUnitNumber]:string"),
	ORDERING_BO_ORD_BILLING_CLIENT_PO_NUMBER_NAME("orderBilling[clientPoNumber]:string"),
	ORDERING_BO_ORD_DIO_TAB_ID("dioInfoTabId"),
	ORDERING_BO_ORD_DIO_ADD_BUTTON_ID("add-dio"),
	ORDERING_BO_ORD_DIO_OPTION_CODE_NAME("dioInfo[dioRequestList][0][optionCode]:string"),
	ORDERING_BO_ORD_DIO_DPO_XPATH("//label[contains(@for,'dpoIndicator')]"),
	ORDERING_BO_ORD_DIO_DESCRIPTION_NAME("dioInfo[dioRequestList][0][optionDesc]:string"),
	ORDERING_BO_ORD_DIO_QUANTITY_NAME("dioInfo[dioRequestList][0][quantity]:number"),
	ORDERING_BO_ORD_DIO_OPTION_PRICE_NAME("dioInfo[dioRequestList][0][maxPriceAmt]:number"),
	ORDERING_BO_ORD_DIO_ADHOC_OPTION_XPATH("//label[contains(@for,'adhocInd')]"),
	ORDERING_BO_ORD_DEALER_TAB_ID("dealerInfoTabId"),
	ORDERING_BO_ORD_DEALER_DELIVERING_DEALER_CODE_NAME("deliveringDealer[supplierCode]:string"),
	ORDERING_BO_ORD_DEALER_DELIVERING_DEALER_CDFEE_NAME("deliveringDealer[codeFeeAmount][amount]:skip"),
	ORDERING_BO_ORD_DEALER_DELIVERING_DEALER_NAME_NAME("deliveringDealer[supplierName]:skip"),
	ORDERING_BO_ORD_DEALER_DELIVERING_DEALER_PHONE_NAME("deliveringDealer[supplierPhone]:skip"),
	ORDERING_BO_ORD_DEALER_ORDERING_DEALER_CODE_NAME("orderingDealer[supplierCode]:string"),
	ORDERING_BO_ORD_DEALER_ORDERING_DEALER_NAME_NAME("orderingDealer[supplierName]:skip"),
	ORDERING_BO_ORD_DEALER_ORDERING_DEALER_PHONE_NAME("orderingDealer[supplierPhone]:skip"),
	ORDERING_BO_ORD_TITLE_LICENSE_TAB_ID("titleInfoTabId"),
	ORDERING_BO_ORD_TITLE_LICENSE_PLATE_TYPE_NAME("titleWho[plateType]:string"),
	ORDERING_BO_ORD_UPFIT_ADD_BUTTON_ID("add-po"),
	ORDERING_BO_ORD_UPFIT_IFNO_TAB_ID("upfitInfoTabId"),
	ORDERING_BO_ORD_UPFIT_PO_SEARCH_ORDER_ID("order-search"),
	ORDERING_BO_ORD_UPFIT_PO_UPFIT_SPEC_SEARCH_ID("upfit-spec-search"),
	ORDERING_BO_ORD_UPFIT_PO_SELECT_SEARCH_OPTION_XPATH("//div[@class='tt-menu tt-open']//div//div[1]"),
	ORDERING_BO_ORD_UPFIT_PO_UPFITTER_SEARCH_ID("upfitter-search"),
	ORDERING_BO_ORD_UPFIT_PO_INSTALLER_SEARCH_ID("installer-search"),
	ORDERING_BO_ORD_UPFIT_PO_SHIP_TO_ID("ship-to-option"),
	ORDERING_BO_ORD_UPFIT_PO_DROP_SHIP_SEARCH_NAME("drop-ship-search"),
	ORDERING_BO_ORD_UPFIT_PO_WORK_TYPE_ID("work-type"),
	ORDERING_BO_ORD_UPFIT_PO_SAVE_ID("save"),
	ORDERING_BO_ORD_UPFIT_PO_SUPPLIER_ID_XPATH("//a[@class='upfit-po-header']//div[3]"),
	ORDERING_BO_ORD_UPFIT_PO_SUPPLIER_NAME_XPATH("//a[@class='upfit-po-header']//div[4]"),
	ORDERING_BO_ORD_UPFIT_PO_CANCEL_PO_XPATH("//a[@class='upfit-po-header']//div[7]/div"),
	ORDERING_BO_ORD_UPFIT_PO_CANCEL_PO_OK_XPATH("//div[@id='warning-dropship-popup' and @class='modal fade in']//button[@data-target='#warning-cancel-popup']"),
	ORDERING_BO_ORD_UPFIT_PO_PROCEED_CANCEL_XPATH("//div[@id='warning-cancel-popup' and @class='modal fade in']//button[@id='proceed-cancel']"),
	ORDERING_BO_ORD_UPFIT_PO_ORDER_STATUS_XPATH("//a[@class='upfit-po-header']//div[8]"),
	ORDERING_BO_ORD_APPROVAL_CREDIT_ERROR_NAME("creditIndicator"),
	ORDERING_BO_ORD_VEHICLE_ACK_BUTTON_ID("acknowledge"),
	ORDERING_BO_ORD_VEHICLE_ACK_YES_BUTTON_XPATH("//div[@class='modal-dialog']//button[@class='modal-ok-btn']"),
	ORDERING_BO_ORD_GENERAL_ORDER_ORDER_STATUS_XPATH("//form[@id='generalInfo-form']//label[contains(text(),'Order Status')]//following::span[1]"),
	ORDERING_BO_ORD_INSURANCE_ERROR_XPATH("//label[@for='approval-insurance']"),
	ORDERING_BO_ORD_BILLING_ERROR_XPATH("//label[@for='approval-billing']"),
	ORDERING_BO_ORD_DEALER_INSTALL_ERROR_XPATH("//label[@for='approval-dio']"),
	ORDERING_BO_ORD_TITLE_ERROR_XPATH("//label[@for='approval-title']"),
	ORDERING_BO_ORD_UPFIT_ERROR_XPATH("//label[@for='approval-upfit']"),
	ORDERING_BO_ORD_DEALER_ERROR_XPATH("//label[@for='approval-dealer']"),
	ORDERING_BO_ORD_UPFIT_RESEND_PO_BTN_XPATH("//div[text()=' Resend PO']"),
	ORDERING_BO_ORD_NEW_VEH_SPEC_YEAR_NAME("numericYear:number"),
	ORDERING_BO_ORD_NEW_VEH_SPEC_MAKE_NAME("divisionDescription:string"),
	ORDERING_BO_ORD_NEW_VEH_SPEC_MODEL_NAME("modelDescription:string"),
	ORDERING_BO_ORD_NEW_VEH_SPEC_TRIM_NAME("trim:string"),
	ORDERING_BO_ORD_NEW_VEH_SPEC_ACODE_NAME("acode:string"),
	ORDERING_BO_ORD_NEW_VEH_SPEC_WHEELBASE_NAME("wheelBaseAsString:string"),
	ORDERINNG_BO_ORD_MAINT_SUPPRESS_PO_WARNING_MESSAGE_CSS("#new-modal>div>div>div:nth-child(2)"),
	ORDERING_BO_ORD_MAINT_SUPPRESS_PO_YES_CSS("#new-modal>div>div>div:nth-child(3)>button:nth-child(2)"),
	ORDERING_BO_ORD_MAINT_SUPPRESS_PO_WARNING_POPUP_CSS("#new-modal>div.modal-dialog"),
	ORDERING_BO_ORD_MAINT_CANCEL_ORDER_CSS("button#cancel"),
	ORDERING_BO_ORD_MAINT_CONFIRM_CANCEL_FACTORY_ORDER_XPATH("//div[@class='modal fade in']//button[@class='button button--primary btn-spacing']"),
	ORDERING_BO_ORD_CANCEL_ORDER_XPATH("//button[@id ='cancel']"),
	ORDERING_BO_ORD_CANCEL_ORDER_YES_XPATH("(//div[contains(text(),'Are you sure, you want to cancel the order?')]//following::button[contains(text(),'Yes')])[1]"),
	ORDERING_BO_ORD_SEC_DIO_OPTION_CODE_NAME("dioInfo[dioRequestList][1][optionCode]:string"),
	ORDERING_BO_ORD_SEC_DIO_DESCRIPTION_NAME("dioInfo[dioRequestList][1][optionDesc]:string"),
	ORDERING_BO_ORD_SEC_DIO_QUANTITY_NAME("dioInfo[dioRequestList][1][quantity]:number"),
	ORDERING_BO_ORD_SEC_DIO_OPTION_PRICE_NAME("dioInfo[dioRequestList][1][maxPriceAmt]:number"),
	ORDERING_BO_ORD_REMOVE_USED_UNIT_ID("btn-removeUsedUnit"),
	ORDERING_BO_ORD_TELEMATICSINDICATOR_XPATH("//label[contains(text(),'Telematics Indicator')]//following::span[1]"),
	ORDERING_BO_DIO_ESTIMATED_COST_NAME("total:skip"),
	ORDERING_BO_DIO_SEARCH_DIO_LABEL_XPATH("//label[contains(text(),'Installed')]"),
	ORDERING_BO_DIO_SEARCH_DIO_OPTION_XPATH("//input[@id='dio-search']"),
	ORDERING_BO_DIO_SUPPLIERTOOLTIP_ICON_XPATH("//i[@class='fa fa-info fa-circle-info']"),
	ORDERING_BO_DIO_TABLE_COLUMN_HEADER_XPATH("//table[@id='dio-table']//tr[@class='main-row']//th"),
	ORDERING_BO_DIO_CHANGE_ORDER_TYPE_XPATH("//select[@name='coreOrder[orderType]:skip"),
	ORDERING_BO_DIO_SECTION_FIRST_ROW_XPATH("//section[@id='tab-dioInfo']//tr[@class='odd']//td"),
	ORDERING_BO_DIO_SECTION_FIRST_SEARCH_RESULT_XPATH("//div[@class='tt-dataset tt-dataset-dioSearchSmart']//div[1]"),
	ORDERING_BO_DIO_SECTION_ADHOCOPTION_NAME("dioInfo[dioRequestList][0][adhocInd]:string"),
	ORDERING_BO_DIO_LABEL_XPATH("//h1[contains(text(),'Dealer Installed Options')]"),
	ORDERING_BO_DIO_SEARCH_XPATH("//input[@id='dio-search']"),
	ORDERING_BO_DIO_COUNT_OF_TOTAL_RECORD_COUNT_XPATH("//div[@id='dio-table_info']"),
	ORDERING_BO_DIO_BO_Add_XPATH("//div[@id='add-dio']"),
	ORDERING_BO_DIO_BO_FIRST_DIO_XPATH("//tr[1]//td[1]//input[4]"),
	ORDERING_BO_DIO_BO_SECOND_DIO_XPATH("//tr[2]//td[1]//input[4]"),
	ORDERING_BO_DIO_BO_DELETE_ID("bulk_delete"),
	ORDERING_BO_ORD_BO_YES_XPATH("//div[@class='modal-dialog']//button[@class='button button--primary btn-spacing']"),
	ORDERING_BO_ORD_BO_DIO_TABLE_XPATH("//table[@id='dio-table']"),
	ORDERING_BO_ORD_BO_DIO_SAVE_XPATH("//input[@class='btn save-order']"),
	ORDERING_BO_ORD_MAINT_DIO_SECTION_XPATH("//h1[text()='Dealer Installed Options']"),
	ORDERING_BO_ORD_MAINT_DIO_SEARCH_ID("dio-search"),
	ORDERING_BO_ORD_UPFIT_PO_DROP_SHIP_SEARCH_ID("drop-ship-search"),
	ORDERING_BO_OOQ_ORDER_NEW_USED_DROP_DOWN_NAME("coreOrder[newUsed]:skip"),
	ORDERING_BO_OOQ_ORDER_COMPETITOR_TO_NOTIFY_DROP_DOWN_NAME("usedUnit[notifyCompetitor]:skip"),
	ORDERING_BO_ORD_NEW_VEH_SPEC_MANUFACTURER_NAME("manufacturerDescription:string"),
	ORDERING_BO_ORD_NEW_VEH_SPEC_CUST_FINFAN_NAME("finFanValue"), 
	ORDERING_BO_ORD_MAINT_UPFIT_LINE_ITEM_SHIP_TO_NAME("ship-to-option:skip"), 
	ORDERING_BO_ORD_MAINT_UPFIT_LINE_ITEM_CATEGORY_XPATH("//select[contains(@id, 'optionCategory')]"), 
	ORDERING_BO_ORD_MAINT_UPFIT_LINE_ITEM_DESCRIPTION_XPATH("//input[contains(@id, 'optionDescription')]"), 
	ORDERING_BO_ORD_MAINT_UPFIT_LINE_ITEM_EXT_DESCRIPTION_XPATH("//textarea[contains(@id, 'extendedDescription')]"), 
	ORDERING_BO_ORD_MAINT_UPFIT_LINE_ITEM_QUANTITY_XPATH("//input[contains(@id, 'optionQuantity')]"), 
	ORDERING_BO_ORD_MAINT_UPFIT_LINE_ITEM_AMOUNT_XPATH("//input[contains(@id, 'amount')]"),
	ORDERING_BO_ORD_TITLE_LICENSE_WHO_TO_TITLE_NAME("titleWho[whoToTitle]:string"), 
	ORDERING_BO_OOQ_TITLE_AND_LICENSE_SECTION_STATE_VALUE_XPATH("//label[contains(text(),'Abbrev')]//following::div[4]"), 
	ORDERING_BO_ORD_DEALER_DELIVERING_DEALER_CONTACT_NAME_NAME("deliveringDealer[supplierContactName]:skip"), 
	ORDERING_BO_ORD_DEALER_DELIVERING_DEALER_EMAIL_NAME("deliveringDealer[supplierEmail]:skip"), 
	ORDERING_BO_ORD_DEALER_ORDERING_DEALER_CONTACT_NAME_NAME("orderingDealer[supplierContactName]:skip"), 
	ORDERING_BO_ORD_DEALER_ORDERING_DEALER_EMAIL_NAME("orderingDealer[supplierEmail]:skip"),
	ORDERING_BO_OOQ_STATUS_DATE_FIELD_XPATH("//input[@name='statusDate:string']"),
	ORDERING_BO_ORD_DELIVERING_DEALER_CODE_TEXTBOX_XPATH("//form[@id='dealerInfo-form']//label[text()='Delivering Dealer Code']/../..//input[@type='text']"),
	ORDERING_BO_ORD_DEALER_INFO_SAVE_BUTTON_XPATH("//form[@id='dealerInfo-form']//button[@id='save-dealerInfo']"),
	ORDERING_BO_ORD_MAINT_UPFITTAB_ADDED_UPFIT_ESTIMEATED_LEAD_TIME_WEEK_POS_ID("lead-time"),
	ORDERING_BO_ORD_MAINT_ADD_STATUS_SAVE_XPATH("//button[ contains(@class,'js-save-po-status') and contains(text(), 'Save')]"),
	ORDERING_BO_ORD_MAINT_UPFIT_PO_CSS("div.export-po-upfit"),
	ORDERING_BO_ORD_MAINT_VIN_CSS("input#vinvehicle"),
	ORDERING_BO_ORD_MAINT_UNIT_CSS("input#newUnitId"),
	ORDERING_BO_ORD_MAINT_ORDER_TYPE_CSS("span#general-order-name"),
	ORDERING_BO_ORD_MAINT_TITLE_LICENSE_SAVE_ID("save-titleform-info"),
	ORDERING_BO_ORD_MAINT_WARNING_POP_UP_YES_BUTTON_XPATH("//button[@class='button button--primary btn-spacing js-button-primary']"),
	ORDERING_BO_ORD_MAINT_DIO_SAVE_XPATH("//button[@id='save-dioInfo']"),
	ORDERING_BO_ORD_MAINT_DIO_SECTION_ID("dioInfo-form"),
	;

	private String value;

	OrderingBOOrdMaintPageEnum(String value) {
		this.value = value;
	}

	public String getValue() {
		return value;
	}	

	@Override
	public String toString() {
		return value;
	}

}
