package com.element.fleet.ordering.enums;

public enum OrderingElementDeliveringDealerAssignmentRulesPageEnum {

	ORDERING_BO_EDDAR_SIDE_MENU_XPATH("//div[@data-target='EDARQ']//div[@class='title']"),
	ORDERING_BO_EDDAR_TITLE_XPATH("//h1[@id='queue-page-title']"),
	ORDERING_BO_EDDAR_GENERIC_LABEL_XPATH("//body//div[@id='mainContainer']//section[1]//input[@name='%s']"),
	ORDERING_BO_EDDAR_SEARCH_FIELDS_VALUE_XPATH("//body//div[@id='mainContainer']//section[1]//input[@name='%s']/..//input"),
	ORDERING_BO_EDDAR_CORP_LABEL_XPATH("//input[@name='corp']"),
	ORDERING_BO_EDDAR_RULE_ID_LABEL_XPATH("//input[@name='ruleId']"),
	ORDERING_BO_EDDAR_RULE_NAME_LABEL_XPATH("//input[@name='ruleName']"),
	ORDERING_BO_EDDAR_START_DATE_LABEL_XPATH("//input[@name='startDate']"),
	ORDERING_BO_EDDAR_END_DATE_LABEL_XPATH("//input[@name='endDate']"),
	ORDERING_BO_EDDAR_STATE_PROVINCE_LABEL_XPATH("//input[@name='province']"),
	ORDERING_BO_EDDAR_COUNTY_LABEL_XPATH("//input[@name='county']"),
	ORDERING_BO_EDDAR_CITY_LABEL_XPATH("//input[@name='city']"),
	ORDERING_BO_EDDAR_ZIP_LABEL_XPATH("//input[@name='zip']"),
	ORDERING_BO_EDDAR_MAKE_LABEL_XPATH("//input[@name='make']"),
	ORDERING_BO_EDDAR_MODEL_LABEL_XPATH("//input[@name='model']"),
	ORDERING_BO_EDDAR_PRODUCT_CLASS_LABEL_XPATH("//input[@name='productClass']"),
	ORDERING_BO_EDDAR_MAX_DISTANCE_LABEL_XPATH("//input[@name='distance']"),
	ORDERING_BO_EDDAR_MAX_COURTESY_DELIVERY_LABEL_XPATH("//input[@name='cdFee']"),
	ORDERING_BO_EDDAR_DEALER_CODE_LABEL_XPATH("//input[@name='dealerCode']"),
	ORDERING_BO_EDDAR_DEALER_NAME_LABEL_XPATH("//input[@name='dealerName']"),
	ORDERING_BO_EDDAR_ALWAYS_USE_NEVER_USE_LABEL_XPATH("//input[@name='alwaysNever']"),
	ORDERING_BO_EDDAR_TOGGLE_COLUMN_BUTTON_XPATH("//span[@class='multiselect-selected-text']"),
	ORDERING_BO_EDDAR_SEARCH_BUTTON_XPATH("//span[@class='fa fa-search']"),
	ORDERING_BO_EDDAR_CLEAR_FILTER_BUTTON_XPATH("//div[@class='btn green btn-shared clear-filters']"),
	ORDERING_BO_EDDAR_EXPORT_BUTTON_CSS("body.el-ord-back-office:nth-child(2) div.wrapper:nth-child(1) section.contentWrapper.row-eq-height:nth-child(2) div.mainWrapper.clearfix:nth-child(3) div.active-queue:nth-child(4) div.queue-wrapper div.queue div.row.search-wrapper div.col-sm-4.col-md-4.col-lg-4.button-wrapper div.btn-group div.btn.blue.btn-shared.queue-export:nth-child(4) > span:nth-child(2)"),
	ORDERING_BO_EDDAR_ADD_NEW_BUTTON_XPATH("//div[@class='btn green btn-shared addNew']"),
	ORDERING_BO_EDDAR_DELETE_BUTTON_XPATH("//div[@class='btn custom-action green btn-shared bulkDelete']"),
	ORDERING_BO_EDDAR_TABLE_SCROLL_BODY_CSS("div.dataTables_scrollBody"),
	ORDERING_BO_EDDAR_TABLE_HEADER_XPATH("//thead/tr[1]/th[]"),
	ORDERING_BO_EDDAR_TABLE_CHECK_ALL_XPATH("//thead/tr[1]/th[1]/input[1]"),
	ORDERING_BO_EDDAR_TABLE_CORP_XPATH("//th[@data-name='corp']"),
	ORDERING_BO_EDDAR_TABLE_RULE_ID_XPATH("//th[@data-name='ruleId']"),
	ORDERING_BO_EDDAR_TABLE_RULE_NAME_XPATH("//th[@data-name='ruleName']"),
	ORDERING_BO_EDDAR_TABLE_START_DATE_XPATH("//th[@data-name='startDate']"),
	ORDERING_BO_EDDAR_TABLE_END_DATE_XPATH("//th[@data-name='endDate']"),
	ORDERING_BO_EDDAR_TABLE_STATE_XPATH("//th[@data-name='province']"),
	ORDERING_BO_EDDAR_TABLE_COUNTY_XPATH("//th[@data-name='county']"),
	ORDERING_BO_EDDAR_TABLE_CITY_XPATH("//th[@data-name='city']"),
	ORDERING_BO_EDDAR_TABLE_ZIP_XPATH("//th[@data-name='zip']"),
	ORDERING_BO_EDDAR_TABLE_MAKE_XPATH("//th[@data-name='make']"),
	ORDERING_BO_EDDAR_TABLE_MODEL_XPATH("//th[@data-name='model']"),
	ORDERING_BO_EDDAR_TABLE_PRODUCT_CLASS_XPATH("//th[@data-name='productClass']"),
	ORDERING_BO_EDDAR_TABLE_MAX_DISTANCE_XPATH("//th[@data-name='distance']"),
	ORDERING_BO_EDDAR_TABLE_MAX_COURTESY_DELIVERY_XPATH("//th[@data-name='cdFee']"),
	ORDERING_BO_EDDAR_TABLE_DEALER_CODE_XPATH("//th[@data-name='dealerCode']"),
	ORDERING_BO_EDDAR_TABLE_DEALER_NAME_XPATH("//th[@data-name='dealerName']"),
	ORDERING_BO_EDDAR_TABLE_ALWAYS_USE_NEVER_USE_XPATH("//th[@data-name='alwaysNever']"),
	ORDERING_BO_EDDAR_TABLE_LAST_UPDATED_BY_XPATH("//th[@data-name='lastUpdateduserId']"),
	ORDERING_BO_EDDAR_TABLE_LAST_UPDATED_ON_XPATH("//th[@data-name='lastUpdateduserDate']"),
	ORDERING_BO_EDDAR_TABLE_SEARCHED_RECORD_XPATH("//body//div[@id='mainContainer']//section[1]//input[@name='%s']"),
	ORDERING_BO_EDDAR_TABLE_COLUMN_NAME_XPATH("//table[@class='table datatable queue-table dataTable no-footer']//tr[@class='main-row']//th"),
	ORDERING_BO_EDDAR_TOGGLE_ACTIVE_COLUMN_LABEL_XPATH("//ul[@class='multiselect-container dropdown-menu']//li[@class='active']"),
	ORDERING_BO_EDDAR_ADD_REMOVE_COMLUMN_XPATH("//ul[@class='multiselect-container dropdown-menu']//li//a//label[contains(text(),'%s')]"),
	ORDERING_BO_EDDAR_CORP_COLUMN_TABLE_DATA_XPATH("//tbody//td[2]"),
	ORDERING_BO_EDDAR_LAST_UPDATED_ON_COLUMN_TABLE_DATA_XPATH("//tbody//td[20]"),
	ORDERING_BO_EDDAR_MAKE_COLUMN_TABLE_DATA_XPATH("//tbody//td[11]"),
	ORDERING_BO_EDDAR_TOGGLE_COLUMN_CHECKBOX_XPATH("//body/div[@id='mainContainer']/section[1]//label[@class='checkbox']"),
	ORDERING_BO_EDDAR_ADD_RULE_PAGE_CORP_XPATH("//select[@id='corps']"),
	ORDERING_BO_EDDAR_ADD_RULE_PAGE_CORP_FA_XPATH("//select[@id='corps']//option[@value='FA']"),
	ORDERING_BO_EDDAR_ADD_RULE_PAGE_CORP_CA_XPATH("//select[@id='corps']//option[@value='CA']"),
	ORDERING_BO_EDDAR_ADD_RULE_FLEET_INPUT_XPATH("//input[@id='search-client']"),
	ORDERING_BO_EDDAR_ADD_RULE_SEARCHED_FLEET_XPATH("//div[@class='tt-dataset tt-dataset-contactSearch']//div[1]]"),
	ORDERING_BO_EDDAR_ADD_RULE_RULE_NAME_XPATH("//input[@id='group-name']"),
	ORDERING_BO_EDDAR_ADD_RULE_MAX_COURTESY_DELIVERY_FEE_XPATH("//input[@name='INPUT-CD']"),
	ORDERING_BO_EDDAR_ADD_RULE_MAX_DELIVERY_DISTANCE_XPATH("//input[@name='INPUT-DIST']"),
	ORDERING_BO_EDDAR_ADD_RULE_HEADING_XPATH("//div[@id='customersubtitle']"),
	ORDERING_BO_EDDAR_ADD_RULE_START_DATE_XPATH("//input[@id='start-date']"),
	ORDERING_BO_EDDAR_ADD_RULE_START_DATE_SELECTED_DATE_XPATH("//a[@class='ui-state-default ui-state-highlight ui-state-active ui-state-hover']"),
	ORDERING_BO_EDDAR_ADD_RULE_END_DATE_XPATH("//input[@id='end-date']"),
	ORDERING_BO_EDDAR_ADD_RULE_END_DATE_SELECTED_DATE_XPATH("//a[@class='ui-state-default ui-state-highlight ui-state-hover']"),
	ORDERING_BO_EDDAR_ADD_RULE_SELECT_STATE_XPATH("//div[@id='multiSelecStates']//button[@class='btn multiselect dropdown-toggle btn-default']"),
	ORDERING_BO_EDDAR_ADD_RULE_SELECTED_STATE_XPATH("//input[@value='ALASKA']"),
	ORDERING_BO_EDDAR_ADD_RULE_SELECT_COUNTRY_BUTTON_XPATH("//div[@id='CNTY']//div[@class='btn county-selector']"),
	ORDERING_BO_EDDAR_ADD_RULE_SELECT_COUNTRY_POPUP_HEADING_XPATH("//h3[@class='text-center primary-color capturePopupHeader']"),
	ORDERING_BO_EDDAR_ADD_RULE_SELECTED_COUNTRY_FROM_POPUP_XPATH("//div[@class='county-list-wrapper']//span[@class='county-checkbox']//input[@id='1']"),
	ORDERING_BO_EDDAR_ADD_RULE_SELECT_COUNTRY_POPUP_OK_BUTTON_XPATH("//button[@class='county-ok-btn']"),
	ORDERING_BO_EDDAR_ADD_RULE_SELECT_COUNTRY_POPUP_CLOSE_BUTTON_XPATH("//button[@class='county-close-btn']"),
	ORDERING_BO_EDDAR_ADD_RULE_SELECT_PRODUCT_CLASS_BUTTON_XPATH("//div[@class='btn product-class-selector']"),
	ORDERING_BO_EDDAR_ADD_RULE_SELECT_PRODUCT_CLASS_POPUP_HEADING_XPATH("//h3[@class='text-center primary-color capturePopupHeader']"),
	ORDERING_BO_EDDAR_ADD_RULE_SELECTED_PRODUCT_CLASS_FROM_POPUP_XPATH("//div[@class='product-class-list-wrapper']//span[@class='product-class-checkbox']//input[@id='1']"),
	ORDERING_BO_EDDAR_ADD_RULE_SELECT_PRODUCT_CLASS_POPUP_OK_BUTTON_XPATH("//button[@class='product-class-ok-btn']"),
	ORDERING_BO_EDDAR_ADD_RULE_SELECT_PRODUCT_CLASS_POPUP_CLOSE_BUTTON_XPATH("//button[@class='product-class-close-btn']"),
	ORDERING_BO_EDDAR_ADD_RULE_CITY_XPATH("//input[@name='INPUT-CITY']"),
	ORDERING_BO_EDDAR_ADD_RULE_ZIP_XPATH("//input[@name='INPUT-ZIP']"),
	ORDERING_BO_EDDAR_ADD_RULE_MAKE_XPATH("//div[@id='MAKE']//button[@class='btn multiselect dropdown-toggle btn-default']"),
	ORDERING_BO_EDDAR_ADD_RULE_MODEL_XPATH("//div[@id='MDL']//button[@class='btn multiselect dropdown-toggle btn-default']"),
	ORDERING_BO_EDDAR_ADD_RULE_SAVE_BUTTON_XPATH("//div[@id='save-group']"),
	ORDERING_BO_EDDAR_ADD_RULE_ALWAYS_NEVER_USE_ERROR_MESSAGE_XPATH("//div[@class='noty-msg x-style']"),
	ORDERING_BO_EDDAR_ADD_RULE_SAVE_POPUP_MESSAGE_XPATH("//div[@class='noty-msg x-style']"),
	ORDERING_BO_EDDAR_ADD_RULE_BACK_TO_QUEUE_VIEW_XPATH("//div[@id='browser-back-cdar']"),
	ORDERING_BO_EDDAR_SEARCHED_RULE_QUEUE_VIEW_XPATH("//td[@data-name='ruleName']"),
	ORDERING_BO_EDDAR_SEARCHED_RULE_CHECKBOX_XPATH("//tbody/tr[1]/td[1]/input[1]"),
	ORDERING_BO_EDDAR_DELETE_CONFIRMATION_POPUP_XPATH("//div[@class='modal-content']//div[@class='modal-body new-modal__body']"),
	ORDERING_BO_EDDAR_DELETE_CONFIRMATION_POPUP_OK_BUTTON_XPATH("//button[@class='button button--primary btn-spacing js-button-primary']"),
	ORDERING_BO_EDDAR_SUCCESSFUL_DELETION_CONFIRMATION_XPATH("//div[@class='noty-msg x-style']"),
	ORDERING_BO_EDDAR_ADD_RULE_DEALER_XPATH("//input[@id='search-dealer']"),
	ORDERING_BO_EDDAR_ADD_RULE_DELETE_BUTTON_XPATH("//div[@id='delete-group']"),
	ORDERING_BO_EDDAR_ADD_RULE_REMOVE_STATE_XPATH("//div[@data-code='ST']//i[@class='fa fa-times close-tag']"),
	ORDERING_BO_EDDAR_MAINTENANCE_PAGE_DELETE_CONFIRMATION_POPUP_XPATH("//div[@class='modal-body new-modal__body']"),
	ORDERING_BO_EDDAR_MAINTENANCE_SUCCESSFUL_DELETION_CONFIRMATION_XPATH("//div[@class='noty-msg x-style']"),
	ORDERING_BO_EDDAR_NO_RECORD_FOUND_XPATH("//td[@class='dataTables_empty']"),
	;

	private String value;

	private OrderingElementDeliveringDealerAssignmentRulesPageEnum(String value) {
		this.value = value;
	}

	public String getValue() {
		return value;
	}

	@Override
	public String toString() {
		return value;
	}

}

